import { FileConversionTool, ConversionCategory } from '../types/fileConv';

export const FILE_CONV_CATEGORIES: { id: ConversionCategory; name: string; description: string; icon: string }[] = [
  { id: 'universal', name: 'Universal Converter', description: 'Auto-detect format and convert between any supported types.', icon: 'Layers' },
  { id: 'document', name: 'Document', description: 'DOCX, PDF, ODT, RTF, TXT, HTML, Markdown, XML, LaTeX.', icon: 'FileText' },
  { id: 'spreadsheet', name: 'Spreadsheet & Data', description: 'XLSX, ODS, CSV, TSV, JSON, YAML.', icon: 'Table' },
  { id: 'presentation', name: 'Presentation', description: 'PPTX, ODP, PDF slide exports.', icon: 'Presentation' },
  { id: 'image', name: 'Image', description: 'JPG, PNG, WebP, AVIF, HEIC, SVG, GIF, BMP, TIFF, ICO.', icon: 'Image' },
  { id: 'audio', name: 'Audio', description: 'MP3, WAV, OGG, FLAC, AAC, OPUS, AIFF, WMA.', icon: 'Music' },
  { id: 'video', name: 'Video', description: 'MP4, WebM, MOV, AVI, MKV, FLV, WMV, OGV.', icon: 'Video' },
  { id: 'ebook', name: 'Ebook', description: 'EPUB, MOBI, AZW3, FB2, CBZ, HTML, PDF.', icon: 'BookOpen' },
  { id: 'archive', name: 'Archive', description: 'ZIP, TAR, GZ, 7Z, RAR, BZ2, ISO extraction.', icon: 'Archive' },
  { id: 'font', name: 'Font & Icon', description: 'TTF, OTF, WOFF, WOFF2, EOT, SVG, ICO.', icon: 'Type' },
  { id: 'developer', name: 'Developer & Markup', description: 'JSON, XML, YAML, CSV, Markdown, Base64, SRT, VCF, ICS.', icon: 'Code' },
  { id: 'web', name: 'Web Assets', description: 'Favicon packs, responsive srcset, CSS image helpers.', icon: 'Globe' },
  { id: 'workflows', name: 'AquaTools Workflows', description: 'Smart recommendations, size budgets, health scanners, diffs.', icon: 'Sparkles' },
];

export const FILE_CONVERSION_TOOLS: FileConversionTool[] = [
  // 1. Universal
  {
    id: 'universal-auto-convert',
    slug: 'universal-convert',
    category: 'universal',
    title: 'Universal Auto Converter',
    description: 'Detects input format automatically and converts to target document, image, audio, or data format.',
    acceptedMimeTypes: ['*/*'],
    acceptedExtensions: ['*'],
    outputFormats: ['pdf', 'png', 'jpg', 'webp', 'txt', 'json', 'csv', 'md'],
    processingMode: 'browser',
    status: 'ready',
    maxRecommendedBytes: 50 * 1024 * 1024,
    privacyNote: 'Processed 100% locally in browser memory. Zero server uploads.',
    knownLimitations: ['Complex proprietary binary formats require specific parsers.'],
    load: async () => Promise.resolve(true),
  },

  // 2. Document
  {
    id: 'doc-to-pdf',
    slug: 'doc-to-pdf',
    category: 'document',
    title: 'Document to PDF Converter',
    description: 'Convert text, markdown, HTML, and rich documents into clean PDF files locally.',
    acceptedMimeTypes: ['text/plain', 'text/markdown', 'text/html', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    acceptedExtensions: ['txt', 'md', 'html', 'docx'],
    outputFormats: ['pdf', 'txt', 'html'],
    processingMode: 'hybrid',
    status: 'ready',
    maxRecommendedBytes: 30 * 1024 * 1024,
    privacyNote: 'Rendered locally via PDF-lib in browser memory.',
    knownLimitations: ['Complex Word formatting may require font substitution.'],
    load: async () => Promise.resolve(true),
  },
  {
    id: 'pdf-to-text',
    slug: 'pdf-to-text',
    category: 'document',
    title: 'PDF to Text & HTML',
    description: 'Extract raw text or HTML structure from searchable PDF files.',
    acceptedMimeTypes: ['application/pdf'],
    acceptedExtensions: ['pdf'],
    outputFormats: ['txt', 'html', 'json'],
    processingMode: 'browser',
    status: 'ready',
    maxRecommendedBytes: 40 * 1024 * 1024,
    privacyNote: 'Extracted locally using PDF.js without cloud roundtrips.',
    knownLimitations: ['Scanned image-based PDFs require OCR (coming soon).'],
    load: async () => Promise.resolve(true),
  },

  // 3. Spreadsheet & Data
  {
    id: 'csv-json-converter',
    slug: 'csv-json-converter',
    category: 'spreadsheet',
    title: 'CSV / Excel to JSON & YAML',
    description: 'Convert tabular CSV, TSV, or spreadsheet data into structured JSON, YAML, or XML.',
    acceptedMimeTypes: ['text/csv', 'text/tab-separated-values', 'application/json'],
    acceptedExtensions: ['csv', 'tsv', 'json', 'xlsx'],
    outputFormats: ['json', 'yaml', 'csv', 'xml'],
    processingMode: 'browser',
    status: 'ready',
    maxRecommendedBytes: 25 * 1024 * 1024,
    privacyNote: 'Parsed entirely in local JavaScript runtime.',
    knownLimitations: ['Multi-sheet workbook support limited to active sheet in CSV mode.'],
    load: async () => Promise.resolve(true),
  },

  // 4. Presentation
  {
    id: 'presentation-pdf-export',
    slug: 'presentation-pdf-export',
    category: 'presentation',
    title: 'Presentation Slide PDF Export',
    description: 'Export presentation slides and image decks into structured presentation PDFs.',
    acceptedMimeTypes: ['application/vnd.openxmlformats-officedocument.presentationml.presentation', 'image/*'],
    acceptedExtensions: ['pptx', 'png', 'jpg'],
    outputFormats: ['pdf'],
    processingMode: 'browser',
    status: 'beta',
    maxRecommendedBytes: 50 * 1024 * 1024,
    privacyNote: 'Slide rendering executed locally.',
    knownLimitations: ['Slide animations and embedded videos are omitted in static PDF exports.'],
    load: async () => Promise.resolve(true),
  },

  // 5. Image
  {
    id: 'image-format-converter',
    slug: 'image-format-converter',
    category: 'image',
    title: 'Universal Image Format Converter',
    description: 'Convert between JPG, PNG, WebP, AVIF, HEIC, BMP, TIFF, and ICO with quality controls.',
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/heic', 'image/svg+xml', 'image/bmp', 'image/tiff', 'image/x-icon'],
    acceptedExtensions: ['jpg', 'jpeg', 'png', 'webp', 'avif', 'heic', 'svg', 'bmp', 'tiff', 'ico'],
    outputFormats: ['jpg', 'png', 'webp', 'avif', 'bmp', 'ico'],
    processingMode: 'browser',
    status: 'ready',
    maxRecommendedBytes: 40 * 1024 * 1024,
    privacyNote: 'Canvas-accelerated local encoding. Zero server uploads.',
    knownLimitations: ['HEIC decoding depends on browser/OS codec support.'],
    load: async () => Promise.resolve(true),
  },

  // 6. Audio
  {
    id: 'audio-format-transcoder',
    slug: 'audio-format-transcoder',
    category: 'audio',
    title: 'Browser Audio Transcoder',
    description: 'Convert and trim browser-supported audio formats (WAV, MP3, OGG, AAC, FLAC).',
    acceptedMimeTypes: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/flac', 'audio/aac'],
    acceptedExtensions: ['mp3', 'wav', 'ogg', 'flac', 'aac', 'm4a', 'opus'],
    outputFormats: ['wav', 'mp3', 'ogg'],
    processingMode: 'browser',
    status: 'beta',
    maxRecommendedBytes: 100 * 1024 * 1024,
    privacyNote: 'Decoded and encoded locally using Web Audio API.',
    knownLimitations: ['Encrypted or DRM-protected audio cannot be processed.'],
    load: async () => Promise.resolve(true),
  },

  // 7. Video
  {
    id: 'video-transcode-extract',
    slug: 'video-transcode-extract',
    category: 'video',
    title: 'Video Frame & Audio Extractor',
    description: 'Extract frames, convert lightweight video snippets, and inspect codecs locally.',
    acceptedMimeTypes: ['video/mp4', 'video/webm', 'video/ogg', 'video/quicktime'],
    acceptedExtensions: ['mp4', 'webm', 'mov', 'avi', 'mkv'],
    outputFormats: ['png', 'jpg', 'mp4', 'webm'],
    processingMode: 'browser',
    status: 'beta',
    maxRecommendedBytes: 200 * 1024 * 1024,
    privacyNote: 'Video frames processed locally in browser memory.',
    knownLimitations: ['Heavy transcoding requires WebAssembly codecs (coming soon for heavy MKV/AVI).'],
    load: async () => Promise.resolve(true),
  },

  // 8. Ebook
  {
    id: 'ebook-converter',
    slug: 'ebook-converter',
    category: 'ebook',
    title: 'Ebook Format Converter',
    description: 'Convert EPUB, Markdown, and text into readable PDF or reflowable formats.',
    acceptedMimeTypes: ['application/epub+zip', 'text/markdown', 'application/x-mobipocket-ebook'],
    acceptedExtensions: ['epub', 'md', 'mobi', 'txt', 'fb2'],
    outputFormats: ['pdf', 'txt', 'html'],
    processingMode: 'browser',
    status: 'beta',
    maxRecommendedBytes: 50 * 1024 * 1024,
    privacyNote: 'Processed entirely in local memory.',
    knownLimitations: ['DRM-protected ebooks cannot be parsed or converted.'],
    load: async () => Promise.resolve(true),
  },

  // 9. Archive
  {
    id: 'archive-extractor-creator',
    slug: 'archive-extractor-creator',
    category: 'archive',
    title: 'Archive Extractor & ZIP Creator',
    description: 'Inspect, extract, and create ZIP, TAR, and GZ archives securely with path traversal protection.',
    acceptedMimeTypes: ['application/zip', 'application/x-tar', 'application/gzip', 'application/x-7z-compressed'],
    acceptedExtensions: ['zip', 'tar', 'gz', '7z'],
    outputFormats: ['zip', 'tar'],
    processingMode: 'browser',
    status: 'ready',
    maxRecommendedBytes: 150 * 1024 * 1024,
    privacyNote: 'Client-side JSZip extraction with strict anti-traversal safety checks.',
    knownLimitations: ['Password-encrypted archives require valid passwords.'],
    load: async () => Promise.resolve(true),
  },

  // 10. Font & Icon
  {
    id: 'font-icon-converter',
    slug: 'font-icon-converter',
    category: 'font',
    title: 'Font & Icon Pack Converter',
    description: 'Convert between WOFF, WOFF2, TTF, OTF font formats and generate ICO / PWA icon packs.',
    acceptedMimeTypes: ['font/ttf', 'font/otf', 'font/woff', 'font/woff2', 'image/svg+xml', 'image/png'],
    acceptedExtensions: ['ttf', 'otf', 'woff', 'woff2', 'svg', 'png'],
    outputFormats: ['woff', 'woff2', 'ttf', 'ico', 'png'],
    processingMode: 'browser',
    status: 'ready',
    maxRecommendedBytes: 20 * 1024 * 1024,
    privacyNote: 'Font binaries converted safely. Never executed as code.',
    knownLimitations: ['Proprietary hinting tables may be normalized during conversion.'],
    load: async () => Promise.resolve(true),
  },

  // 11. Developer & Markup
  {
    id: 'developer-markup-formatter',
    slug: 'developer-markup-formatter',
    category: 'developer',
    title: 'Developer Markup & Data Formatter',
    description: 'Format, validate, and convert JSON, XML, YAML, CSV, Markdown, Base64, and Data URIs.',
    acceptedMimeTypes: ['application/json', 'text/xml', 'text/yaml', 'text/markdown', 'text/csv'],
    acceptedExtensions: ['json', 'xml', 'yaml', 'yml', 'md', 'csv', 'tsv', 'srt', 'vcf', 'ics'],
    outputFormats: ['json', 'xml', 'yaml', 'md', 'csv', 'base64', 'txt'],
    processingMode: 'browser',
    status: 'ready',
    maxRecommendedBytes: 30 * 1024 * 1024,
    privacyNote: 'Parsed and validated locally in browser runtime.',
    knownLimitations: ['Extremely large multi-megabyte JSON trees may impact UI responsiveness.'],
    load: async () => Promise.resolve(true),
  },

  // 12. Web Assets
  {
    id: 'web-assets-generator',
    slug: 'web-assets-generator',
    category: 'web',
    title: 'Responsive Web Assets & Favicon Studio',
    description: 'Generate responsive srcset variations, PWA icon manifests, and optimized web images.',
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml'],
    acceptedExtensions: ['jpg', 'jpeg', 'png', 'webp', 'svg'],
    outputFormats: ['zip', 'png', 'webp'],
    processingMode: 'browser',
    status: 'ready',
    maxRecommendedBytes: 40 * 1024 * 1024,
    privacyNote: 'All asset resizing and packaging performed locally.',
    knownLimitations: ['Input image must be at least 512x512 pixels for full icon pack generation.'],
    load: async () => Promise.resolve(true),
  },

  // 13. Workflows
  {
    id: 'aquatools-workflow-hub',
    slug: 'aquatools-workflows',
    category: 'workflows',
    title: 'AquaTools Advanced Conversion Workflows',
    description: 'Smart recommendations, size budget optimization, health scanners, round-trip testers, and diff reports.',
    acceptedMimeTypes: ['*/*'],
    acceptedExtensions: ['*'],
    outputFormats: ['report', 'zip', 'json'],
    processingMode: 'browser',
    status: 'ready',
    maxRecommendedBytes: 100 * 1024 * 1024,
    privacyNote: 'Privacy-first local workflow orchestration.',
    knownLimitations: ['Designed for client-side multi-file pipelines.'],
    load: async () => Promise.resolve(true),
  },
];

export const getFileConvToolBySlug = (slug: string): FileConversionTool | undefined => {
  return FILE_CONVERSION_TOOLS.find((t) => t.slug === slug || t.id === slug);
};
