import { ImageCategoryMeta, ImageToolCategory, ImageToolDefinition } from '../types/image';

export const IMAGE_CATEGORIES: ImageCategoryMeta[] = [
  {
    id: 'convert',
    name: 'Convert',
    shortName: 'Convert',
    description: 'Transform between JPG, PNG, WebP, AVIF, SVG, GIF, BMP, and ICO client-side.',
    iconName: 'RefreshCw',
    accentColor: 'from-cyan-500/20 to-blue-500/10 border-cyan-500/30 text-cyan-400',
  },
  {
    id: 'compress-optimize',
    name: 'Compress & Optimize',
    shortName: 'Compress',
    description: 'Reduce image file sizes, target specific byte limits, and inspect before/after differences.',
    iconName: 'Zap',
    accentColor: 'from-teal-500/20 to-emerald-500/10 border-teal-500/30 text-teal-400',
  },
  {
    id: 'resize-crop',
    name: 'Resize & Crop',
    shortName: 'Resize & Crop',
    description: 'Pixel-perfect dimensions, aspect ratio constraints, freeform cropping, rotate, and straighten.',
    iconName: 'Crop',
    accentColor: 'from-sky-500/20 to-indigo-500/10 border-sky-500/30 text-sky-400',
  },
  {
    id: 'edit-design',
    name: 'Edit & Design',
    shortName: 'Edit & Design',
    description: 'Adjust brightness, contrast, filters, blur, pixelate, borders, text stamps, and meme layouts.',
    iconName: 'Sliders',
    accentColor: 'from-blue-500/20 to-cyan-500/10 border-blue-500/30 text-blue-400',
  },
  {
    id: 'background-object',
    name: 'Background & Alpha',
    shortName: 'Background',
    description: 'Change background colors, add gradients, and inspect alpha transparency channels.',
    iconName: 'Layers',
    accentColor: 'from-indigo-500/20 to-purple-500/10 border-indigo-500/30 text-indigo-400',
  },
  {
    id: 'metadata-privacy',
    name: 'Metadata & Privacy',
    shortName: 'Privacy & EXIF',
    description: 'Inspect EXIF/GPS data, strip private device identifiers, fix orientation, and verify hashes.',
    iconName: 'ShieldCheck',
    accentColor: 'from-emerald-500/20 to-cyan-500/10 border-emerald-500/30 text-emerald-400',
  },
  {
    id: 'color-accessibility',
    name: 'Color & Accessibility',
    shortName: 'Color & A11y',
    description: 'Eyedropper picker, palette extractor, contrast calculator, color-blind simulator, and CSS generators.',
    iconName: 'Palette',
    accentColor: 'from-sky-500/20 to-teal-500/10 border-sky-500/30 text-sky-300',
  },
  {
    id: 'batch-workflows',
    name: 'Batch Workflows',
    shortName: 'Batch',
    description: 'Batch convert, resize, rename, watermark, clean metadata, and export multi-file ZIPs.',
    iconName: 'Boxes',
    accentColor: 'from-cyan-500/20 to-teal-500/10 border-cyan-500/30 text-cyan-300',
  },
  {
    id: 'developer-assets',
    name: 'Developer & Web Assets',
    shortName: 'Web & Dev',
    description: 'Base64 encoder, Data URIs, favicon/PWA pack, Open Graph generator, and responsive srcsets.',
    iconName: 'Code2',
    accentColor: 'from-blue-500/20 to-indigo-500/10 border-blue-500/30 text-blue-300',
  },
  {
    id: 'utilities',
    name: 'AquaTools Utilities',
    shortName: 'Utilities',
    description: 'Quality-vs-size lab, privacy inspector, e-commerce packs, social media frames, and budget checkers.',
    iconName: 'Sparkles',
    accentColor: 'from-teal-500/20 to-sky-500/10 border-teal-500/30 text-teal-400',
  },
];

export const IMAGE_TOOLS: ImageToolDefinition[] = [
  // ==========================================
  // 1. Convert
  // ==========================================
  {
    id: 'image-converter-universal',
    slug: 'convert-image',
    category: 'convert',
    title: 'Universal Image Converter',
    description: 'Convert between PNG, JPG, WebP, AVIF, SVG, BMP, and ICO formats instantly in your browser.',
    shortDescription: 'Multi-format image converter supporting PNG, JPG, WebP, AVIF, BMP, and ICO.',
    fullDescription: 'Fast, local image format conversion with custom quality, dimensions, background fill, and aspect ratio controls without uploading to servers.',
    iconName: 'RefreshCw',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/avif', 'image/svg+xml', 'image/bmp', 'image/gif'],
    outputTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/avif', 'image/bmp', 'image/x-icon'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Converted entirely inside browser memory via Canvas / OffscreenCanvas. 0 bytes uploaded.',
    knownLimitations: ['Animated GIF conversion produces high-resolution static frame or WebP.'],
    tags: ['convert', 'png', 'jpg', 'webp', 'avif', 'bmp', 'ico', 'format'],
    isPopular: true,
  },
  {
    id: 'jpg-to-png',
    slug: 'jpg-to-png',
    category: 'convert',
    title: 'JPG to PNG Converter',
    description: 'Convert JPEG and JPG photos into lossless PNG format with transparent canvas support.',
    shortDescription: 'Convert JPEG/JPG images to lossless PNG format.',
    fullDescription: 'Converts lossy JPEG files into clean, lossless PNG bitmaps ready for graphics editing and alpha-channel composition.',
    iconName: 'ArrowRightLeft',
    acceptedTypes: ['image/jpeg', 'image/jpg'],
    outputTypes: ['image/png'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Zero network transfer. Rendered client-side.',
    knownLimitations: [],
    tags: ['jpg', 'png', 'convert', 'lossless'],
    isPopular: true,
  },
  {
    id: 'png-to-jpg',
    slug: 'png-to-jpg',
    category: 'convert',
    title: 'PNG to JPG Converter',
    description: 'Convert PNG graphics and screenshots to lightweight JPG format with custom background color.',
    shortDescription: 'Convert PNG images to compressed JPEG with background color selection.',
    fullDescription: 'Converts PNG images with customizable background color filling for transparent areas and variable JPEG compression quality.',
    iconName: 'FileImage',
    acceptedTypes: ['image/png'],
    outputTypes: ['image/jpeg'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Processed purely in local device RAM.',
    knownLimitations: ['JPEG does not support alpha transparency; transparent pixels are filled with chosen background color.'],
    tags: ['png', 'jpg', 'convert', 'jpeg'],
    isPopular: true,
  },
  {
    id: 'convert-to-webp',
    slug: 'convert-to-webp',
    category: 'convert',
    title: 'Convert to WebP',
    description: 'Generate ultra-fast modern WebP images with 30-80% smaller file sizes than standard JPG.',
    shortDescription: 'Transform photos and graphics into modern, high-efficiency WebP files.',
    fullDescription: 'Converts images to Google WebP format with full alpha transparency support and high compression efficiency for web performance.',
    iconName: 'Zap',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/jpg', 'image/bmp', 'image/svg+xml'],
    outputTypes: ['image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'WebP encoding is performed natively by your browser engine.',
    knownLimitations: [],
    tags: ['webp', 'convert', 'web', 'fast', 'compress'],
    isPopular: true,
  },
  {
    id: 'convert-to-avif',
    slug: 'convert-to-avif',
    category: 'convert',
    title: 'Convert to AVIF',
    description: 'Convert images to next-generation AVIF format for unmatched quality-to-size ratios.',
    shortDescription: 'Next-gen AVIF encoding for bleeding-edge web optimization.',
    fullDescription: 'Transforms images into AV1 Image File Format (AVIF) with HDR color depth support and superior compression.',
    iconName: 'Sparkles',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/avif'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 40,
    privacyNote: 'Client-side encoding via browser canvas.',
    knownLimitations: ['Requires a browser with AVIF canvas export support (Chrome 94+, Firefox 113+, Safari 16.4+).'],
    tags: ['avif', 'convert', 'nextgen', 'hdr'],
  },
  {
    id: 'svg-to-raster',
    slug: 'svg-to-png',
    category: 'convert',
    title: 'SVG to PNG / JPG Rasterizer',
    description: 'Render vector SVG illustrations into high-resolution pixel graphics safely without executing scripts.',
    shortDescription: 'Safely rasterize vector SVG files into high-resolution PNG or JPG images.',
    fullDescription: 'Sanitizes SVG input to remove embedded JavaScript before rendering onto a 2D canvas at custom multiplier scales (1x, 2x, 4x, 8x).',
    iconName: 'Shapes',
    acceptedTypes: ['image/svg+xml'],
    outputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 20,
    privacyNote: 'SVG is sanitized to strip malicious scripts before rendering.',
    knownLimitations: ['External fonts or linked external assets in SVG must be embedded inline.'],
    tags: ['svg', 'rasterize', 'png', 'scale', 'vector'],
  },
  {
    id: 'ico-generator',
    slug: 'ico-generator',
    category: 'convert',
    title: 'Favicon ICO Maker',
    description: 'Create multi-resolution Windows .ICO files (16x16, 32x32, 48x48, 64x64, 128x128, 256x256).',
    shortDescription: 'Generate standard Microsoft .ICO favicon files from any square image.',
    fullDescription: 'Generates proper binary .ICO container files packed with standard bitmap directories for web favicons and desktop icons.',
    iconName: 'Bookmark',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml'],
    outputTypes: ['image/x-icon', 'image/png'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 20,
    privacyNote: 'Binary ICO container built directly in memory via ArrayBuffer.',
    knownLimitations: [],
    tags: ['ico', 'favicon', 'icon', 'windows', 'generator'],
  },

  // ==========================================
  // 2. Compress and Optimize
  // ==========================================
  {
    id: 'image-compressor',
    slug: 'compress-image',
    category: 'compress-optimize',
    title: 'Image Compressor',
    description: 'Reduce image file size with real-time before/after preview, quality slider, and byte savings readout.',
    shortDescription: 'Visual image compression with live before/after slider and file size estimates.',
    fullDescription: 'Interactive compression workbench allowing fine control over quality percentage, output format, downscaling, and instant visual artifact inspection.',
    iconName: 'Minimize2',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/avif'],
    outputTypes: ['image/jpeg', 'image/webp', 'image/png', 'image/avif'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Zero network requests. Compression runs on local GPU/CPU canvas.',
    knownLimitations: [],
    tags: ['compress', 'optimize', 'shrink', 'quality', 'slider'],
    isPopular: true,
  },
  {
    id: 'target-size-compressor',
    slug: 'compress-to-target-size',
    category: 'compress-optimize',
    title: 'Compress to Target File Size',
    description: 'Specify an exact target file size (e.g. Under 200 KB, Under 1 MB) and auto-optimize quality.',
    shortDescription: 'Auto-tune compression and resolution to hit a target file size limit.',
    fullDescription: 'Uses an intelligent binary-search iteration algorithm to find the optimal quality and dimension parameters that satisfy a strict byte budget.',
    iconName: 'Gauge',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/jpeg', 'image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 40,
    privacyNote: 'Multiple iteration passes occur entirely in client-side RAM.',
    knownLimitations: ['Extremely low target budgets may necessitate automatic downscaling.'],
    tags: ['target', 'size', 'kb', 'mb', 'budget', 'limit'],
    isPopular: true,
  },
  {
    id: 'lossless-optimizer',
    slug: 'lossless-optimizer',
    category: 'compress-optimize',
    title: 'Lossless Image Optimizer',
    description: 'Strip unnecessary metadata chunks, color profiles, and compress PNG/JPEG streams with 0% quality loss.',
    shortDescription: 'Lossless byte reduction preserving 100% pixel-perfect image fidelity.',
    fullDescription: 'Cleans auxiliary metadata, normalizes color chunks, and optimizes compression dictionaries without altering a single pixel value.',
    iconName: 'Shield',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Completely lossless local stream sanitization.',
    knownLimitations: [],
    tags: ['lossless', 'clean', 'perfect', 'metadata', 'shrink'],
  },
  {
    id: 'before-after-lab',
    slug: 'compare-images',
    category: 'compress-optimize',
    title: 'Visual Comparison Lab',
    description: 'Compare two images side-by-side or with an interactive split slider with zoom and pixel inspection.',
    shortDescription: 'Interactive split-slider and side-by-side image comparison tool.',
    fullDescription: 'Inspect compression artifacts, color shifts, and resolution changes between original and processed images with synchronized panning and zooming.',
    iconName: 'Eye',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/avif'],
    outputTypes: ['image/png'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Both images loaded only in local browser memory.',
    knownLimitations: [],
    tags: ['compare', 'slider', 'diff', 'inspection', 'zoom'],
  },

  // ==========================================
  // 3. Resize and Crop
  // ==========================================
  {
    id: 'image-resizer',
    slug: 'resize-image',
    category: 'resize-crop',
    title: 'Image Resizer',
    description: 'Resize images by exact pixels, percentage scale, or aspect ratio presets with bicubic interpolation.',
    shortDescription: 'Resize photos and graphics by dimensions, percentage, or presets.',
    fullDescription: 'High-quality resampling with aspect-ratio lock, custom fit modes (contain, cover, fill), and background color padding for fixed dimensions.',
    iconName: 'Maximize2',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/avif', 'image/bmp'],
    outputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Resampled locally using hardware-accelerated 2D canvas.',
    knownLimitations: [],
    tags: ['resize', 'scale', 'dimensions', 'width', 'height', 'percent'],
    isPopular: true,
  },
  {
    id: 'image-cropper',
    slug: 'crop-image',
    category: 'resize-crop',
    title: 'Crop & Aspect Ratio Tool',
    description: 'Interactive visual cropping with freeform handles and standard aspect ratios (1:1, 16:9, 4:3, 9:16).',
    shortDescription: 'Visual crop tool with standard social and photo aspect ratio presets.',
    fullDescription: 'Drag-and-drop crop bounding box with grid overlays, aspect ratio locks, pixel readout, and keyboard-accessible nudging.',
    iconName: 'Crop',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/avif', 'image/bmp'],
    outputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Cropped directly in memory. Original file never modified.',
    knownLimitations: [],
    tags: ['crop', 'aspect', 'square', '16:9', 'ratio', 'trim'],
    isPopular: true,
  },
  {
    id: 'rotate-flip-tool',
    slug: 'rotate-flip-image',
    category: 'resize-crop',
    title: 'Rotate, Flip & Straighten',
    description: 'Rotate 90°, 180°, 270°, flip horizontally or vertically, and fine-tune straightening angles.',
    shortDescription: 'Rotate in 90° increments, flip mirrors, or straighten horizon lines.',
    fullDescription: 'Transforms image orientation with automatic canvas dimension readjustment, lossless 90° rotation, and sub-degree angle straightening.',
    iconName: 'RotateCw',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/avif', 'image/bmp'],
    outputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Local canvas coordinate transformation.',
    knownLimitations: [],
    tags: ['rotate', 'flip', 'mirror', 'straighten', 'orientation'],
  },
  {
    id: 'canvas-padding-tool',
    slug: 'expand-canvas-pad',
    category: 'resize-crop',
    title: 'Expand Canvas & Add Padding',
    description: 'Add borders, margins, or transparent padding around any image to fit specific square or banner dimensions.',
    shortDescription: 'Add custom background padding or expand canvas size.',
    fullDescription: 'Centers the source image onto a larger target canvas with customizable background color (white, black, custom hex, or transparent).',
    iconName: 'Square',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Rendered in local canvas.',
    knownLimitations: [],
    tags: ['padding', 'margin', 'expand', 'border', 'canvas'],
  },

  // ==========================================
  // 4. Edit and Design
  // ==========================================
  {
    id: 'image-filter-studio',
    slug: 'image-filters-adjustments',
    category: 'edit-design',
    title: 'Filters & Color Adjustments',
    description: 'Fine-tune brightness, contrast, saturation, temperature, tint, sepia, grayscale, invert, and duotone.',
    shortDescription: 'Photo filter workbench with brightness, contrast, saturation, and tone controls.',
    fullDescription: 'Pixel-level color transformations with instant live preview, preset photographic filters, and fine numeric sliders.',
    iconName: 'Sliders',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/avif'],
    outputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 40,
    privacyNote: 'Shader/Canvas pixel filter processing runs on local GPU/CPU.',
    knownLimitations: [],
    tags: ['filter', 'brightness', 'contrast', 'saturation', 'grayscale', 'sepia'],
    isPopular: true,
  },
  {
    id: 'blur-pixelate-redact',
    slug: 'blur-pixelate-redact',
    category: 'edit-design',
    title: 'Blur, Pixelate & Redact',
    description: 'Anonymize sensitive text, faces, license plates, or credit card numbers with gaussian blur or pixelation boxes.',
    shortDescription: 'Redact sensitive areas with customizable blur or mosaic pixelation.',
    fullDescription: 'Draw bounding boxes over sensitive regions to permanently burn gaussian blur or pixel mosaic blocks into the bitmap pixels.',
    iconName: 'EyeOff',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 40,
    privacyNote: 'Redactions are rasterized directly into the pixel buffer, making them non-reversible.',
    knownLimitations: [],
    tags: ['redact', 'blur', 'pixelate', 'privacy', 'censor', 'anonymous'],
    isPopular: true,
  },
  {
    id: 'watermark-overlay-tool',
    slug: 'watermark-image',
    category: 'edit-design',
    title: 'Watermark & Text Overlay',
    description: 'Stamp customized text or logo watermarks with opacity, rotation, tiled patterns, and positioning.',
    shortDescription: 'Add text or logo watermarks with custom opacity and positioning.',
    fullDescription: 'Protect photos and documents by overlaying diagonal tiled or corner-positioned text, copyright notices, or logo stamps.',
    iconName: 'Stamp',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 40,
    privacyNote: 'Watermark rasterized onto canvas client-side.',
    knownLimitations: [],
    tags: ['watermark', 'text', 'logo', 'copyright', 'stamp'],
    isPopular: true,
  },
  {
    id: 'rounded-corners-border',
    slug: 'rounded-corners-border',
    category: 'edit-design',
    title: 'Rounded Corners & Shadows',
    description: 'Add smooth rounded corners, decorative borders, and soft drop shadows for modern mockups.',
    shortDescription: 'Add rounded corner radius, colored borders, and drop shadows.',
    fullDescription: 'Generates polished presentation graphics with custom corner radius (px or %), outer borders, and customizable shadow blur.',
    iconName: 'SquareCode',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/png', 'image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 40,
    privacyNote: 'Canvas clipping path rendered locally.',
    knownLimitations: ['Requires PNG or WebP output to preserve alpha transparency on rounded corners.'],
    tags: ['rounded', 'corners', 'border', 'shadow', 'radius'],
  },
  {
    id: 'meme-generator',
    slug: 'meme-generator',
    category: 'edit-design',
    title: 'Meme Generator & Text Styler',
    description: 'Create classic and modern memes with bold impact text, outline strokes, and customizable positioning.',
    shortDescription: 'Add top and bottom meme text with heavy black outlines.',
    fullDescription: 'Classic Impact font meme maker with uppercase automatic formatting, outline stroke width adjustments, and instant download.',
    iconName: 'Smile',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/png', 'image/jpeg'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 30,
    privacyNote: 'Text composited client-side on canvas.',
    knownLimitations: [],
    tags: ['meme', 'impact', 'text', 'funny', 'generator'],
  },

  // ==========================================
  // 5. Background and Object
  // ==========================================
  {
    id: 'background-color-changer',
    slug: 'change-background-color',
    category: 'background-object',
    title: 'Background Color & Gradients',
    description: 'Replace transparent image backgrounds with solid studio colors, smooth linear gradients, or soft water hues.',
    shortDescription: 'Add solid color or gradient backgrounds to transparent PNGs.',
    fullDescription: 'Fills transparent alpha areas with clean studio colors (white, black, navy) or custom multi-stop gradients.',
    iconName: 'PaintBucket',
    acceptedTypes: ['image/png', 'image/webp', 'image/svg+xml'],
    outputTypes: ['image/png', 'image/jpeg', 'image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 40,
    privacyNote: 'Local canvas fill operation.',
    knownLimitations: [],
    tags: ['background', 'color', 'gradient', 'transparent', 'fill'],
  },
  {
    id: 'transparent-channel-inspector',
    slug: 'transparent-channel-inspector',
    category: 'background-object',
    title: 'Alpha Channel & Transparency Inspector',
    description: 'Inspect alpha transparency channels, identify semi-transparent halos, and verify alpha masks.',
    shortDescription: 'Analyze alpha channel transparency and edge quality.',
    fullDescription: 'Toggles between high-contrast dark, light, magenta, and checkered test backdrops to inspect pixel transparency.',
    iconName: 'Grid',
    acceptedTypes: ['image/png', 'image/webp', 'image/svg+xml'],
    outputTypes: ['image/png'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 40,
    privacyNote: 'Visual inspection performed in local browser memory.',
    knownLimitations: [],
    tags: ['transparency', 'alpha', 'mask', 'checkerboard', 'inspect'],
  },

  // ==========================================
  // 6. Metadata and Privacy
  // ==========================================
  {
    id: 'exif-metadata-viewer',
    slug: 'view-exif-metadata',
    category: 'metadata-privacy',
    title: 'EXIF & GPS Metadata Viewer',
    description: 'Inspect camera model, GPS coordinates, date taken, exposure settings, software, and lens details.',
    shortDescription: 'Comprehensive EXIF, GPS location, and camera metadata viewer.',
    fullDescription: 'Parses binary EXIF, TIFF, and IPTC headers client-side to display complete camera settings, shutter speeds, ISO, and map coordinates.',
    iconName: 'FileSearch',
    acceptedTypes: ['image/jpeg', 'image/jpg', 'image/tiff', 'image/png'],
    outputTypes: ['interactive', 'text'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'EXIF bytes are decoded locally. No telemetry or location queries are sent.',
    knownLimitations: [],
    tags: ['exif', 'metadata', 'gps', 'camera', 'iso', 'shutter', 'location'],
    isPopular: true,
  },
  {
    id: 'exif-metadata-remover',
    slug: 'remove-exif-metadata',
    category: 'metadata-privacy',
    title: 'EXIF & Metadata Stripper',
    description: 'Completely remove GPS location, camera serial numbers, author tags, and date timestamps before sharing.',
    shortDescription: 'Strip all EXIF, GPS, and device metadata for complete privacy.',
    fullDescription: 'Re-encodes image raster buffers to produce clean, sanitized output files containing 0% trace metadata or device identifiers.',
    iconName: 'ShieldAlert',
    acceptedTypes: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
    outputTypes: ['image/jpeg', 'image/png', 'image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Guaranteed 100% metadata scrub. Sanitized file contains purely raw image pixels.',
    knownLimitations: [],
    tags: ['exif', 'strip', 'clean', 'privacy', 'gps', 'remove', 'scrub'],
    isPopular: true,
  },
  {
    id: 'privacy-risk-scanner',
    slug: 'privacy-risk-scanner',
    category: 'metadata-privacy',
    title: 'Photo Privacy Risk Scanner',
    description: 'Scan photos for hidden location tags, camera serial numbers, author names, and embedded thumbnails.',
    shortDescription: 'Audit photos for privacy risks and sensitive embedded information.',
    fullDescription: 'Audits image headers for privacy risks like GPS coordinates, camera serial numbers, unique owner tags, and hidden preview thumbnails.',
    iconName: 'AlertTriangle',
    acceptedTypes: ['image/jpeg', 'image/jpg', 'image/png', 'image/tiff'],
    outputTypes: ['interactive'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Audit executed locally in your browser.',
    knownLimitations: [],
    tags: ['privacy', 'audit', 'scanner', 'risk', 'gps', 'security'],
  },
  {
    id: 'orientation-fixer',
    slug: 'fix-photo-orientation',
    category: 'metadata-privacy',
    title: 'EXIF Orientation Fixer',
    description: 'Correct rotated or upside-down smartphone photos by baking the EXIF orientation tag into pixel geometry.',
    shortDescription: 'Bake EXIF rotation tags directly into pixels so photos open correctly everywhere.',
    fullDescription: 'Reads the EXIF orientation flag (1 through 8), rotates the bitmap pixels physically, and resets the tag to 1 for universal compatibility.',
    iconName: 'RotateCcw',
    acceptedTypes: ['image/jpeg', 'image/jpg'],
    outputTypes: ['image/jpeg', 'image/png'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Local orientation correction.',
    knownLimitations: [],
    tags: ['orientation', 'exif', 'rotate', 'fix', 'phone', 'camera'],
  },

  // ==========================================
  // 7. Color and Accessibility
  // ==========================================
  {
    id: 'color-picker-eyedropper',
    slug: 'image-color-picker',
    category: 'color-accessibility',
    title: 'Image Eyedropper & Color Sampler',
    description: 'Pick exact pixel colors from any image with a zoom loupe, HEX/RGB/HSL conversion, and one-click copy.',
    shortDescription: 'Sample exact pixel colors from any image with a precision zoom loupe.',
    fullDescription: 'Interactive canvas eyedropper with magnifying loupe, instant HEX, RGB, HSL, and CMYK readouts, and clipboard export.',
    iconName: 'Pipette',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml', 'image/bmp'],
    outputTypes: ['interactive', 'text'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Pixel color sampling occurs locally in canvas buffer.',
    knownLimitations: [],
    tags: ['color', 'picker', 'eyedropper', 'hex', 'rgb', 'hsl', 'sample'],
    isPopular: true,
  },
  {
    id: 'palette-extractor',
    slug: 'extract-color-palette',
    category: 'color-accessibility',
    title: 'Color Palette Extractor',
    description: 'Extract dominant color palettes, harmonic swatches, and CSS color variables from any photo.',
    shortDescription: 'Extract harmonious color palettes and CSS swatch variables.',
    fullDescription: 'Quantizes image color frequencies to extract dominant, vibrant, muted, light, and dark swatch sets with downloadable CSS/JSON palettes.',
    iconName: 'Palette',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/avif'],
    outputTypes: ['interactive', 'json', 'css'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 40,
    privacyNote: 'Color quantization executed on local worker/canvas.',
    knownLimitations: [],
    tags: ['palette', 'dominant', 'swatch', 'css', 'colors', 'quantize'],
    isPopular: true,
  },
  {
    id: 'color-blind-preview',
    slug: 'color-blind-preview',
    category: 'color-accessibility',
    title: 'Color Blindness Simulator',
    description: 'Test image accessibility under Protanopia, Deuteranopia, Tritanopia, and Achromatopsia color filters.',
    shortDescription: 'Simulate how images appear to people with different color vision deficiencies.',
    fullDescription: 'Applies scientifically calibrated Daltonization color matrices to simulate various types of color vision deficiency for WCAG accessibility testing.',
    iconName: 'Eye',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml'],
    outputTypes: ['image/png', 'interactive'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 40,
    privacyNote: 'Matrix transformation computed locally.',
    knownLimitations: [],
    tags: ['colorblind', 'accessibility', 'a11y', 'wcag', 'protanopia', 'deuteranopia'],
  },
  {
    id: 'contrast-checker-tool',
    slug: 'image-contrast-checker',
    category: 'color-accessibility',
    title: 'Color Contrast Analyzer (WCAG)',
    description: 'Calculate WCAG AA/AAA contrast ratios between sampled image colors and background text.',
    shortDescription: 'Check color contrast ratios against WCAG AA and AAA accessibility standards.',
    fullDescription: 'Computes relative luminance ratios between foreground and background colors with instant pass/fail ratings for normal text, large text, and UI components.',
    iconName: 'CheckCircle2',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['interactive'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 30,
    privacyNote: 'Mathematical contrast formula evaluated locally.',
    knownLimitations: [],
    tags: ['contrast', 'wcag', 'aa', 'aaa', 'accessibility', 'ratio'],
  },

  // ==========================================
  // 9. Batch Workflows
  // ==========================================
  {
    id: 'batch-image-converter',
    slug: 'batch-convert-images',
    category: 'batch-workflows',
    title: 'Batch Image Converter & ZIP',
    description: 'Convert dozens of images simultaneously to WebP, PNG, JPG, or AVIF and download as a single ZIP archive.',
    shortDescription: 'Convert multiple images in batch with unified format and download as ZIP.',
    fullDescription: 'High-throughput client-side batch conversion engine with concurrent processing limits, individual progress tracking, and packaged ZIP export.',
    iconName: 'Boxes',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/bmp', 'image/avif', 'image/svg+xml'],
    outputTypes: ['zip', 'image/webp', 'image/png', 'image/jpeg'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 100,
    privacyNote: 'Batch queue and ZIP creation run entirely in browser memory.',
    knownLimitations: ['Processing 50+ massive images at once may take a few seconds depending on device memory.'],
    tags: ['batch', 'multi', 'convert', 'zip', 'bulk', 'archive'],
    isPopular: true,
  },
  {
    id: 'batch-resizer-tool',
    slug: 'batch-resize-images',
    category: 'batch-workflows',
    title: 'Batch Image Resizer',
    description: 'Resize an entire folder of photos to uniform dimensions, percentage scales, or maximum bounding boxes.',
    shortDescription: 'Resize multiple photos at once with unified dimensions or scaling rules.',
    fullDescription: 'Batch resizes multiple photos with flexible constraints (e.g. Max Width 1200px, Scale to 50%) and provides one-click batch ZIP download.',
    iconName: 'Maximize',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['zip', 'image/png', 'image/jpeg'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 100,
    privacyNote: 'Processed locally in browser memory.',
    knownLimitations: [],
    tags: ['batch', 'resize', 'scale', 'bulk', 'zip'],
  },
  {
    id: 'batch-watermarker-tool',
    slug: 'batch-watermark-images',
    category: 'batch-workflows',
    title: 'Batch Watermark Stamper',
    description: 'Apply copyright text, signatures, or logo watermarks to multiple photos at once in a single batch.',
    shortDescription: 'Stamp watermarks across multiple images simultaneously.',
    fullDescription: 'Stamps uniform watermark text or branding logos across multiple photos with position alignment, opacity, and batch ZIP export.',
    iconName: 'Stamp',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['zip', 'image/jpeg', 'image/png'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 100,
    privacyNote: 'Watermarking runs entirely on client device.',
    knownLimitations: [],
    tags: ['batch', 'watermark', 'copyright', 'stamp', 'multi'],
  },

  // ==========================================
  // 10. Developer and Web Assets
  // ==========================================
  {
    id: 'base64-image-encoder',
    slug: 'image-to-base64',
    category: 'developer-assets',
    title: 'Image to Base64 & Data URI',
    description: 'Convert images into Base64 strings, HTML <img> tags, CSS background-image code, and Data URIs.',
    shortDescription: 'Convert images to Base64 strings, CSS code, and Data URIs.',
    fullDescription: 'Instantly encodes images into Data URIs with one-click copying for raw Base64, HTML embed code, CSS url() syntax, and JSON payloads.',
    iconName: 'Code',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml', 'image/gif', 'image/x-icon'],
    outputTypes: ['text', 'css', 'html'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 20,
    privacyNote: 'Base64 string generated in local memory.',
    knownLimitations: ['Base64 increases binary size by ~33%; best suited for small icons and inline web assets.'],
    tags: ['base64', 'data-uri', 'css', 'html', 'developer', 'inline'],
    isPopular: true,
  },
  {
    id: 'favicon-pwa-pack',
    slug: 'favicon-pwa-icon-pack',
    category: 'developer-assets',
    title: 'Favicon & PWA Icon Pack Generator',
    description: 'Generate all standard favicon and PWA icon sizes (16x16, 32x32, 180x180, 192x192, 512x512) + manifest.json.',
    shortDescription: 'Generate a complete favicon package and Web App Manifest icons.',
    fullDescription: 'Creates an all-in-one ZIP containing favicon.ico, apple-touch-icon.png, Android Chrome 192/512 icons, and a ready-to-use manifest.json snippet.',
    iconName: 'Package',
    acceptedTypes: ['image/png', 'image/svg+xml', 'image/jpeg'],
    outputTypes: ['zip'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 25,
    privacyNote: 'Icon resizing and ZIP packing occur locally.',
    knownLimitations: ['Square source images produce the cleanest icons without automatic padding.'],
    tags: ['favicon', 'pwa', 'manifest', 'icons', 'web', 'apple-touch-icon'],
    isPopular: true,
  },
  {
    id: 'opengraph-banner-maker',
    slug: 'opengraph-image-maker',
    category: 'developer-assets',
    title: 'Open Graph (OG) Image Maker',
    description: 'Generate standard 1200x630 social share preview cards for Twitter, Facebook, LinkedIn, and Discord.',
    shortDescription: 'Create standard 1200×630 social preview banners for Twitter and LinkedIn.',
    fullDescription: 'Generates perfectly sized 1200×630 px Open Graph banners with customizable titles, water-glass badge cards, gradients, and logo overlays.',
    iconName: 'Share2',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/png', 'image/jpeg'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 30,
    privacyNote: 'Rendered locally on 1200×630 canvas.',
    knownLimitations: [],
    tags: ['opengraph', 'og', 'twitter', 'social', 'banner', '1200x630'],
  },
  {
    id: 'responsive-srcset-generator',
    slug: 'responsive-srcset-generator',
    category: 'developer-assets',
    title: 'Responsive Srcset & HTML Picture Generator',
    description: 'Export multiple responsive image widths (320w, 640w, 1024w, 1920w) and copy the <picture> HTML code.',
    shortDescription: 'Generate multi-resolution srcset images and copy responsive HTML code.',
    fullDescription: 'Resizes images into standard responsive screen breakpoints and generates copy-ready HTML <picture> and <img srcset> tags with WebP/AVIF fallbacks.',
    iconName: 'Layout',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['zip', 'html'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 40,
    privacyNote: 'Responsive images and HTML snippets created client-side.',
    knownLimitations: [],
    tags: ['srcset', 'responsive', 'picture', 'html', 'breakpoints', 'developer'],
  },

  // ==========================================
  // 11. AquaTools Utilities
  // ==========================================
  {
    id: 'quality-vs-size-lab',
    slug: 'quality-vs-size-lab',
    category: 'utilities',
    title: 'Quality-vs-Size Optimization Lab',
    description: 'Test WebP vs JPG vs AVIF across multiple quality levels simultaneously to find the sweet spot.',
    shortDescription: 'Side-by-side multi-format matrix comparing file sizes and visual quality.',
    fullDescription: 'Encodes an image across multiple formats and quality percentages at once, plotting a visual compression comparison table.',
    iconName: 'BarChart2',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['interactive', 'image/webp'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 30,
    privacyNote: 'All format variations encoded in local browser RAM.',
    knownLimitations: [],
    tags: ['quality', 'size', 'matrix', 'comparison', 'lab', 'optimization'],
    isPopular: true,
  },
  {
    id: 'social-media-resizer-pack',
    slug: 'social-media-pack',
    category: 'utilities',
    title: 'Social Media Image Pack',
    description: 'Crop and resize one photo into Instagram, YouTube, X/Twitter, LinkedIn, and TikTok sizes in one click.',
    shortDescription: 'One-click export for Instagram, YouTube, LinkedIn, X, and TikTok.',
    fullDescription: 'Automatically generates square (1:1), story (9:16), landscape banner (16:9), and avatar formats from a single source image.',
    iconName: 'Share',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['zip'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 40,
    privacyNote: 'Batch social resizing processed locally.',
    knownLimitations: [],
    tags: ['social', 'instagram', 'youtube', 'tiktok', 'twitter', 'linkedin', 'presets'],
    isPopular: true,
  },
  {
    id: 'screenshot-beautifier',
    slug: 'screenshot-beautifier',
    category: 'utilities',
    title: 'Screenshot Beautifier & Mockup Frame',
    description: 'Frame raw screenshots on a gorgeous water-glass or twilight backdrop with soft drop shadows and padding.',
    shortDescription: 'Wrap raw screenshots in elegant backgrounds with soft shadows and padding.',
    fullDescription: 'Transforms basic screenshots into marketing-ready presentation mockups with water glass gradients, rounded corners, and soft lighting shadows.',
    iconName: 'Monitor',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp'],
    outputTypes: ['image/png'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 40,
    privacyNote: 'Composited on 2D canvas client-side.',
    knownLimitations: [],
    tags: ['screenshot', 'beautify', 'mockup', 'frame', 'gradient', 'shadow'],
    isPopular: true,
  },
  {
    id: 'file-size-budget-tool',
    slug: 'file-size-budget-tool',
    category: 'utilities',
    title: 'Image File-Size Budget Tester',
    description: 'Simulate mobile network load times (3G, 4G, 5G) and test against performance budgets (e.g., < 150 KB).',
    shortDescription: 'Test web images against byte budgets and simulate 3G/4G/5G load speeds.',
    fullDescription: 'Evaluates whether an image meets Core Web Vitals and performance budgets, estimating latency and time-to-first-render across network tiers.',
    iconName: 'Activity',
    acceptedTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/avif', 'image/svg+xml'],
    outputTypes: ['interactive'],
    runsLocally: true,
    status: 'ready',
    maxRecommendedSize: 50,
    privacyNote: 'Performance calculations run locally without network pings.',
    knownLimitations: [],
    tags: ['budget', 'cwv', 'performance', 'latency', '3g', '4g', 'speed'],
  },
];

export function getImageToolBySlug(slug: string): ImageToolDefinition | undefined {
  if (!slug) return undefined;
  const cleanSlug = slug.toLowerCase().trim();
  return IMAGE_TOOLS.find(
    (t) => t.slug.toLowerCase() === cleanSlug || t.id.toLowerCase() === cleanSlug
  );
}

export function getImageToolsByCategory(category: ImageToolCategory | 'all'): ImageToolDefinition[] {
  if (category === 'all') return IMAGE_TOOLS;
  return IMAGE_TOOLS.filter((t) => t.category === category);
}
