import { PdfCategoryMeta, PdfToolCategory, PdfToolDefinition } from '../types/pdf';

export const PDF_CATEGORIES: PdfCategoryMeta[] = [
  {
    id: 'create',
    name: 'Create PDF',
    shortName: 'Create',
    description: 'Generate blank PDFs, photo scans, invoices, and structured forms locally.',
    iconName: 'PlusCircle',
    accentColor: 'from-cyan-500/20 to-blue-500/10 border-cyan-500/30 text-cyan-400',
  },
  {
    id: 'edit',
    name: 'Edit PDF',
    shortName: 'Edit',
    description: 'Add watermarks, page numbers, annotations, crop margins, and document info.',
    iconName: 'Edit3',
    accentColor: 'from-sky-500/20 to-teal-500/10 border-sky-500/30 text-sky-400',
  },
  {
    id: 'organize',
    name: 'Organize PDF',
    shortName: 'Organize',
    description: 'Merge, split, rotate, rearrange, extract, and remove pages seamlessly.',
    iconName: 'Layers',
    accentColor: 'from-blue-500/20 to-indigo-500/10 border-blue-500/30 text-blue-400',
  },
  {
    id: 'optimize-repair',
    name: 'Optimize & Repair',
    shortName: 'Optimize',
    description: 'Compress file sizes, flatten forms, convert to PDF/A, and clean streams.',
    iconName: 'Zap',
    accentColor: 'from-teal-500/20 to-emerald-500/10 border-teal-500/30 text-teal-400',
  },
  {
    id: 'security-privacy',
    name: 'Security & Privacy',
    shortName: 'Security',
    description: 'Password protection, user decryption, metadata stripping, and visual signatures.',
    iconName: 'ShieldCheck',
    accentColor: 'from-emerald-500/20 to-cyan-500/10 border-emerald-500/30 text-emerald-400',
  },
  {
    id: 'view-compare',
    name: 'View & Compare',
    shortName: 'View',
    description: 'Side-by-side visual diffs, secure browser viewer, and page metrics inspection.',
    iconName: 'Eye',
    accentColor: 'from-indigo-500/20 to-purple-500/10 border-indigo-500/30 text-indigo-400',
  },
  {
    id: 'convert-to-pdf',
    name: 'Convert to PDF',
    shortName: 'To PDF',
    description: 'Transform images, markdown, text, HTML, and documents into standard PDF.',
    iconName: 'ArrowRightCircle',
    accentColor: 'from-cyan-500/20 to-sky-500/10 border-cyan-500/30 text-cyan-300',
  },
  {
    id: 'convert-from-pdf',
    name: 'Convert from PDF',
    shortName: 'From PDF',
    description: 'Extract high-resolution images, plain text, SVG, and HTML from PDF documents.',
    iconName: 'FileDown',
    accentColor: 'from-sky-500/20 to-blue-500/10 border-sky-500/30 text-sky-300',
  },
  {
    id: 'image-conversion',
    name: 'Image Conversion',
    shortName: 'Images',
    description: 'Batch convert and optimize raster images specifically for PDF workflows.',
    iconName: 'Image',
    accentColor: 'from-teal-500/20 to-cyan-500/10 border-teal-500/30 text-teal-300',
  },
];

export const PDF_TOOLS: PdfToolDefinition[] = [
  // ==========================================
  // 1. Create PDF
  // ==========================================
  {
    id: 'create-pdf',
    slug: 'create-pdf',
    category: 'create',
    title: 'Create Blank PDF',
    shortDescription: 'Build new customized PDF documents with defined dimensions and grid lines.',
    fullDescription: 'Generate fresh blank or ruled PDF canvases with custom page counts, standard sizes (A4, Letter, A3), orientation, and margin setups.',
    iconName: 'FilePlus',
    supportedInputTypes: ['Form settings'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 10,
    requiredCapability: 'pdf-lib standard creation',
    privacyNote: 'Constructed directly in memory using pdf-lib. Zero network transmission.',
    tags: ['create', 'new', 'blank', 'page', 'builder'],
    implementationStatus: 'implemented',
  },
  {
    id: 'camera-to-pdf',
    slug: 'camera-to-pdf',
    category: 'create',
    title: 'Camera to PDF Scan',
    shortDescription: 'Capture documents with your device webcam or phone camera directly into a PDF.',
    fullDescription: 'Uses the browser MediaDevices Web API to capture multi-page document scans with contrast enhancement and compile to PDF.',
    iconName: 'Camera',
    supportedInputTypes: ['Webcam Stream', 'Photo Snap'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 25,
    requiredCapability: 'HTML5 MediaDevices & Canvas2D',
    privacyNote: 'Camera feed stays in browser memory. Video frames never leave your local session.',
    tags: ['camera', 'scan', 'webcam', 'capture', 'photo'],
    implementationStatus: 'implemented',
  },
  {
    id: 'webpage-to-pdf',
    slug: 'webpage-to-pdf',
    category: 'create',
    title: 'Webpage to PDF',
    shortDescription: 'Convert public HTML code and rendered pages into clean vector PDF.',
    fullDescription: 'Renders sanitized HTML/CSS into paginated vector PDF documents directly in client canvas.',
    iconName: 'Globe',
    supportedInputTypes: ['HTML', 'URL Text'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 15,
    requiredCapability: 'DOMParser & Canvas sandbox',
    privacyNote: 'HTML parsed inside isolated sandboxed container without script execution.',
    tags: ['webpage', 'html', 'url', 'site', 'export'],
    implementationStatus: 'implemented',
  },
  {
    id: 'images-to-pdf',
    slug: 'images-to-pdf',
    category: 'create',
    title: 'Images to PDF',
    shortDescription: 'Combine JPG, PNG, and WebP images into a single polished multi-page PDF.',
    fullDescription: 'Batch convert image files into a single unified PDF with auto-orientation, standard paper dimensions, and configurable margin padding.',
    iconName: 'Images',
    supportedInputTypes: ['PNG', 'JPG', 'JPEG', 'WebP', 'GIF', 'BMP'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib & Canvas2D raster embedder',
    privacyNote: 'Raw image bytes are embedded directly in memory. Zero remote storage.',
    tags: ['images', 'photos', 'compile', 'jpg to pdf', 'png to pdf'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'create-fillable-pdf-form',
    slug: 'create-fillable-pdf-form',
    category: 'create',
    title: 'Create Fillable PDF Form',
    shortDescription: 'Add interactive text inputs, checkboxes, and radio buttons to PDF documents.',
    fullDescription: 'Design PDF forms with interactive AcroForm fields that can be filled in Adobe Reader, browser viewers, and mobile devices.',
    iconName: 'CheckSquare',
    supportedInputTypes: ['PDF', 'Form Spec'],
    supportedOutputTypes: ['Interactive PDF Form'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'pdf-lib AcroForm API',
    privacyNote: 'Form structure compiled purely on client side.',
    tags: ['form', 'fillable', 'acroform', 'inputs', 'checkbox'],
    implementationStatus: 'implemented',
  },
  {
    id: 'create-job-application-pdf',
    slug: 'create-job-application-pdf',
    category: 'create',
    title: 'Job Application PDF Builder',
    shortDescription: 'Generate standard job application and cover letter PDF templates.',
    fullDescription: 'Interactive resume and application letter builder that generates crisp vector typography PDFs without external cloud tools.',
    iconName: 'Briefcase',
    supportedInputTypes: ['Form Data'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 10,
    requiredCapability: 'pdf-lib vector typesetting',
    privacyNote: 'Applicant personal details and resume data remain strictly on your device.',
    tags: ['resume', 'cv', 'job', 'application', 'letter'],
    implementationStatus: 'implemented',
  },
  {
    id: 'create-invoice-pdf',
    slug: 'create-invoice-pdf',
    category: 'create',
    title: 'Create Invoice PDF',
    shortDescription: 'Generate professional business invoices with automatic line item calculation.',
    fullDescription: 'Client-side invoice creator with currency selection, automatic tax calculations, line item tables, and custom company branding.',
    iconName: 'Receipt',
    supportedInputTypes: ['Invoice Data'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 10,
    requiredCapability: 'pdf-lib vector generator',
    privacyNote: 'Financial and client invoice records are never recorded or transmitted.',
    tags: ['invoice', 'bill', 'receipt', 'business', 'tax'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'visual-invoice-pdf',
    slug: 'visual-invoice-pdf',
    category: 'create',
    title: 'Visual Invoice Designer',
    shortDescription: 'Visual drag-and-drop template designer for modern business invoices.',
    fullDescription: 'Customizable visual invoice layout with color themes, logo upload, and live preview rendering.',
    iconName: 'FileSpreadsheet',
    supportedInputTypes: ['Visual Form'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 10,
    requiredCapability: 'pdf-lib & Canvas typography',
    privacyNote: 'All company assets and pricing figures are processed locally.',
    tags: ['invoice', 'visual', 'designer', 'template', 'pdf'],
    implementationStatus: 'implemented',
  },
  {
    id: 'electronic-invoice',
    slug: 'electronic-invoice',
    category: 'create',
    title: 'Electronic Invoice (ZUGFeRD / Factur-X Preview)',
    shortDescription: 'Attach standardized XML e-invoice data records to PDF documents.',
    fullDescription: 'Embeds structured electronic invoice XML into PDF/A-3 document containers adhering to modern European e-invoicing standards.',
    iconName: 'FileCheck',
    supportedInputTypes: ['PDF', 'XML'],
    supportedOutputTypes: ['Hybrid PDF/A-3'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 20,
    requiredCapability: 'pdf-lib attachment catalog',
    privacyNote: 'XML invoices are bundled strictly within local browser memory.',
    tags: ['zugferd', 'factur-x', 'e-invoice', 'xml', 'pdfa'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'generate-qr-code',
    slug: 'generate-qr-code',
    category: 'create',
    title: 'QR Code PDF Generator',
    shortDescription: 'Generate high-resolution printable vector QR codes and embed them in PDF.',
    fullDescription: 'Build printable QR codes for URLs, WiFi credentials, vCards, or text with configurable error correction and export to PDF.',
    iconName: 'QrCode',
    supportedInputTypes: ['Text', 'URL', 'vCard'],
    supportedOutputTypes: ['PDF', 'PNG'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 5,
    requiredCapability: 'qrcode generator & pdf-lib',
    privacyNote: 'QR payload generation occurs using local mathematical matrix algorithms.',
    tags: ['qr', 'qrcode', 'barcode', 'printable', 'pdf'],
    implementationStatus: 'implemented',
  },

  // ==========================================
  // 2. Edit PDF
  // ==========================================
  {
    id: 'edit-pdf',
    slug: 'edit-pdf',
    category: 'edit',
    title: 'Edit PDF Content',
    shortDescription: 'Add text blocks, shapes, highlights, and drawings onto PDF pages.',
    fullDescription: 'Direct browser canvas overlay editor for inserting custom text notes, rectangles, callouts, and freehand markup onto PDF sheets.',
    iconName: 'Edit',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'pdf-lib & Canvas layer editor',
    privacyNote: 'Document content is edited entirely within the active browser tab.',
    tags: ['edit', 'text', 'draw', 'markup', 'shapes'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'annotate-pdf',
    slug: 'annotate-pdf',
    category: 'edit',
    title: 'Annotate PDF',
    shortDescription: 'Highlight key passages, underline text, and leave comments on PDF pages.',
    fullDescription: 'Interactive annotation tool for reviewing documents, striking through text, and placing sticky callouts on specific pages.',
    iconName: 'Highlighter',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Annotated PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'Canvas annotation overlay',
    privacyNote: 'Annotations are baked locally into the exported PDF stream.',
    tags: ['annotate', 'highlight', 'comment', 'review', 'markup'],
    implementationStatus: 'implemented',
  },
  {
    id: 'fill-pdf-form',
    slug: 'fill-pdf-form',
    category: 'edit',
    title: 'Fill PDF Form',
    shortDescription: 'Fill out existing interactive PDF form fields and export filled documents.',
    fullDescription: 'Read and update existing PDF AcroForm text fields, checkboxes, dropdowns, and radio buttons with auto-detection.',
    iconName: 'FileEdit',
    supportedInputTypes: ['PDF with AcroForms'],
    supportedOutputTypes: ['Filled PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'pdf-lib getForm API',
    privacyNote: 'Confidential form answers are never uploaded to any remote server.',
    tags: ['form', 'fill', 'acroform', 'inputs', 'pdf'],
    implementationStatus: 'implemented',
  },
  {
    id: 'add-watermark',
    slug: 'add-watermark',
    category: 'edit',
    title: 'Add Watermark to PDF',
    shortDescription: 'Stamp customizable text watermarks across all or selected PDF pages.',
    fullDescription: 'Configure watermark text, rotation angle, opacity, font size, color, and page positioning (center, corners) with instant visual feedback.',
    iconName: 'Stamp',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Watermarked PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib vector drawing',
    privacyNote: 'Watermarking is applied vector-by-vector in browser memory.',
    tags: ['watermark', 'stamp', 'confidential', 'draft', 'overlay'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'add-page-numbers',
    slug: 'add-page-numbers',
    category: 'edit',
    title: 'Add Page Numbers to PDF',
    shortDescription: 'Insert dynamic page numbers ("Page 1 of N") with flexible placement.',
    fullDescription: 'Stamp customizable pagination numbers with header/footer positions, custom formatting templates, font sizing, and margins.',
    iconName: 'Hash',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Numbered PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib page enumeration',
    privacyNote: 'Numbers calculated and stamped strictly within client memory.',
    tags: ['page numbers', 'paginate', 'footer', 'header', 'numbering'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'pdf-overlay',
    slug: 'pdf-overlay',
    category: 'edit',
    title: 'PDF Overlay & Letterhead',
    shortDescription: 'Merge background letterheads or foreground frames onto existing PDFs.',
    fullDescription: 'Overlay a letterhead template or official border graphics across all pages of a target PDF document.',
    iconName: 'Copy',
    supportedInputTypes: ['PDF', 'Letterhead PDF/Image'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'pdf-lib embedded page layer',
    privacyNote: 'Overlay layering happens via client-side PDF document blending.',
    tags: ['overlay', 'letterhead', 'template', 'stationery', 'layer'],
    implementationStatus: 'implemented',
  },
  {
    id: 'crop-pdf',
    slug: 'crop-pdf',
    category: 'edit',
    title: 'Crop PDF Margins',
    shortDescription: 'Trim excess page margins or isolate specific rectangular regions.',
    fullDescription: 'Adjust PDF MediaBox and CropBox boundaries to eliminate white borders or crop scanned pages to exact focus areas.',
    iconName: 'Crop',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Cropped PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 40,
    requiredCapability: 'pdf-lib MediaBox adjustment',
    privacyNote: 'Bounding boxes are updated directly in memory.',
    tags: ['crop', 'trim', 'margins', 'cut', 'box'],
    implementationStatus: 'implemented',
  },
  {
    id: 'change-pdf-page-size',
    slug: 'change-pdf-page-size',
    category: 'edit',
    title: 'Change PDF Page Size',
    shortDescription: 'Resize document dimensions to standard A4, US Letter, A3, or custom sizes.',
    fullDescription: 'Standardize non-uniform PDF page dimensions to uniform paper formats with content scaling and auto-centering.',
    iconName: 'Maximize2',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Resized PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 40,
    requiredCapability: 'pdf-lib scale & translate page',
    privacyNote: 'Page scaling calculations occur locally.',
    tags: ['resize', 'page size', 'a4', 'letter', 'dimensions'],
    implementationStatus: 'implemented',
  },
  {
    id: 'edit-pdf-document-info',
    slug: 'edit-pdf-document-info',
    category: 'edit',
    title: 'Edit PDF Document Info',
    shortDescription: 'Update title, author, subject, keywords, and creator metadata properties.',
    fullDescription: 'Modify internal PDF metadata dictionary values (Title, Author, Subject, Keywords, Creator, Producer) without altering page content.',
    iconName: 'FileText',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Updated PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib metadata setters',
    privacyNote: 'Metadata properties updated locally.',
    tags: ['metadata', 'info', 'author', 'title', 'properties'],
    implementationStatus: 'implemented',
  },

  // ==========================================
  // 3. Organize PDF
  // ==========================================
  {
    id: 'merge-pdf',
    slug: 'merge-pdf',
    category: 'organize',
    title: 'Merge PDF Documents',
    shortDescription: 'Combine multiple PDF files into one organized, consolidated document.',
    fullDescription: 'Drag-and-drop multiple PDF files, reorder their sequence, and merge them into a single seamless PDF file in seconds.',
    iconName: 'GitMerge',
    supportedInputTypes: ['2+ PDF Files'],
    supportedOutputTypes: ['Merged PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 100,
    requiredCapability: 'pdf-lib document concatenator',
    privacyNote: 'All merging happens in local RAM. Zero bytes sent to cloud.',
    tags: ['merge', 'combine', 'join', 'bundle', 'concat'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'split-pdf',
    slug: 'split-pdf',
    category: 'organize',
    title: 'Split PDF & Extract Pages',
    shortDescription: 'Split documents by page ranges or extract each page into individual PDFs.',
    fullDescription: 'Divide large PDF files into distinct chapters or download all pages packaged in a clean, convenient ZIP archive.',
    iconName: 'Scissors',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['PDF', 'ZIP archive'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 100,
    requiredCapability: 'pdf-lib & jszip packager',
    privacyNote: 'Extraction executed strictly on the client.',
    tags: ['split', 'extract', 'separate', 'divide', 'zip'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'rearrange-pdf-pages',
    slug: 'rearrange-pdf-pages',
    category: 'organize',
    title: 'Rearrange PDF Pages',
    shortDescription: 'Visual drag-and-drop board to reorder, duplicate, and sort pages.',
    fullDescription: 'Floating glass page cards with drag-and-drop reordering, keyboard sorting alternatives, and instant preview.',
    iconName: 'Move',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Reordered PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib page reordering',
    privacyNote: 'Pages reorganized in-memory.',
    tags: ['rearrange', 'reorder', 'sort', 'pages', 'move'],
    implementationStatus: 'implemented',
  },
  {
    id: 'remove-pdf-pages',
    slug: 'remove-pdf-pages',
    category: 'organize',
    title: 'Remove PDF Pages',
    shortDescription: 'Delete blank, unwanted, or confidential pages from any PDF document.',
    fullDescription: 'Select pages visually or specify page numbers to strip them out completely from the output PDF.',
    iconName: 'Trash2',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Cleaned PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib page exclusion',
    privacyNote: 'Deleted pages are discarded from memory.',
    tags: ['remove', 'delete', 'strip', 'clean', 'pages'],
    implementationStatus: 'implemented',
  },
  {
    id: 'extract-pdf-pages',
    slug: 'extract-pdf-pages',
    category: 'organize',
    title: 'Extract PDF Pages',
    shortDescription: 'Save selected page numbers into a standalone new PDF document.',
    fullDescription: 'Choose specific pages from a master PDF and compile them into an isolated new PDF.',
    iconName: 'Download',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib page copying',
    privacyNote: 'Extracted pages compiled locally.',
    tags: ['extract', 'select', 'isolate', 'subset', 'export'],
    implementationStatus: 'implemented',
  },
  {
    id: 'rotate-pdf-pages',
    slug: 'rotate-pdf-pages',
    category: 'organize',
    title: 'Rotate PDF Pages',
    shortDescription: 'Rotate individual or all pages by 90°, 180°, or 270° permanently.',
    fullDescription: 'Fix upside-down or sideways scans with per-page orientation controls and permanent rotation tags.',
    iconName: 'RotateCw',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Rotated PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib rotation angle modifiers',
    privacyNote: 'Orientation flags updated locally.',
    tags: ['rotate', 'turn', 'orientation', 'upside down', 'landscape'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'pages-per-sheet',
    slug: 'pages-per-sheet',
    category: 'organize',
    title: 'Pages per Sheet (N-Up)',
    shortDescription: 'Place 2, 4, 6, or 8 pages onto a single sheet to save paper and printing costs.',
    fullDescription: 'Tile multiple consecutive pages into structured grid layouts per sheet with optional divider borders.',
    iconName: 'Grid',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['N-Up PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 40,
    requiredCapability: 'pdf-lib embedded page tiling',
    privacyNote: 'Tiling matrix rendered locally.',
    tags: ['n-up', '2-up', '4-up', 'sheets', 'print saving', 'tiling'],
    implementationStatus: 'implemented',
  },
  {
    id: 'halve-pdf-pages',
    slug: 'halve-pdf-pages',
    category: 'organize',
    title: 'Halve PDF Pages (Split Book Spreads)',
    shortDescription: 'Split 2-page scanned book spreads into two individual sequential pages.',
    fullDescription: 'Detects wide landscape 2-page spreads and splits them down the middle into left and right portrait pages.',
    iconName: 'Columns',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Split Spread PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 40,
    requiredCapability: 'pdf-lib dual crop box splitting',
    privacyNote: 'Book spreads split in memory.',
    tags: ['halve', 'spreads', 'book scan', 'split pages', 'dual'],
    implementationStatus: 'implemented',
  },
  {
    id: 'bookmarks-pdf',
    slug: 'bookmarks-pdf',
    category: 'organize',
    title: 'Edit PDF Bookmarks & Outline',
    shortDescription: 'View, add, and organize table of contents bookmarks in PDF documents.',
    fullDescription: 'Inspect document outline trees and edit PDF outline hierarchy nodes.',
    iconName: 'Bookmark',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['PDF with Bookmarks'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'pdf-lib PDFOutlines dictionary',
    privacyNote: 'Bookmarks edited locally.',
    tags: ['bookmarks', 'toc', 'outline', 'table of contents', 'navigation'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'extract-pdf-images',
    slug: 'extract-pdf-images',
    category: 'organize',
    title: 'Extract Images from PDF',
    shortDescription: 'Extract embedded photos, diagrams, and illustrations into high-res PNG/JPGs.',
    fullDescription: 'Extracts embedded raster image XObjects from PDF streams and packages them in a ZIP archive.',
    iconName: 'Image',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['ZIP of PNG/JPGs'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib stream parser & jszip',
    privacyNote: 'Extracted images bundled into local ZIP.',
    tags: ['extract images', 'photos', 'embedded', 'xobjects', 'rip'],
    isPopular: true,
    implementationStatus: 'implemented',
  },

  // ==========================================
  // 4. Optimize and Repair
  // ==========================================
  {
    id: 'compress-pdf',
    slug: 'compress-pdf',
    category: 'optimize-repair',
    title: 'Compress PDF & Shrink File Size',
    shortDescription: 'Optimize streams, remove redundant objects, and downsample images.',
    fullDescription: 'Shrink PDF file sizes by stripping unreferenced xref items, deduplicating fonts, and compressing raster streams.',
    iconName: 'Minimize2',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Compressed PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib object dictionary optimizer',
    privacyNote: 'Optimization computed entirely inside your browser.',
    tags: ['compress', 'shrink', 'reduce size', 'optimize', 'fast web'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'web-optimize-pdf',
    slug: 'web-optimize-pdf',
    category: 'optimize-repair',
    title: 'Web Optimize (Linearize / Fast View)',
    shortDescription: 'Structure PDF for instant streaming and fast online display.',
    fullDescription: 'Reorders PDF stream objects and dictionary tables for fast web viewing.',
    iconName: 'Zap',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Web Optimized PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 40,
    requiredCapability: 'pdf-lib stream linearizer',
    privacyNote: 'Linearization processed in client memory.',
    tags: ['web optimize', 'linearize', 'fast web view', 'stream', 'fast'],
    implementationStatus: 'implemented',
  },
  {
    id: 'ocr-pdf',
    slug: 'ocr-pdf',
    category: 'optimize-repair',
    title: 'OCR PDF (Searchable Text Layer)',
    shortDescription: 'Recognize scanned document text and insert an invisible searchable text layer.',
    fullDescription: 'Uses browser-based WebAssembly Tesseract OCR to recognize text in scanned pages and embed selectable text.',
    iconName: 'ScanText',
    supportedInputTypes: ['Scanned PDF', 'Images'],
    supportedOutputTypes: ['Searchable PDF'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 25,
    requiredCapability: 'WebAssembly Tesseract / Worker OCR',
    privacyNote: 'OCR models run locally via WebAssembly without external server API calls.',
    knownLimitations: ['Requires initial local download of language training data (~2-4 MB cached).'],
    tags: ['ocr', 'searchable', 'text recognition', 'scans', 'tesseract'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'repair-pdf',
    slug: 'repair-pdf',
    category: 'optimize-repair',
    title: 'Repair Corrupted PDF',
    shortDescription: 'Reconstruct damaged xref tables, truncated streams, and malformed catalogs.',
    fullDescription: 'Attempts client-side recovery by parsing intact raw PDF objects, rebuilding cross-reference tables, and re-serializing.',
    iconName: 'Wrench',
    supportedInputTypes: ['Damaged PDF'],
    supportedOutputTypes: ['Repaired PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 40,
    requiredCapability: 'pdf-lib tolerant parser',
    privacyNote: 'File stream reconstructed locally.',
    tags: ['repair', 'fix', 'corrupted', 'damaged', 'recovery'],
    implementationStatus: 'implemented',
  },
  {
    id: 'rasterize-pdf',
    slug: 'rasterize-pdf',
    category: 'optimize-repair',
    title: 'Rasterize PDF Pages',
    shortDescription: 'Convert all vector text, fonts, and layers into flattened pixel bitmaps.',
    fullDescription: 'Turns all pages into high-resolution images and compiles them back into a PDF, eliminating all live text, metadata, and vectors.',
    iconName: 'Grid',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Rasterized PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'Canvas rasterization & PDF rebuild',
    privacyNote: 'Rasterization guarantees zero hidden text remains in the file.',
    tags: ['rasterize', 'flatten', 'pixels', 'bitmap', 'sanitize'],
    implementationStatus: 'implemented',
  },
  {
    id: 'flatten-pdf',
    slug: 'flatten-pdf',
    category: 'optimize-repair',
    title: 'Flatten PDF Forms & Annotations',
    shortDescription: 'Permanently bake interactive form fields and annotations into page content.',
    fullDescription: 'Locks editable form fields, digital marks, and annotations so they become permanent, non-editable page graphics.',
    iconName: 'Layers',
    supportedInputTypes: ['PDF with Forms/Annotations'],
    supportedOutputTypes: ['Flattened PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib form flattening',
    privacyNote: 'Form values permanently embedded into page stream.',
    tags: ['flatten', 'lock', 'forms', 'non-editable', 'acroform'],
    implementationStatus: 'implemented',
  },
  {
    id: 'pdf-to-pdfa',
    slug: 'pdf-to-pdfa',
    category: 'optimize-repair',
    title: 'PDF to PDF/A (Archival Standard)',
    shortDescription: 'Embed fonts and set color profiles for long-term ISO archival compliance.',
    fullDescription: 'Sets PDF/A-1b and PDF/A-2b compliance dictionaries, embeds standard fonts, and strips non-compliant dynamic elements.',
    iconName: 'Archive',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['PDF/A Compliant PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'pdf-lib PDF/A profile embedder',
    privacyNote: 'Archival transformation executed locally.',
    tags: ['pdfa', 'archival', 'iso', 'long-term', 'compliance'],
    implementationStatus: 'implemented',
  },

  // ==========================================
  // 5. Security and Privacy
  // ==========================================
  {
    id: 'protect-pdf',
    slug: 'protect-pdf',
    category: 'security-privacy',
    title: 'Protect PDF with Password',
    shortDescription: 'Encrypt your PDF with standard user and owner passwords and access restrictions.',
    fullDescription: 'Add user password protection to prevent unauthorized opening, editing, printing, or copying of sensitive document pages.',
    iconName: 'Lock',
    supportedInputTypes: ['PDF', 'User Password'],
    supportedOutputTypes: ['Encrypted PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib standard encryption dictionary',
    privacyNote: 'Passwords are processed solely in memory and never stored, logged, or transmitted.',
    tags: ['protect', 'password', 'encrypt', 'lock', 'security'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'unlock-pdf',
    slug: 'unlock-pdf',
    category: 'security-privacy',
    title: 'Unlock PDF (Decrypt with Password)',
    shortDescription: 'Remove password restrictions from PDF documents when you know the password.',
    fullDescription: 'Decrypt and save an unprotected copy of your PDF by providing the authorized user/owner password. Note: AquaTools does not crack or bypass unknown passwords.',
    iconName: 'Unlock',
    supportedInputTypes: ['Encrypted PDF', 'Valid Password'],
    supportedOutputTypes: ['Unprotected PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib decryption pipeline',
    privacyNote: 'Decryption is performed locally. We never attempt brute-force password cracking.',
    knownLimitations: ['Requires the correct user or master password. Password recovery/cracking is not supported.'],
    tags: ['unlock', 'decrypt', 'remove password', 'unprotect', 'permission'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'sign-pdf',
    slug: 'sign-pdf',
    category: 'security-privacy',
    title: 'Sign PDF (Visual & Touch Signature)',
    shortDescription: 'Draw, type, or upload an image signature and stamp it onto specific pages.',
    fullDescription: 'Interactive signature pad for desktop mouse and mobile touchscreens with smooth ink smoothing, transparent background, and precision positioning.',
    iconName: 'PenTool',
    supportedInputTypes: ['PDF', 'Drawn / Image Signature'],
    supportedOutputTypes: ['Signed PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 40,
    requiredCapability: 'Canvas signature pad & pdf-lib embedder',
    privacyNote: 'Your signature strokes and image files stay in browser memory only.',
    knownLimitations: ['Generates a visual signature stamp; does not include X.509 PKI cryptographic certificates.'],
    tags: ['sign', 'signature', 'pen', 'draw signature', 'autograph'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'redact-pdf',
    slug: 'redact-pdf',
    category: 'security-privacy',
    title: 'Redact PDF (Permanent Blackout)',
    shortDescription: 'Permanently remove and obscure confidential text, SSNs, and sensitive numbers.',
    fullDescription: 'Draw permanent black redaction blocks over sensitive content and bake them into flattened raster page content so underlying vectors cannot be highlighted or extracted.',
    iconName: 'EyeOff',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Redacted PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'Canvas redaction & stream sanitizer',
    privacyNote: 'True redaction: underlying text is permanently stripped and replaced by opaque pixels.',
    tags: ['redact', 'blackout', 'censor', 'privacy', 'hide', 'ssn'],
    implementationStatus: 'implemented',
  },
  {
    id: 'remove-pdf-metadata',
    slug: 'remove-pdf-metadata',
    category: 'security-privacy',
    title: 'Remove PDF Metadata & Tracking',
    shortDescription: 'Wipe author names, software fingerprints, creation dates, and GPS coordinates.',
    fullDescription: 'Completely strips document info dictionaries, XMP metadata streams, editing history, and printer tags for clean anonymous distribution.',
    iconName: 'ShieldAlert',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Sanitized PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib metadata sanitization',
    privacyNote: 'All metadata properties are scrubbed locally in memory.',
    tags: ['metadata', 'sanitize', 'wipe', 'anonymize', 'privacy', 'xmp'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'generate-password',
    slug: 'generate-password',
    category: 'security-privacy',
    title: 'Generate Secure PDF Password',
    shortDescription: 'Create cryptographically strong random passwords and passphrases using Web Crypto.',
    fullDescription: 'CSPRNG entropy generation for ultra-secure 16-64 character passwords and Diceware passphrases with zero network calls.',
    iconName: 'Key',
    supportedInputTypes: ['Entropy settings'],
    supportedOutputTypes: ['Secure Password'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 1,
    requiredCapability: 'Web Crypto API (crypto.getRandomValues)',
    privacyNote: 'Generated strictly in browser memory.',
    tags: ['password', 'generate', 'csprng', 'passphrase', 'key'],
    implementationStatus: 'implemented',
  },

  // ==========================================
  // 6. View and Compare
  // ==========================================
  {
    id: 'view-pdf',
    slug: 'view-pdf',
    category: 'view-compare',
    title: 'View PDF (Secure Local Viewer)',
    shortDescription: 'Read and navigate PDF files locally with zoom, thumbnails, and zero tracking.',
    fullDescription: 'Privacy-first in-browser PDF reader with page thumbnail sidebar, page jump navigation, zoom scaling, and full-screen reading mode.',
    iconName: 'Eye',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Interactive Viewer'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 100,
    requiredCapability: 'HTML5 Canvas & PDF rendering',
    privacyNote: 'Document rendered locally on Canvas. No telemetry or analytics recorded.',
    tags: ['view', 'reader', 'preview', 'read', 'open'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'compare-pdfs',
    slug: 'compare-pdfs',
    category: 'view-compare',
    title: 'Compare PDFs (Side-by-Side & Diff)',
    shortDescription: 'Detect visual and text differences between two PDF document revisions.',
    fullDescription: 'Compare two PDF files side-by-side with synchronized scrolling and visual color highlight diff overlays.',
    iconName: 'GitCompare',
    supportedInputTypes: ['2 PDF Files'],
    supportedOutputTypes: ['Diff Report / Visual Comparison'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 40,
    requiredCapability: 'Canvas pixel diffing & text comparison',
    privacyNote: 'Both documents compared directly in local memory.',
    tags: ['compare', 'diff', 'revisions', 'side by side', 'changes'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'pdf-viewer-preferences',
    slug: 'pdf-viewer-preferences',
    category: 'view-compare',
    title: 'PDF Viewer Preferences & Initial View',
    shortDescription: 'Configure default zoom, page layout (single/double), and toolbar display flags.',
    fullDescription: 'Sets internal PDF ViewerPreferences dictionary so the PDF opens with custom initial display modes in external readers.',
    iconName: 'Sliders',
    supportedInputTypes: ['PDF', 'Preferences'],
    supportedOutputTypes: ['PDF with Custom View'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 40,
    requiredCapability: 'pdf-lib ViewerPreferences catalog',
    privacyNote: 'Preferences encoded locally.',
    tags: ['preferences', 'initial view', 'fit window', 'two page', 'fullscreen'],
    implementationStatus: 'implemented',
  },

  // ==========================================
  // 7. Convert to PDF
  // ==========================================
  {
    id: 'convert-to-pdf',
    slug: 'convert-to-pdf',
    category: 'convert-to-pdf',
    title: 'Convert File to PDF (Universal)',
    shortDescription: 'Universal multi-format converter for images, text, markdown, and web formats.',
    fullDescription: 'Drag in image files, markdown, text files, or HTML to automatically convert them into clean standard PDF files.',
    iconName: 'FilePlus2',
    supportedInputTypes: ['PNG', 'JPG', 'WebP', 'SVG', 'Markdown', 'TXT', 'HTML'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'Universal local compiler',
    privacyNote: 'Conversions executed 100% in browser memory.',
    tags: ['convert', 'to pdf', 'universal', 'images to pdf', 'text to pdf'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'jpg-to-pdf',
    slug: 'jpg-to-pdf',
    category: 'convert-to-pdf',
    title: 'JPG to PDF',
    shortDescription: 'Convert JPEG/JPG photo files into standard PDF documents with custom margins.',
    fullDescription: 'Fast client-side JPEG embedding into A4, Letter, or image-sized PDF pages.',
    iconName: 'Image',
    supportedInputTypes: ['JPG', 'JPEG'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib embedJpg',
    privacyNote: 'JPEG files embedded locally.',
    tags: ['jpg to pdf', 'jpeg', 'photos', 'convert'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'png-to-pdf',
    slug: 'png-to-pdf',
    category: 'convert-to-pdf',
    title: 'PNG to PDF',
    shortDescription: 'Convert PNG graphics with transparency preservation into crisp PDF pages.',
    fullDescription: 'Embeds PNG alpha-channel graphics directly into multi-page PDF documents.',
    iconName: 'Image',
    supportedInputTypes: ['PNG'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib embedPng',
    privacyNote: 'PNG files converted locally.',
    tags: ['png to pdf', 'transparent', 'convert', 'images'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'webp-to-pdf',
    slug: 'webp-to-pdf',
    category: 'convert-to-pdf',
    title: 'WebP to PDF',
    shortDescription: 'Convert modern WebP images into universal PDF documents.',
    fullDescription: 'Decodes modern WebP images via browser canvas and compiles them into standard PDF.',
    iconName: 'Image',
    supportedInputTypes: ['WebP'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 40,
    requiredCapability: 'Canvas WebP decoder & pdf-lib',
    privacyNote: 'WebP converted in browser memory.',
    tags: ['webp to pdf', 'webp', 'convert', 'photos'],
    implementationStatus: 'implemented',
  },
  {
    id: 'heic-to-pdf',
    slug: 'heic-to-pdf',
    category: 'convert-to-pdf',
    title: 'HEIC to PDF',
    shortDescription: 'Convert Apple iPhone HEIC photo captures directly into PDF documents.',
    fullDescription: 'Decodes HEIC container streams in-browser and compiles high-res photos into PDF.',
    iconName: 'Smartphone',
    supportedInputTypes: ['HEIC', 'HEIF'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'WebAssembly HEIC decoder',
    privacyNote: 'HEIC decoded client-side.',
    tags: ['heic to pdf', 'iphone', 'apple', 'heif', 'photos'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'svg-to-pdf',
    slug: 'svg-to-pdf',
    category: 'convert-to-pdf',
    title: 'SVG to PDF',
    shortDescription: 'Convert vector SVG illustrations and logos into scalable PDF files.',
    fullDescription: 'Parses scalable vector graphics into crisp vector PDF documents with transparent background support.',
    iconName: 'FileCode',
    supportedInputTypes: ['SVG'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 20,
    requiredCapability: 'SVG vector renderer & Canvas',
    privacyNote: 'SVG parsed inside isolated memory container.',
    tags: ['svg to pdf', 'vector', 'logo', 'scalable'],
    implementationStatus: 'implemented',
  },
  {
    id: 'tiff-to-pdf',
    slug: 'tiff-to-pdf',
    category: 'convert-to-pdf',
    title: 'TIFF to PDF',
    shortDescription: 'Convert multi-page TIFF document scans into standard PDF files.',
    fullDescription: 'Decodes TIFF raster layers and merges them into standard multi-page PDF files.',
    iconName: 'FileArchive',
    supportedInputTypes: ['TIFF', 'TIF'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 40,
    requiredCapability: 'TIFF decoder library',
    privacyNote: 'TIFF decoded in browser memory.',
    tags: ['tiff to pdf', 'tif', 'scans', 'multipage'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'text-to-pdf',
    slug: 'text-to-pdf',
    category: 'convert-to-pdf',
    title: 'Text to PDF',
    shortDescription: 'Convert plain text notes and code files into formatted vector PDF pages.',
    fullDescription: 'Formats plain text (.txt, .log, code) with word-wrapping, line numbering, monospace/proportional fonts, and pagination.',
    iconName: 'FileText',
    supportedInputTypes: ['TXT', 'LOG', 'Code'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 10,
    requiredCapability: 'pdf-lib standard typography',
    privacyNote: 'Text rendered locally into PDF.',
    tags: ['text to pdf', 'txt', 'notes', 'code', 'monospace'],
    implementationStatus: 'implemented',
  },
  {
    id: 'markdown-to-pdf',
    slug: 'markdown-to-pdf',
    category: 'convert-to-pdf',
    title: 'Markdown to PDF',
    shortDescription: 'Render Markdown notes with headings, tables, code blocks, and lists to PDF.',
    fullDescription: 'Transforms GitHub-flavored Markdown into beautifully styled PDF documents with typography hierarchy and tables.',
    iconName: 'FileCode2',
    supportedInputTypes: ['MD', 'Markdown'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 10,
    requiredCapability: 'Markdown parser & DOM canvas',
    privacyNote: 'Markdown parsed in memory.',
    tags: ['markdown to pdf', 'md', 'readme', 'gfm', 'docs'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    category: 'convert-to-pdf',
    title: 'Word to PDF (DOCX)',
    shortDescription: 'Convert Microsoft Word DOCX documents into PDF format.',
    fullDescription: 'Client-side DOCX parser extracting typography, headings, tables, and images to generate PDF.',
    iconName: 'FileText',
    supportedInputTypes: ['DOCX'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 20,
    requiredCapability: 'DOCX XML parser',
    privacyNote: 'Document parsed inside client sandbox.',
    knownLimitations: ['Complex Word macros, custom WordArt, and proprietary nested tables may have simplified layout styling.'],
    tags: ['word to pdf', 'docx', 'doc', 'microsoft word'],
    isPopular: true,
    implementationStatus: 'stub-ready',
  },
  {
    id: 'docx-to-pdf',
    slug: 'docx-to-pdf',
    category: 'convert-to-pdf',
    title: 'DOCX to PDF',
    shortDescription: 'Direct DOCX to PDF converter with formatting preservation.',
    fullDescription: 'Extracts DOCX document structure and compiles it into a standard PDF.',
    iconName: 'FileText',
    supportedInputTypes: ['DOCX'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 20,
    requiredCapability: 'DOCX parser',
    privacyNote: 'Processed locally.',
    tags: ['docx to pdf', 'word', 'office'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'powerpoint-to-pdf',
    slug: 'powerpoint-to-pdf',
    category: 'convert-to-pdf',
    title: 'PowerPoint to PDF (PPTX)',
    shortDescription: 'Convert presentation slide decks into multi-page PDF documents.',
    fullDescription: 'Extracts PPTX slide shapes, text frames, and background graphics into sequential PDF slide pages.',
    iconName: 'Presentation',
    supportedInputTypes: ['PPTX'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 25,
    requiredCapability: 'PPTX slide unpacker',
    privacyNote: 'Presentation data processed locally.',
    tags: ['powerpoint to pdf', 'pptx', 'slides', 'presentation'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'pptx-to-pdf',
    slug: 'pptx-to-pdf',
    category: 'convert-to-pdf',
    title: 'PPTX to PDF',
    shortDescription: 'Direct PPTX slide presentation to PDF converter.',
    fullDescription: 'Converts presentation slide layouts into PDF format.',
    iconName: 'Presentation',
    supportedInputTypes: ['PPTX'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 25,
    requiredCapability: 'PPTX unpacker',
    privacyNote: 'Processed locally.',
    tags: ['pptx', 'slides', 'powerpoint'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'excel-to-pdf',
    slug: 'excel-to-pdf',
    category: 'convert-to-pdf',
    title: 'Excel to PDF (XLSX)',
    shortDescription: 'Convert spreadsheet sheets, calculation tables, and grids into PDF format.',
    fullDescription: 'Parses XLSX workbook worksheets and renders cell grids into paginated PDF tables.',
    iconName: 'Table',
    supportedInputTypes: ['XLSX', 'XLS', 'CSV'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 20,
    requiredCapability: 'XLSX sheet parser',
    privacyNote: 'Spreadsheet numbers and tables processed in memory.',
    tags: ['excel to pdf', 'xlsx', 'spreadsheet', 'sheets', 'tables'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'xlsx-to-pdf',
    slug: 'xlsx-to-pdf',
    category: 'convert-to-pdf',
    title: 'XLSX to PDF',
    shortDescription: 'Direct XLSX workbook to formatted PDF table sheets.',
    fullDescription: 'Converts XLSX worksheets into PDF tables.',
    iconName: 'Table',
    supportedInputTypes: ['XLSX'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 20,
    requiredCapability: 'XLSX sheet parser',
    privacyNote: 'Processed locally.',
    tags: ['xlsx to pdf', 'excel', 'spreadsheet'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'doc-to-pdf',
    slug: 'doc-to-pdf',
    category: 'convert-to-pdf',
    title: 'DOC to PDF (Legacy Word)',
    shortDescription: 'Convert legacy binary Microsoft Word (.doc) documents to PDF.',
    fullDescription: 'Parses legacy Word OLE2 binary structures for client-side text and formatting extraction.',
    iconName: 'FileText',
    supportedInputTypes: ['DOC'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'coming-soon',
    localProcessing: true,
    maxRecommendedFileSizeMB: 15,
    requiredCapability: 'Legacy OLE2 parser (Under development)',
    privacyNote: 'No files are sent to remote conversion servers.',
    knownLimitations: ['Legacy binary .doc format requires complex OLE2 stream reconstruction. For best results, save as .docx.'],
    tags: ['doc to pdf', 'legacy word', 'doc', 'office 97-2003'],
    implementationStatus: 'coming-soon',
  },
  {
    id: 'ppt-to-pdf',
    slug: 'ppt-to-pdf',
    category: 'convert-to-pdf',
    title: 'PPT to PDF (Legacy PowerPoint)',
    shortDescription: 'Convert legacy binary PowerPoint (.ppt) slide files to PDF.',
    fullDescription: 'Legacy binary presentation converter undergoing local WebAssembly porting.',
    iconName: 'Presentation',
    supportedInputTypes: ['PPT'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'coming-soon',
    localProcessing: true,
    maxRecommendedFileSizeMB: 15,
    requiredCapability: 'Legacy binary presentation parser',
    privacyNote: 'Local conversion pipeline.',
    tags: ['ppt to pdf', 'legacy powerpoint', 'ppt'],
    implementationStatus: 'coming-soon',
  },
  {
    id: 'xls-to-pdf',
    slug: 'xls-to-pdf',
    category: 'convert-to-pdf',
    title: 'XLS to PDF (Legacy Excel)',
    shortDescription: 'Convert legacy binary Excel (.xls) spreadsheets to PDF.',
    fullDescription: 'Extracts cell grids and data values from legacy BIFF8 binary spreadsheets.',
    iconName: 'Table',
    supportedInputTypes: ['XLS'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'coming-soon',
    localProcessing: true,
    maxRecommendedFileSizeMB: 15,
    requiredCapability: 'BIFF8 spreadsheet parser',
    privacyNote: 'Processed locally.',
    tags: ['xls to pdf', 'legacy excel', 'xls'],
    implementationStatus: 'coming-soon',
  },
  {
    id: 'publisher-to-pdf',
    slug: 'publisher-to-pdf',
    category: 'convert-to-pdf',
    title: 'Publisher to PDF (PUB)',
    shortDescription: 'Convert Microsoft Publisher (.pub) desktop publishing files to PDF.',
    fullDescription: 'Advanced browser support required for proprietary Microsoft Publisher vector layout files.',
    iconName: 'Layout',
    supportedInputTypes: ['PUB'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'coming-soon',
    localProcessing: true,
    maxRecommendedFileSizeMB: 15,
    requiredCapability: 'libmspub WebAssembly port',
    privacyNote: 'Zero cloud upload.',
    knownLimitations: ['Requires libmspub WebAssembly engine which is currently in active development.'],
    tags: ['publisher to pdf', 'pub', 'desktop publishing', 'ms publisher'],
    implementationStatus: 'coming-soon',
  },
  {
    id: 'pub-to-pdf',
    slug: 'pub-to-pdf',
    category: 'convert-to-pdf',
    title: 'PUB to PDF',
    shortDescription: 'Direct Microsoft Publisher document conversion.',
    fullDescription: 'Converts Publisher desktop publications into PDF format.',
    iconName: 'Layout',
    supportedInputTypes: ['PUB'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'coming-soon',
    localProcessing: true,
    maxRecommendedFileSizeMB: 15,
    requiredCapability: 'libmspub WebAssembly',
    privacyNote: 'Zero cloud upload.',
    tags: ['pub', 'publisher', 'ms publisher'],
    implementationStatus: 'coming-soon',
  },
  {
    id: 'odt-to-pdf',
    slug: 'odt-to-pdf',
    category: 'convert-to-pdf',
    title: 'ODT to PDF (OpenDocument Text)',
    shortDescription: 'Convert LibreOffice / OpenOffice ODT text documents into PDF.',
    fullDescription: 'Parses OpenDocument XML content.xml and styles.xml structures to compile PDF.',
    iconName: 'FileText',
    supportedInputTypes: ['ODT'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 20,
    requiredCapability: 'OpenDocument XML parser',
    privacyNote: 'ODT document parsed client-side.',
    tags: ['odt to pdf', 'opendocument', 'libreoffice', 'openoffice'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'ods-to-pdf',
    slug: 'ods-to-pdf',
    category: 'convert-to-pdf',
    title: 'ODS to PDF (OpenDocument Spreadsheet)',
    shortDescription: 'Convert OpenDocument ODS spreadsheets into PDF tables.',
    fullDescription: 'Converts OpenDocument spreadsheet tables into paginated PDF.',
    iconName: 'Table',
    supportedInputTypes: ['ODS'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 20,
    requiredCapability: 'ODS parser',
    privacyNote: 'Processed locally.',
    tags: ['ods to pdf', 'opendocument spreadsheet', 'libreoffice calc'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'odp-to-pdf',
    slug: 'odp-to-pdf',
    category: 'convert-to-pdf',
    title: 'ODP to PDF (OpenDocument Presentation)',
    shortDescription: 'Convert OpenDocument ODP slide shows into PDF pages.',
    fullDescription: 'Converts OpenDocument presentation slides into PDF pages.',
    iconName: 'Presentation',
    supportedInputTypes: ['ODP'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 20,
    requiredCapability: 'ODP slide parser',
    privacyNote: 'Processed locally.',
    tags: ['odp to pdf', 'opendocument presentation', 'impress'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'odg-to-pdf',
    slug: 'odg-to-pdf',
    category: 'convert-to-pdf',
    title: 'ODG to PDF (OpenDocument Drawing)',
    shortDescription: 'Convert OpenDocument ODG vector drawings into PDF.',
    fullDescription: 'Converts OpenDocument vector drawings into PDF vector documents.',
    iconName: 'PenTool',
    supportedInputTypes: ['ODG'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 20,
    requiredCapability: 'ODG vector parser',
    privacyNote: 'Processed locally.',
    tags: ['odg to pdf', 'opendocument drawing', 'draw'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'rtf-to-pdf',
    slug: 'rtf-to-pdf',
    category: 'convert-to-pdf',
    title: 'RTF to PDF (Rich Text Format)',
    shortDescription: 'Convert Rich Text Format (.rtf) documents to PDF format.',
    fullDescription: 'Parses RTF control words, fonts, and paragraph attributes into vector PDF pages.',
    iconName: 'FileText',
    supportedInputTypes: ['RTF'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 15,
    requiredCapability: 'RTF tokenizer & pdf-lib',
    privacyNote: 'RTF parsed locally.',
    tags: ['rtf to pdf', 'rich text', 'rtf', 'wordpad'],
    implementationStatus: 'implemented',
  },
  {
    id: 'epub-to-pdf',
    slug: 'epub-to-pdf',
    category: 'convert-to-pdf',
    title: 'EPUB to PDF (E-Book)',
    shortDescription: 'Convert reflowable EPUB e-books into formatted, paginated PDF documents.',
    fullDescription: 'Unpacks EPUB ZIP containers, parses XHTML chapters, and formats them into paginated PDF books.',
    iconName: 'BookOpen',
    supportedInputTypes: ['EPUB'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 25,
    requiredCapability: 'EPUB XHTML engine',
    privacyNote: 'E-book chapters processed locally.',
    tags: ['epub to pdf', 'ebook', 'kindle', 'epub', 'book'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'cbz-to-pdf',
    slug: 'cbz-to-pdf',
    category: 'convert-to-pdf',
    title: 'CBZ to PDF (Comic Book Archive)',
    shortDescription: 'Convert comic book CBZ archives into a continuous sequential PDF.',
    fullDescription: 'Unpacks sequential comic book page images from CBZ ZIP containers and compiles them into a unified PDF comic.',
    iconName: 'Book',
    supportedInputTypes: ['CBZ', 'CBR'],
    supportedOutputTypes: ['PDF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 60,
    requiredCapability: 'JSZip unpacker & pdf-lib embedder',
    privacyNote: 'Comic images unpacked and compiled in memory.',
    tags: ['cbz to pdf', 'comic', 'manga', 'cbr', 'cbz'],
    implementationStatus: 'implemented',
  },

  // ==========================================
  // 8. Convert from PDF
  // ==========================================
  {
    id: 'pdf-to-images',
    slug: 'pdf-to-images',
    category: 'convert-from-pdf',
    title: 'PDF to Images (PNG / JPG)',
    shortDescription: 'Render every PDF page into high-resolution images bundled in a ZIP.',
    fullDescription: 'Render pages at 150-300 DPI into crisp PNG or JPEG image files with optional ZIP archive packaging.',
    iconName: 'Images',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['PNG', 'JPG', 'ZIP Archive'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'HTML5 Canvas page renderer & JSZip',
    privacyNote: 'Page rendering executed entirely on local Canvas elements.',
    tags: ['pdf to images', 'pdf to jpg', 'pdf to png', 'render', 'zip'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'pdf-to-jpg',
    slug: 'pdf-to-jpg',
    category: 'convert-from-pdf',
    title: 'PDF to JPG',
    shortDescription: 'Extract and convert PDF pages into lightweight JPEG photo files.',
    fullDescription: 'Convert PDF pages to JPEG with customizable quality compression factor and background filling.',
    iconName: 'Image',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['JPG', 'ZIP Archive'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'Canvas JPEG encoder',
    privacyNote: 'JPEG files rendered locally.',
    tags: ['pdf to jpg', 'jpeg', 'photos', 'convert'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'pdf-to-png',
    slug: 'pdf-to-png',
    category: 'convert-from-pdf',
    title: 'PDF to PNG',
    shortDescription: 'Convert PDF pages into lossless PNG graphics with sharp text edges.',
    fullDescription: 'Export ultra-sharp PNG page renderings suitable for presentations, documents, and web publishing.',
    iconName: 'Image',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['PNG', 'ZIP Archive'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'Canvas PNG encoder',
    privacyNote: 'PNG files rendered locally.',
    tags: ['pdf to png', 'png', 'lossless', 'sharp'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'pdf-to-svg',
    slug: 'pdf-to-svg',
    category: 'convert-from-pdf',
    title: 'PDF to SVG (Vector Graphics)',
    shortDescription: 'Convert PDF pages into scalable vector SVG files with paths and text.',
    fullDescription: 'Converts vector paths, fonts, and shapes from PDF pages into standard SVG XML markup.',
    iconName: 'FileCode',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['SVG Vector', 'ZIP Archive'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'Vector SVG generator',
    privacyNote: 'SVG output generated locally.',
    tags: ['pdf to svg', 'vector', 'scalable', 'illustrator', 'svg'],
    implementationStatus: 'implemented',
  },
  {
    id: 'pdf-to-text',
    slug: 'pdf-to-text',
    category: 'convert-from-pdf',
    title: 'PDF to Text (Extract Text)',
    shortDescription: 'Extract selectable text and words from PDF documents into plain text (.txt).',
    fullDescription: 'Extracts text content stream operators (Tj, TJ, BT, ET) and formats words, paragraphs, and page breaks into clean text.',
    iconName: 'FileText',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Plain Text (.txt)'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 50,
    requiredCapability: 'pdf-lib stream text extractor',
    privacyNote: 'Extracted text stays in your browser. Zero cloud logging.',
    tags: ['pdf to text', 'extract text', 'txt', 'copy text', 'words'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'pdf-to-html',
    slug: 'pdf-to-html',
    category: 'convert-from-pdf',
    title: 'PDF to HTML',
    shortDescription: 'Convert PDF document pages into structured, web-ready HTML/CSS pages.',
    fullDescription: 'Extracts paragraphs, headings, and images into clean responsive HTML with CSS styling.',
    iconName: 'Globe',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['HTML & CSS'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'HTML structure builder',
    privacyNote: 'HTML generated locally.',
    tags: ['pdf to html', 'web page', 'html', 'css', 'export'],
    implementationStatus: 'implemented',
  },
  {
    id: 'pdf-to-markdown',
    slug: 'pdf-to-markdown',
    category: 'convert-from-pdf',
    title: 'PDF to Markdown',
    shortDescription: 'Convert PDF documents into clean, structured Markdown (.md) notes.',
    fullDescription: 'Extracts headings, lists, tables, and paragraphs into formatted Markdown ready for Obsidian, Notion, or GitHub.',
    iconName: 'FileCode2',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Markdown (.md)'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'Markdown structural extractor',
    privacyNote: 'Markdown compiled in memory.',
    tags: ['pdf to markdown', 'md', 'notion', 'obsidian', 'notes'],
    isPopular: true,
    implementationStatus: 'implemented',
  },
  {
    id: 'pdf-to-word',
    slug: 'pdf-to-word',
    category: 'convert-from-pdf',
    title: 'PDF to Word (DOCX)',
    shortDescription: 'Reconstruct PDF pages into editable Microsoft Word DOCX documents.',
    fullDescription: 'Extracts text lines, styling, and embedded images into a standard OpenXML DOCX container.',
    iconName: 'FileText',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['DOCX'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 25,
    requiredCapability: 'DOCX generator & JSZip',
    privacyNote: 'DOCX container assembled strictly on the client.',
    knownLimitations: ['Multi-column complex magazine layouts are converted with linear text flow.'],
    tags: ['pdf to word', 'docx', 'doc', 'editable word'],
    isPopular: true,
    implementationStatus: 'stub-ready',
  },
  {
    id: 'pdf-to-docx',
    slug: 'pdf-to-docx',
    category: 'convert-from-pdf',
    title: 'PDF to DOCX',
    shortDescription: 'Direct PDF to DOCX document reconstruction.',
    fullDescription: 'Converts PDF documents into editable DOCX files.',
    iconName: 'FileText',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['DOCX'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 25,
    requiredCapability: 'DOCX OpenXML builder',
    privacyNote: 'Processed locally.',
    tags: ['pdf to docx', 'word', 'office'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'pdf-to-powerpoint',
    slug: 'pdf-to-powerpoint',
    category: 'convert-from-pdf',
    title: 'PDF to PowerPoint (PPTX)',
    shortDescription: 'Convert PDF pages into editable PowerPoint presentation slides.',
    fullDescription: 'Converts individual PDF pages into PPTX slide layouts with background rendering and text layers.',
    iconName: 'Presentation',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['PPTX'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 25,
    requiredCapability: 'PPTX slide builder',
    privacyNote: 'PPTX slides generated in memory.',
    tags: ['pdf to powerpoint', 'pptx', 'presentation', 'slides'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'pdf-to-pptx',
    slug: 'pdf-to-pptx',
    category: 'convert-from-pdf',
    title: 'PDF to PPTX',
    shortDescription: 'Direct PDF to PPTX slide presentation exporter.',
    fullDescription: 'Converts PDF pages to presentation slides.',
    iconName: 'Presentation',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['PPTX'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 25,
    requiredCapability: 'PPTX builder',
    privacyNote: 'Processed locally.',
    tags: ['pdf to pptx', 'slides', 'powerpoint'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'pdf-to-excel',
    slug: 'pdf-to-excel',
    category: 'convert-from-pdf',
    title: 'PDF to Excel (XLSX / CSV)',
    shortDescription: 'Detect tables and cell grids in PDF and export them to Excel spreadsheets.',
    fullDescription: 'Analyzes tabular line structures and cell coordinates in PDF documents to generate structured XLSX and CSV workbooks.',
    iconName: 'Table',
    supportedInputTypes: ['PDF with Tables'],
    supportedOutputTypes: ['XLSX', 'CSV'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 25,
    requiredCapability: 'Table coordinate detector & XLSX builder',
    privacyNote: 'Financial tables and numbers extracted strictly in client memory.',
    tags: ['pdf to excel', 'xlsx', 'csv', 'tables', 'extract data'],
    isPopular: true,
    implementationStatus: 'stub-ready',
  },
  {
    id: 'pdf-to-xlsx',
    slug: 'pdf-to-xlsx',
    category: 'convert-from-pdf',
    title: 'PDF to XLSX',
    shortDescription: 'Direct PDF to XLSX spreadsheet converter.',
    fullDescription: 'Extracts tabular data into Excel worksheets.',
    iconName: 'Table',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['XLSX'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 25,
    requiredCapability: 'XLSX builder',
    privacyNote: 'Processed locally.',
    tags: ['pdf to xlsx', 'excel', 'spreadsheet'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'pdf-to-odt',
    slug: 'pdf-to-odt',
    category: 'convert-from-pdf',
    title: 'PDF to ODT (OpenDocument Text)',
    shortDescription: 'Convert PDF content into LibreOffice / OpenOffice ODT documents.',
    fullDescription: 'Builds OpenDocument text files from extracted PDF content streams.',
    iconName: 'FileText',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['ODT'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 20,
    requiredCapability: 'ODT XML builder',
    privacyNote: 'ODT assembled client-side.',
    tags: ['pdf to odt', 'opendocument', 'libreoffice'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'pdf-to-ods',
    slug: 'pdf-to-ods',
    category: 'convert-from-pdf',
    title: 'PDF to ODS (OpenDocument Calc)',
    shortDescription: 'Convert PDF tables into OpenDocument spreadsheet format.',
    fullDescription: 'Exports detected tables into ODS spreadsheet worksheets.',
    iconName: 'Table',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['ODS'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 20,
    requiredCapability: 'ODS builder',
    privacyNote: 'Processed locally.',
    tags: ['pdf to ods', 'libreoffice calc', 'ods'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'pdf-to-odp',
    slug: 'pdf-to-odp',
    category: 'convert-from-pdf',
    title: 'PDF to ODP (OpenDocument Impress)',
    shortDescription: 'Convert PDF pages into OpenDocument presentation slides.',
    fullDescription: 'Converts PDF pages into ODP slide deck files.',
    iconName: 'Presentation',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['ODP'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 20,
    requiredCapability: 'ODP builder',
    privacyNote: 'Processed locally.',
    tags: ['pdf to odp', 'impress', 'odp'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'pdf-to-rtf',
    slug: 'pdf-to-rtf',
    category: 'convert-from-pdf',
    title: 'PDF to RTF (Rich Text Format)',
    shortDescription: 'Export PDF text and typography into universal Rich Text Format.',
    fullDescription: 'Formats extracted text with basic typography into RTF files.',
    iconName: 'FileText',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['RTF'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 20,
    requiredCapability: 'RTF stream writer',
    privacyNote: 'RTF exported locally.',
    tags: ['pdf to rtf', 'rich text', 'rtf'],
    implementationStatus: 'implemented',
  },
  {
    id: 'pdf-to-epub',
    slug: 'pdf-to-epub',
    category: 'convert-from-pdf',
    title: 'PDF to EPUB (Reflowable E-Book)',
    shortDescription: 'Convert PDF books and articles into reflowable EPUB e-reader files.',
    fullDescription: 'Extracts linear text and headings, packaging them into an EPUB container for mobile e-readers.',
    iconName: 'BookOpen',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['EPUB'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 25,
    requiredCapability: 'EPUB packager & JSZip',
    privacyNote: 'EPUB packaged locally.',
    tags: ['pdf to epub', 'ebook', 'kindle', 'epub'],
    implementationStatus: 'stub-ready',
  },

  // ==========================================
  // 9. Image Conversion for PDF Workflows
  // ==========================================
  {
    id: 'heic-to-jpg',
    slug: 'heic-to-jpg',
    category: 'image-conversion',
    title: 'HEIC to JPG Converter',
    shortDescription: 'Convert Apple HEIC photos to standard JPG format for easy PDF inclusion.',
    fullDescription: 'Decodes Apple HEIC/HEIF photos and encodes them into universal JPEG files directly in browser memory.',
    iconName: 'Image',
    supportedInputTypes: ['HEIC', 'HEIF'],
    supportedOutputTypes: ['JPG'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'WebAssembly HEIC decoder & Canvas',
    privacyNote: 'Zero photo upload. Transcoded on your device.',
    tags: ['heic to jpg', 'apple', 'iphone', 'heic', 'jpg'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'heic-to-png',
    slug: 'heic-to-png',
    category: 'image-conversion',
    title: 'HEIC to PNG Converter',
    shortDescription: 'Convert Apple HEIC photos into lossless PNG format with transparency.',
    fullDescription: 'Transforms HEIC images into full-fidelity lossless PNG graphics.',
    iconName: 'Image',
    supportedInputTypes: ['HEIC', 'HEIF'],
    supportedOutputTypes: ['PNG'],
    browserSupportLevel: 'beta',
    localProcessing: true,
    maxRecommendedFileSizeMB: 30,
    requiredCapability: 'WebAssembly HEIC decoder & Canvas',
    privacyNote: 'Transcoded locally.',
    tags: ['heic to png', 'apple', 'iphone', 'heic', 'png'],
    implementationStatus: 'stub-ready',
  },
  {
    id: 'webp-to-jpg',
    slug: 'webp-to-jpg',
    category: 'image-conversion',
    title: 'WebP to JPG Converter',
    shortDescription: 'Convert modern WebP images into standard high-compatibility JPG format.',
    fullDescription: 'Converts WebP images into JPEG with adjustable quality settings.',
    iconName: 'Image',
    supportedInputTypes: ['WebP'],
    supportedOutputTypes: ['JPG'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 40,
    requiredCapability: 'HTML5 Canvas',
    privacyNote: 'Converted locally in canvas context.',
    tags: ['webp to jpg', 'webp', 'jpg', 'jpeg'],
    implementationStatus: 'implemented',
  },
  {
    id: 'webp-to-png',
    slug: 'webp-to-png',
    category: 'image-conversion',
    title: 'WebP to PNG Converter',
    shortDescription: 'Convert WebP images into lossless PNG graphics with alpha transparency.',
    fullDescription: 'Converts WebP images to lossless PNG files preserving transparent pixels.',
    iconName: 'Image',
    supportedInputTypes: ['WebP'],
    supportedOutputTypes: ['PNG'],
    browserSupportLevel: 'ready',
    localProcessing: true,
    maxRecommendedFileSizeMB: 40,
    requiredCapability: 'HTML5 Canvas',
    privacyNote: 'Converted locally in canvas context.',
    tags: ['webp to png', 'webp', 'png', 'transparency'],
    implementationStatus: 'implemented',
  },
];

export function getPdfToolBySlug(slug: string): PdfToolDefinition | undefined {
  return PDF_TOOLS.find((t) => t.slug === slug || t.id === slug);
}

export function getPdfToolsByCategory(category: PdfToolCategory): PdfToolDefinition[] {
  return PDF_TOOLS.filter((t) => t.category === category);
}

export function searchPdfTools(query: string): PdfToolDefinition[] {
  const q = query.toLowerCase().trim();
  if (!q) return PDF_TOOLS;
  return PDF_TOOLS.filter((t) => {
    return (
      t.title.toLowerCase().includes(q) ||
      t.shortDescription.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.toLowerCase().includes(q))
    );
  });
}
