import { CategoryMeta, ToolCategory, ToolDefinition } from '../types';

export const CATEGORIES: CategoryMeta[] = [
  {
    id: 'converters',
    name: 'File Converters',
    description: 'Transform images, code, markup, and documents client-side.',
    iconName: 'RefreshCw',
    color: 'from-cyan-500/20 to-blue-500/10 border-cyan-500/30 text-cyan-400',
  },
  {
    id: 'documents',
    name: 'Document & PDF',
    description: 'Inspect, merge, and split PDF documents locally.',
    iconName: 'FileText',
    color: 'from-sky-500/20 to-indigo-500/10 border-sky-500/30 text-sky-400',
  },
  {
    id: 'developer',
    name: 'Developer & Text',
    description: 'Web Crypto hashes, JWT decoding, UUIDs, diffs, and formatting.',
    iconName: 'Code2',
    color: 'from-teal-500/20 to-emerald-500/10 border-teal-500/30 text-teal-400',
  },
  {
    id: 'generators',
    name: 'Generators',
    description: 'Create QR codes, favicons, meta tags, gradients, and mock data.',
    iconName: 'Sparkles',
    color: 'from-cyan-500/20 to-teal-500/10 border-cyan-500/30 text-cyan-300',
  },
  {
    id: 'utilities',
    name: 'Image & Utilities',
    description: 'Crop images, pick colors, and inspect binary file signatures.',
    iconName: 'Wrench',
    color: 'from-blue-500/20 to-cyan-500/10 border-blue-500/30 text-blue-400',
  },
];

export const TOOLS: ToolDefinition[] = [
  // --- A. File Converters ---
  {
    id: 'image-converter',
    slug: 'image-converter',
    name: 'Image Format Converter',
    category: 'converters',
    description: 'Convert between PNG, JPG, and WebP with custom dimensions, quality, and background color.',
    iconName: 'Image',
    supportedInputTypes: ['PNG', 'JPG', 'JPEG', 'WebP', 'SVG', 'GIF', 'BMP'],
    supportedOutputTypes: ['PNG', 'JPG', 'WebP'],
    privacyNote: 'Image rendering occurs directly on a local Canvas element. No data leaves your device.',
    browserSupportNote: 'Supported in all modern browsers supporting HTML5 Canvas2D.',
    tags: ['image', 'convert', 'png', 'jpg', 'webp', 'resize'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'ImageConverterTool',
  },
  {
    id: 'image-compressor',
    slug: 'image-compressor',
    name: 'Image Compressor & Optimizer',
    category: 'converters',
    description: 'Compress PNG, JPEG, and WebP images with real-time visual quality preview and size savings.',
    iconName: 'Minimize2',
    supportedInputTypes: ['PNG', 'JPG', 'JPEG', 'WebP'],
    supportedOutputTypes: ['PNG', 'JPG', 'WebP'],
    privacyNote: 'Compression is executed in browser memory with instant blob URL disposal.',
    browserSupportNote: 'Requires HTML5 Canvas toBlob API.',
    tags: ['compress', 'optimize', 'shrink', 'image', 'jpg', 'png'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'ImageCompressorTool',
  },
  {
    id: 'svg-converter',
    slug: 'svg-converter',
    name: 'SVG to PNG Converter',
    category: 'converters',
    description: 'Render scalable vector graphics (SVG) to raster PNG with custom scale factor and background.',
    iconName: 'FileCode',
    supportedInputTypes: ['SVG'],
    supportedOutputTypes: ['PNG', 'WebP'],
    privacyNote: 'SVG is loaded as an isolated image element without executing external scripts.',
    browserSupportNote: 'Supported on all standard browsers.',
    tags: ['svg', 'vector', 'png', 'export', 'rasterize'],
    maxFileSizeMB: 20,
    componentId: 'ImageConverterTool',
  },
  {
    id: 'json-csv-converter',
    slug: 'json-csv-converter',
    name: 'JSON ↔ CSV Converter',
    category: 'converters',
    description: 'Bidirectional conversion between JSON arrays and CSV tables with custom delimiters.',
    iconName: 'Table',
    supportedInputTypes: ['JSON', 'CSV'],
    supportedOutputTypes: ['CSV', 'JSON'],
    privacyNote: 'Parsing occurs via pure JavaScript in your active tab memory.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['json', 'csv', 'spreadsheet', 'data', 'table'],
    isPopular: true,
    maxFileSizeMB: 10,
    componentId: 'JsonCsvConverterTool',
  },
  {
    id: 'code-formatter',
    slug: 'code-formatter',
    name: 'Code Formatter & Minifier',
    category: 'converters',
    description: 'Validate, format, and minify JSON, XML, HTML, CSS, and JavaScript with clean syntax.',
    iconName: 'Braces',
    supportedInputTypes: ['JSON', 'XML', 'HTML', 'CSS', 'JS'],
    supportedOutputTypes: ['Formatted Code', 'Minified Code'],
    privacyNote: 'No external code formatters or servers are contacted.',
    browserSupportNote: 'Standard JavaScript execution.',
    tags: ['format', 'minify', 'beautify', 'json', 'xml', 'html', 'css', 'javascript'],
    isPopular: true,
    maxFileSizeMB: 10,
    componentId: 'CodeFormatterTool',
  },
  {
    id: 'markdown-preview',
    slug: 'markdown-preview',
    name: 'Markdown to HTML Converter',
    category: 'converters',
    description: 'Write Markdown with real-time live preview, sanitized HTML output, and file download.',
    iconName: 'BookOpen',
    supportedInputTypes: ['Markdown', 'MD', 'Text'],
    supportedOutputTypes: ['HTML', 'Preview'],
    privacyNote: 'HTML preview is rendered safely without script execution.',
    browserSupportNote: 'Standard JavaScript engine.',
    tags: ['markdown', 'html', 'preview', 'docs', 'readme'],
    maxFileSizeMB: 5,
    componentId: 'MarkdownPreviewTool',
  },
  {
    id: 'base64-converter',
    slug: 'base64-converter',
    name: 'Base64 Encoder & Decoder',
    category: 'converters',
    description: 'Encode and decode text strings or binary files to and from Base64 and Data URIs.',
    iconName: 'Binary',
    supportedInputTypes: ['Text', 'Files (Any type)'],
    supportedOutputTypes: ['Base64 String', 'Data URI', 'Decoded File'],
    privacyNote: 'Uses standard FileReader readAsDataURL and atob/btoa locally.',
    browserSupportNote: 'Supported on all modern browsers.',
    tags: ['base64', 'encode', 'decode', 'data uri', 'binary'],
    isPopular: true,
    maxFileSizeMB: 25,
    componentId: 'Base64Tool',
  },
  {
    id: 'url-encoder',
    slug: 'url-encoder',
    name: 'URL Encoder & Decoder',
    category: 'converters',
    description: 'Encode and decode standard URLs, URI components, and parse query parameters.',
    iconName: 'Link',
    supportedInputTypes: ['Text', 'URL'],
    supportedOutputTypes: ['Encoded URL', 'Decoded URL', 'Query Parameters'],
    privacyNote: 'Executes using native encodeURIComponent and decodeURIComponent.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['url', 'uri', 'encode', 'decode', 'querystring'],
    maxFileSizeMB: 5,
    componentId: 'UrlEncoderTool',
  },

  // --- B. Document & PDF Utilities ---
  {
    id: 'pdf-metadata',
    slug: 'pdf-metadata',
    name: 'PDF Metadata & Info Inspector',
    category: 'documents',
    description: 'Inspect PDF page counts, author, creator, creation date, and encryption status locally.',
    iconName: 'FileCheck',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Document Metadata Table', 'JSON'],
    privacyNote: 'Parsed with pdf-lib directly in your browser without transmitting document contents.',
    browserSupportNote: 'Requires ArrayBuffer and TypedArray support.',
    tags: ['pdf', 'metadata', 'inspector', 'page count', 'info'],
    maxFileSizeMB: 50,
    componentId: 'PdfMetadataTool',
  },
  {
    id: 'pdf-merge-split',
    slug: 'pdf-merge-split',
    name: 'PDF Merge & Split Tool',
    category: 'documents',
    description: 'Merge multiple PDF files into one or extract specific page ranges (e.g., 1-3, 5) securely.',
    iconName: 'Files',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Merged PDF', 'Split PDF'],
    privacyNote: 'Documents are assembled in client RAM via pdf-lib and downloaded straight to your drive.',
    browserSupportNote: 'Requires modern browser memory support (recommended < 100MB per file).',
    tags: ['pdf', 'merge', 'split', 'combine', 'extract pages'],
    isPopular: true,
    maxFileSizeMB: 100,
    componentId: 'PdfMergeSplitTool',
  },

  // --- C. Developer & Text Utilities ---
  {
    id: 'uuid-generator',
    slug: 'uuid-generator',
    name: 'UUID / GUID Generator',
    category: 'developer',
    description: 'Generate single or bulk cryptographically secure RFC 4122 v4 UUIDs using the Web Crypto API.',
    iconName: 'Fingerprint',
    supportedInputTypes: ['None'],
    supportedOutputTypes: ['UUID v4 Strings'],
    privacyNote: 'Generated with window.crypto.randomUUID() / getRandomValues(). Never logged.',
    browserSupportNote: 'Web Crypto API standard.',
    tags: ['uuid', 'guid', 'v4', 'random', 'id'],
    isPopular: true,
    componentId: 'UuidGeneratorTool',
  },
  {
    id: 'password-generator',
    slug: 'password-generator',
    name: 'Strong Password & Passphrase Generator',
    category: 'developer',
    description: 'Create high-entropy passwords and diceware-style passphrases with entropy analysis.',
    iconName: 'KeyRound',
    supportedInputTypes: ['None'],
    supportedOutputTypes: ['Cryptographically Secure Passwords'],
    privacyNote: 'Built with window.crypto.getRandomValues(). Keys exist only in temporary UI state.',
    browserSupportNote: 'Web Crypto CSPRNG.',
    tags: ['password', 'passphrase', 'security', 'crypto', 'generator'],
    isPopular: true,
    componentId: 'PasswordGeneratorTool',
  },
  {
    id: 'hash-generator',
    slug: 'hash-generator',
    name: 'Cryptographic Hash Generator',
    category: 'developer',
    description: 'Compute SHA-256, SHA-384, and SHA-512 hashes for text and files using native SubtleCrypto.',
    iconName: 'ShieldCheck',
    supportedInputTypes: ['Text', 'File'],
    supportedOutputTypes: ['Hex Hashes (SHA-256, SHA-384, SHA-512)'],
    privacyNote: 'Processed via window.crypto.subtle.digest(). Zero network calls.',
    browserSupportNote: 'Web Crypto SubtleCrypto standard.',
    tags: ['hash', 'sha256', 'sha512', 'crypto', 'checksum'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'HashGeneratorTool',
  },
  {
    id: 'jwt-decoder',
    slug: 'jwt-decoder',
    name: 'JWT Token Decoder (Offline)',
    category: 'developer',
    description: 'Decode and inspect JSON Web Token headers, claims, and expiry dates locally without verification claims.',
    iconName: 'Key',
    supportedInputTypes: ['JWT String'],
    supportedOutputTypes: ['Parsed JSON Header & Payload'],
    privacyNote: 'Safe offline parsing. Never transmits your auth tokens across the internet.',
    browserSupportNote: 'Supported in all browsers.',
    tags: ['jwt', 'token', 'decode', 'json web token', 'auth', 'claims'],
    isPopular: true,
    componentId: 'JwtDecoderTool',
  },
  {
    id: 'timestamp-converter',
    slug: 'timestamp-converter',
    name: 'Unix Timestamp Converter',
    category: 'developer',
    description: 'Convert Unix epoch seconds/milliseconds to UTC, local formatted date, and relative time.',
    iconName: 'Clock',
    supportedInputTypes: ['Unix Timestamp', 'ISO Date', 'Date String'],
    supportedOutputTypes: ['Formatted Dates', 'Epoch Seconds/ms'],
    privacyNote: 'Local date arithmetic only.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['timestamp', 'unix', 'epoch', 'date', 'time'],
    componentId: 'TimestampConverterTool',
  },
  {
    id: 'color-converter',
    slug: 'color-converter',
    name: 'Color Format Converter',
    category: 'developer',
    description: 'Convert color values between HEX, RGB, HSL, and OKLCH with interactive visual picker.',
    iconName: 'Palette',
    supportedInputTypes: ['HEX', 'RGB', 'HSL'],
    supportedOutputTypes: ['HEX', 'RGB', 'HSL', 'CSS Code'],
    privacyNote: 'Runs in client memory.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['color', 'hex', 'rgb', 'hsl', 'css', 'palette'],
    componentId: 'ColorConverterTool',
  },
  {
    id: 'regex-tester',
    slug: 'regex-tester',
    name: 'Regular Expression Tester',
    category: 'developer',
    description: 'Test RegExp patterns against sample text with live match highlight, capture groups, and flags.',
    iconName: 'Terminal',
    supportedInputTypes: ['Regex Pattern', 'Test Text'],
    supportedOutputTypes: ['Match Highlights', 'Capture Group Inspector'],
    privacyNote: 'Evaluated locally in JavaScript sandbox.',
    browserSupportNote: 'Supported across all modern browsers.',
    tags: ['regex', 'regexp', 'match', 'pattern', 'test'],
    componentId: 'RegexTesterTool',
  },
  {
    id: 'text-utilities',
    slug: 'text-utilities',
    name: 'Text Utilities & Diff Viewer',
    category: 'developer',
    description: 'Word/character counters, case converters, line sorters, deduplication, and visual text diff.',
    iconName: 'AlignLeft',
    supportedInputTypes: ['Text'],
    supportedOutputTypes: ['Transformed Text', 'Side-by-Side Diff'],
    privacyNote: 'All string transformations are computed entirely in browser RAM.',
    browserSupportNote: 'Supported in all browsers.',
    tags: ['text', 'count', 'diff', 'case', 'sort', 'dedup', 'whitespace'],
    isPopular: true,
    maxFileSizeMB: 5,
    componentId: 'TextUtilitiesTool',
  },

  // --- D. Generator Tools ---
  {
    id: 'text-to-image',
    slug: 'text-to-image',
    name: 'Text to Image & Typography Studio',
    category: 'generators',
    description: 'Add watermarks, quotes, memes, and styled typography overlay onto photos, or generate high-res cards from scratch.',
    iconName: 'Type',
    supportedInputTypes: ['Text', 'PNG', 'JPG', 'WebP', 'SVG'],
    supportedOutputTypes: ['PNG Image', 'JPEG Image', 'WebP Image'],
    privacyNote: '100% client-side HTML5 Canvas typography rendering. No images or text ever leave your device.',
    browserSupportNote: 'Supported in all modern browsers with HTML5 Canvas and Blob APIs.',
    tags: ['text to image', 'add text to image', 'watermark', 'typography', 'meme', 'caption', 'quote', 'banner', 'overlay', 'poster'],
    isPopular: true,
    isNew: true,
    maxFileSizeMB: 40,
    componentId: 'TextToImageTool',
  },
  {
    id: 'qr-code-generator',
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    category: 'generators',
    description: 'Generate high-resolution customizable QR codes with custom colors, margin, and SVG/PNG download.',
    iconName: 'QrCode',
    supportedInputTypes: ['Text', 'URL', 'VCard', 'Wi-Fi'],
    supportedOutputTypes: ['PNG Image', 'SVG Vector', 'Data URL'],
    privacyNote: 'Generated offline via pure JavaScript QR generator canvas.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['qr', 'qrcode', 'barcode', 'generator', 'svg', 'png'],
    isPopular: true,
    componentId: 'QrCodeGeneratorTool',
  },
  {
    id: 'favicon-generator',
    slug: 'favicon-generator',
    name: 'Favicon & App Icon Generator',
    category: 'generators',
    description: 'Transform any square image into a complete favicon package (16px, 32px, 48px, Apple Touch, PWA) in a ZIP.',
    iconName: 'Layers',
    supportedInputTypes: ['PNG', 'JPG', 'SVG', 'WebP'],
    supportedOutputTypes: ['ZIP Archive with Icons & Manifest'],
    privacyNote: 'Resizing and ZIP packaging are processed entirely in browser memory.',
    browserSupportNote: 'Requires HTML5 Canvas and JSZip.',
    tags: ['favicon', 'icon', 'apple-touch-icon', 'pwa', 'manifest', 'zip'],
    isPopular: true,
    maxFileSizeMB: 20,
    componentId: 'FaviconGeneratorTool',
  },
  {
    id: 'random-generator',
    slug: 'random-generator',
    name: 'Random & Design Generator Suite',
    category: 'generators',
    description: 'Generate random numbers, list shufflers, slugs, lorem ipsum, CSS gradients, shadows, and buttons.',
    iconName: 'Sliders',
    supportedInputTypes: ['Parameters'],
    supportedOutputTypes: ['Generated Data', 'CSS Snippets'],
    privacyNote: 'Pure local mathematical generation.',
    browserSupportNote: 'Supported in all modern browsers.',
    tags: ['random', 'lorem', 'slug', 'css', 'gradient', 'shadow', 'button'],
    componentId: 'GeneratorSuiteTool',
  },
  {
    id: 'slug-generator',
    slug: 'slug-generator',
    name: 'URL Slug Generator',
    category: 'generators',
    description: 'Convert article titles, product names, and foreign phrases into clean, SEO-friendly URL slugs.',
    iconName: 'Link',
    supportedInputTypes: ['Text'],
    supportedOutputTypes: ['URL Slug'],
    privacyNote: '100% local text formatting with diacritic normalization.',
    browserSupportNote: 'Supported in all browsers.',
    tags: ['slug', 'url', 'seo', 'permalink', 'clean url', 'format'],
    isPopular: true,
    isNew: true,
    componentId: 'GeneratorSuiteTool',
  },
  {
    id: 'username-generator',
    slug: 'username-generator',
    name: 'Username & Handle Generator',
    category: 'generators',
    description: 'Generate developer, aesthetic, gamer, or minimalist usernames powered by Web Crypto CSPRNG.',
    iconName: 'UserCheck',
    supportedInputTypes: ['Parameters'],
    supportedOutputTypes: ['Usernames List'],
    privacyNote: 'Handles are generated client-side with zero external API calls.',
    browserSupportNote: 'Requires Web Crypto API.',
    tags: ['username', 'handle', 'alias', 'gamertag', 'random', 'crypto'],
    isPopular: true,
    isNew: true,
    componentId: 'GeneratorSuiteTool',
  },
  {
    id: 'palette-generator',
    slug: 'palette-generator',
    name: 'Color Palette & Harmony Generator',
    category: 'generators',
    description: 'Generate triadic, complementary, analogous, and monochromatic palettes with lockable swatches and WCAG contrast.',
    iconName: 'Palette',
    supportedInputTypes: ['Base Color', 'Harmony Rule'],
    supportedOutputTypes: ['CSS Variables', 'HEX / RGB / HSL'],
    privacyNote: 'Mathematical color wheel calculation in client memory.',
    browserSupportNote: 'Standard browser support.',
    tags: ['palette', 'color', 'harmony', 'triadic', 'complementary', 'css', 'design', 'wcag'],
    isPopular: true,
    isNew: true,
    componentId: 'GeneratorSuiteTool',
  },
  {
    id: 'gradient-generator',
    slug: 'gradient-generator',
    name: 'CSS Gradient Generator',
    category: 'generators',
    description: 'Create multi-stop linear and radial gradients with interactive canvas preview and CSS export.',
    iconName: 'Sparkles',
    supportedInputTypes: ['Color Stops', 'Angles'],
    supportedOutputTypes: ['CSS Code', 'Live Preview'],
    privacyNote: 'CSS generation with immediate preview.',
    browserSupportNote: 'All modern CSS3 browsers.',
    tags: ['gradient', 'css', 'linear', 'radial', 'design', 'background', 'style'],
    isPopular: true,
    isNew: true,
    componentId: 'GeneratorSuiteTool',
  },
  {
    id: 'shadow-generator',
    slug: 'shadow-generator',
    name: 'CSS Box & Text Shadow Generator',
    category: 'generators',
    description: 'Design smooth multi-layered box shadows and text elevations with real-time surface preview.',
    iconName: 'Box',
    supportedInputTypes: ['Offsets', 'Blur', 'Spread'],
    supportedOutputTypes: ['CSS box-shadow'],
    privacyNote: 'Calculated instantly in local DOM.',
    browserSupportNote: 'Standard CSS3 support.',
    tags: ['shadow', 'box-shadow', 'elevation', 'css', 'card', 'glow'],
    isPopular: true,
    isNew: true,
    componentId: 'GeneratorSuiteTool',
  },
  {
    id: 'robots-generator',
    slug: 'robots-generator',
    name: 'Robots.txt Generator',
    category: 'generators',
    description: 'Generate search crawler directives, AI bot blocks (GPTBot, ClaudeBot), and sitemap references.',
    iconName: 'Shield',
    supportedInputTypes: ['Form Inputs'],
    supportedOutputTypes: ['robots.txt file'],
    privacyNote: 'Formatted client-side.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['robots', 'seo', 'crawler', 'spider', 'ai bots', 'disallow'],
    isNew: true,
    componentId: 'WebBoilerplateTool',
  },
  {
    id: 'sitemap-generator',
    slug: 'sitemap-generator',
    name: 'Sitemap.xml Generator',
    category: 'generators',
    description: 'Generate XML sitemaps with custom page paths, change frequencies, priorities, and lastmod timestamps.',
    iconName: 'Globe',
    supportedInputTypes: ['Domain', 'Path List'],
    supportedOutputTypes: ['sitemap.xml file'],
    privacyNote: 'XML generation entirely in local memory.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['sitemap', 'xml', 'seo', 'google search', 'indexing'],
    isNew: true,
    componentId: 'WebBoilerplateTool',
  },
  {
    id: 'open-graph-generator',
    slug: 'open-graph-generator',
    name: 'Open Graph & Social Cards Generator',
    category: 'generators',
    description: 'Create social meta tags with live card previews for Facebook, Twitter/X, Discord, and Google.',
    iconName: 'Share2',
    supportedInputTypes: ['Title', 'Description', 'Image URL'],
    supportedOutputTypes: ['HTML Meta Tags'],
    privacyNote: 'Tags rendered locally.',
    browserSupportNote: 'Universal browser support.',
    tags: ['open graph', 'og', 'social card', 'meta tags', 'twitter card', 'seo'],
    isPopular: true,
    isNew: true,
    componentId: 'WebBoilerplateTool',
  },
  {
    id: 'passphrase-generator',
    slug: 'passphrase-generator',
    name: 'Passphrase & PIN Generator',
    category: 'developer',
    description: 'Create memorable Diceware-style passphrases and numeric PINs using Web Crypto CSPRNG.',
    iconName: 'Lock',
    supportedInputTypes: ['Word Count', 'Separator'],
    supportedOutputTypes: ['Secure Passphrase', 'PIN'],
    privacyNote: 'Web Crypto API entropy calculation. Zero network telemetry.',
    browserSupportNote: 'Supported across all modern browsers.',
    tags: ['passphrase', 'pin', 'diceware', 'password', 'security', 'crypto'],
    isPopular: true,
    isNew: true,
    componentId: 'PasswordGeneratorTool',
  },
  {
    id: 'web-boilerplate',
    slug: 'web-boilerplate',
    name: 'Web Config & Meta Tag Generator',
    category: 'generators',
    description: 'Create SEO-ready Open Graph meta tags, HTML5 boilerplate, robots.txt, and sitemap.xml.',
    iconName: 'Globe',
    supportedInputTypes: ['Form Inputs'],
    supportedOutputTypes: ['HTML', 'robots.txt', 'sitemap.xml'],
    privacyNote: 'Outputs are formatted strings generated on the fly.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['seo', 'opengraph', 'robots', 'sitemap', 'boilerplate', 'html5'],
    componentId: 'WebBoilerplateTool',
  },

  // --- E. Utility Tools ---
  {
    id: 'image-cropper',
    slug: 'image-cropper',
    name: 'Image Cropper & Ratio Preset',
    category: 'utilities',
    description: 'Crop images with aspect ratio presets (1:1, 16:9, 4:3, 3:2, freeform) and instant export.',
    iconName: 'Crop',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['Cropped PNG', 'JPG', 'WebP'],
    privacyNote: 'Cropping is performed in client canvas context.',
    browserSupportNote: 'HTML5 Canvas standard.',
    tags: ['crop', 'aspect ratio', 'image', 'photo', 'resize'],
    maxFileSizeMB: 30,
    componentId: 'ImageCropperTool',
  },
  {
    id: 'image-color-picker',
    slug: 'image-color-picker',
    name: 'Image Color Picker & Eyedropper',
    category: 'utilities',
    description: 'Inspect and sample exact pixel colors from any loaded image in HEX, RGB, and HSL.',
    iconName: 'Pipette',
    supportedInputTypes: ['PNG', 'JPG', 'WebP', 'SVG'],
    supportedOutputTypes: ['Sampled Color Codes'],
    privacyNote: 'Canvas pixel extraction happens exclusively on your device.',
    browserSupportNote: 'HTML5 Canvas getImageData standard.',
    tags: ['color', 'eyedropper', 'picker', 'pixel', 'image', 'hex'],
    maxFileSizeMB: 30,
    componentId: 'ImageColorPickerTool',
  },
  {
    id: 'file-info',
    slug: 'file-info',
    name: 'File Inspector & Magic Byte Validator',
    category: 'utilities',
    description: 'Inspect exact file sizes, MIME types, last-modified dates, magic byte signatures, and dimensions.',
    iconName: 'FileSearch',
    supportedInputTypes: ['Any File'],
    supportedOutputTypes: ['File Signature Report'],
    privacyNote: 'Only the first few bytes are read into memory to verify headers. Zero file transmission.',
    browserSupportNote: 'Requires FileReader and ArrayBuffer.',
    tags: ['file', 'mime', 'magic bytes', 'signature', 'inspect', 'size'],
    maxFileSizeMB: 100,
    componentId: 'FileInfoTool',
  },
];

export const ALL_TOOLS = TOOLS;

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS.find(
    (t) => t.slug === slug || t.id === slug || (slug === 'add-text-to-image' && t.slug === 'text-to-image')
  );
}

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getPopularTools(): ToolDefinition[] {
  return TOOLS.filter((t) => t.isPopular);
}

export function searchTools(query: string): ToolDefinition[] {
  const q = query.toLowerCase().trim();
  if (!q) return TOOLS;
  return TOOLS.filter((t) => {
    return (
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.toLowerCase().includes(q))
    );
  });
}

export function getRelatedTools(currentSlug: string, count = 3): ToolDefinition[] {
  const current = getToolBySlug(currentSlug);
  if (!current) return TOOLS.slice(0, count);
  return TOOLS.filter((t) => t.slug !== currentSlug && (t.category === current.category || t.isPopular)).slice(
    0,
    count
  );
}
