import { CategoryMeta, ToolCategory, ToolDefinition } from '../types';

export const CATEGORIES: CategoryMeta[] = [
  {
    id: 'converters',
    name: 'File Converters',
    description: 'Transform images, code, markup, and documents client-side.',
    iconName: 'RefreshCw',
    color: 'from-cyan-500/20 to-blue-500/10 border-cyan-500/30 text-cyan-400',
  },
  {
    id: 'documents',
    name: 'Document & PDF',
    description: 'Inspect, merge, and split PDF documents locally.',
    iconName: 'FileText',
    color: 'from-sky-500/20 to-indigo-500/10 border-sky-500/30 text-sky-400',
  },
  {
    id: 'developer',
    name: 'Developer & Text',
    description: 'Web Crypto hashes, JWT decoding, UUIDs, diffs, and formatting.',
    iconName: 'Code2',
    color: 'from-teal-500/20 to-emerald-500/10 border-teal-500/30 text-teal-400',
  },
  {
    id: 'generators',
    name: 'Generators',
    description: 'Create QR codes, favicons, meta tags, gradients, and mock data.',
    iconName: 'Sparkles',
    color: 'from-cyan-500/20 to-teal-500/10 border-cyan-500/30 text-cyan-300',
  },
  {
    id: 'utilities',
    name: 'Image & Utilities',
    description: 'Convert, compress, resize, edit, anonymize, extract, and inspect photos & files client-side.',
    iconName: 'Wrench',
    color: 'from-blue-500/20 to-cyan-500/10 border-blue-500/30 text-blue-400',
  },
];

export const TOOLS: ToolDefinition[] = [
  // --- A. File Converters ---
  {
    id: 'image-converter',
    slug: 'image-converter',
    name: 'Image Format Converter',
    category: 'converters',
    description: 'Convert between PNG, JPG, and WebP with custom dimensions, quality, and background color.',
    iconName: 'Image',
    supportedInputTypes: ['PNG', 'JPG', 'JPEG', 'WebP', 'SVG', 'GIF', 'BMP'],
    supportedOutputTypes: ['PNG', 'JPG', 'WebP'],
    privacyNote: 'Image rendering occurs directly on a local Canvas element. No data leaves your device.',
    browserSupportNote: 'Supported in all modern browsers supporting HTML5 Canvas2D.',
    tags: ['image', 'convert', 'png', 'jpg', 'webp', 'resize'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'ImageConverterTool',
  },
  {
    id: 'image-compressor',
    slug: 'image-compressor',
    name: 'Image Compressor & Optimizer',
    category: 'converters',
    description: 'Compress PNG, JPEG, and WebP images with real-time visual quality preview and size savings.',
    iconName: 'Minimize2',
    supportedInputTypes: ['PNG', 'JPG', 'JPEG', 'WebP'],
    supportedOutputTypes: ['PNG', 'JPG', 'WebP'],
    privacyNote: 'Compression is executed in browser memory with instant blob URL disposal.',
    browserSupportNote: 'Requires HTML5 Canvas toBlob API.',
    tags: ['compress', 'optimize', 'shrink', 'image', 'jpg', 'png'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'ImageCompressorTool',
  },
  {
    id: 'svg-converter',
    slug: 'svg-converter',
    name: 'SVG to PNG Converter',
    category: 'converters',
    description: 'Render scalable vector graphics (SVG) to raster PNG with custom scale factor and background.',
    iconName: 'FileCode',
    supportedInputTypes: ['SVG'],
    supportedOutputTypes: ['PNG', 'WebP'],
    privacyNote: 'SVG is loaded as an isolated image element without executing external scripts.',
    browserSupportNote: 'Supported on all standard browsers.',
    tags: ['svg', 'vector', 'png', 'export', 'rasterize'],
    maxFileSizeMB: 20,
    componentId: 'ImageConverterTool',
  },
  {
    id: 'json-csv-converter',
    slug: 'json-csv-converter',
    name: 'JSON ↔ CSV Converter',
    category: 'converters',
    description: 'Bidirectional conversion between JSON arrays and CSV tables with custom delimiters.',
    iconName: 'Table',
    supportedInputTypes: ['JSON', 'CSV'],
    supportedOutputTypes: ['CSV', 'JSON'],
    privacyNote: 'Parsing occurs via pure JavaScript in your active tab memory.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['json', 'csv', 'spreadsheet', 'data', 'table'],
    isPopular: true,
    maxFileSizeMB: 10,
    componentId: 'JsonCsvConverterTool',
  },
  {
    id: 'code-formatter',
    slug: 'code-formatter',
    name: 'Code Formatter & Minifier',
    category: 'converters',
    description: 'Validate, format, and minify JSON, XML, HTML, CSS, and JavaScript with clean syntax.',
    iconName: 'Braces',
    supportedInputTypes: ['JSON', 'XML', 'HTML', 'CSS', 'JS'],
    supportedOutputTypes: ['Formatted Code', 'Minified Code'],
    privacyNote: 'No external code formatters or servers are contacted.',
    browserSupportNote: 'Standard JavaScript execution.',
    tags: ['format', 'minify', 'beautify', 'json', 'xml', 'html', 'css', 'javascript'],
    isPopular: true,
    maxFileSizeMB: 10,
    componentId: 'CodeFormatterTool',
  },
  {
    id: 'markdown-preview',
    slug: 'markdown-preview',
    name: 'Markdown to HTML Converter',
    category: 'converters',
    description: 'Write Markdown with real-time live preview, sanitized HTML output, and file download.',
    iconName: 'BookOpen',
    supportedInputTypes: ['Markdown', 'MD', 'Text'],
    supportedOutputTypes: ['HTML', 'Preview'],
    privacyNote: 'HTML preview is rendered safely without script execution.',
    browserSupportNote: 'Standard JavaScript engine.',
    tags: ['markdown', 'html', 'preview', 'docs', 'readme'],
    maxFileSizeMB: 5,
    componentId: 'MarkdownPreviewTool',
  },
  {
    id: 'base64-converter',
    slug: 'base64-converter',
    name: 'Base64 Encoder & Decoder',
    category: 'converters',
    description: 'Encode and decode text strings or binary files to and from Base64 and Data URIs.',
    iconName: 'Binary',
    supportedInputTypes: ['Text', 'Files (Any type)'],
    supportedOutputTypes: ['Base64 String', 'Data URI', 'Decoded File'],
    privacyNote: 'Uses standard FileReader readAsDataURL and atob/btoa locally.',
    browserSupportNote: 'Supported on all modern browsers.',
    tags: ['base64', 'encode', 'decode', 'data uri', 'binary'],
    isPopular: true,
    maxFileSizeMB: 25,
    componentId: 'Base64Tool',
  },
  {
    id: 'url-encoder',
    slug: 'url-encoder',
    name: 'URL Encoder & Decoder',
    category: 'converters',
    description: 'Encode and decode standard URLs, URI components, and parse query parameters.',
    iconName: 'Link',
    supportedInputTypes: ['Text', 'URL'],
    supportedOutputTypes: ['Encoded URL', 'Decoded URL', 'Query Parameters'],
    privacyNote: 'Executes using native encodeURIComponent and decodeURIComponent.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['url', 'uri', 'encode', 'decode', 'querystring'],
    maxFileSizeMB: 5,
    componentId: 'UrlEncoderTool',
  },

  // --- B. Document & PDF Utilities ---
  {
    id: 'view-pdf',
    slug: 'view-pdf',
    name: 'PDF Viewer & Reader',
    category: 'documents',
    description: 'Read, inspect, zoom, rotate, and navigate single or multi-page PDF documents locally in your browser.',
    iconName: 'Eye',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Interactive Viewer'],
    privacyNote: 'Documents are rendered on client-side HTML5 Canvas. Zero remote server access.',
    browserSupportNote: 'Supported in all modern browsers via WebAssembly/Canvas.',
    tags: ['pdf', 'view', 'read', 'preview', 'reader', 'canvas'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfViewerTool',
  },
  {
    id: 'merge-pdf',
    slug: 'merge-pdf',
    name: 'Merge PDF Documents',
    category: 'documents',
    description: 'Combine multiple PDF documents into a single organized file in any desired sequence.',
    iconName: 'Files',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Merged PDF'],
    privacyNote: 'Documents are assembled in client RAM via pdf-lib and downloaded straight to your drive.',
    browserSupportNote: 'Requires modern browser memory support.',
    tags: ['pdf', 'merge', 'combine', 'join', 'concat'],
    isPopular: true,
    maxFileSizeMB: 100,
    componentId: 'PdfMergeSplitTool',
  },
  {
    id: 'split-pdf',
    slug: 'split-pdf',
    name: 'Split PDF & Extract Pages',
    category: 'documents',
    description: 'Split multi-page PDFs into separate files or extract custom page ranges (e.g., 1-3, 5, 8-10) with ZIP bundling.',
    iconName: 'Scissors',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Split PDF', 'ZIP Archive'],
    privacyNote: 'Pages are extracted directly in browser memory without uploading.',
    browserSupportNote: 'Requires client-side ArrayBuffer support.',
    tags: ['pdf', 'split', 'separate', 'extract', 'ranges'],
    isPopular: true,
    maxFileSizeMB: 100,
    componentId: 'PdfMergeSplitTool',
  },
  {
    id: 'organize-pdf-pages',
    slug: 'organize-pdf-pages',
    name: 'Rearrange & Organize PDF Pages',
    category: 'documents',
    description: 'Reorder, duplicate, move, and organize PDF pages visually with drag-and-drop page tiles.',
    iconName: 'Layers',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Organized PDF'],
    privacyNote: 'All reordering and visual previews execute locally in your session.',
    browserSupportNote: 'HTML5 Drag and Drop with Canvas thumbnails.',
    tags: ['pdf', 'organize', 'reorder', 'sort', 'rearrange', 'pages'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfPageOrganizerTool',
  },
  {
    id: 'rotate-pdf-pages',
    slug: 'rotate-pdf-pages',
    name: 'Rotate PDF Pages',
    category: 'documents',
    description: 'Rotate individual pages or the entire PDF document by 90°, 180°, or 270° clockwise.',
    iconName: 'RotateCw',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Rotated PDF'],
    privacyNote: 'Rotation metadata is updated in client memory using pdf-lib.',
    browserSupportNote: 'Standard modern browser.',
    tags: ['pdf', 'rotate', 'orientation', 'turn', 'landscape', 'portrait'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfPageOrganizerTool',
  },
  {
    id: 'remove-pdf-pages',
    slug: 'remove-pdf-pages',
    name: 'Remove & Delete PDF Pages',
    category: 'documents',
    description: 'Delete unwanted blank pages, cover sheets, or confidential sections from any PDF document.',
    iconName: 'Trash2',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Trimmed PDF'],
    privacyNote: 'Selected pages are removed entirely before generating the clean PDF.',
    browserSupportNote: 'Client-side PDF compilation.',
    tags: ['pdf', 'delete', 'remove', 'strip', 'cut', 'pages'],
    maxFileSizeMB: 50,
    componentId: 'PdfPageOrganizerTool',
  },
  {
    id: 'extract-pdf-pages',
    slug: 'extract-pdf-pages',
    name: 'Extract PDF Pages',
    category: 'documents',
    description: 'Select and export specific pages into a brand new standalone PDF document.',
    iconName: 'FileOutput',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Extracted PDF'],
    privacyNote: 'Extracted pages are cloned in browser memory without sending data to servers.',
    browserSupportNote: 'Supported in all standard browsers.',
    tags: ['pdf', 'extract', 'export', 'select', 'pages'],
    maxFileSizeMB: 50,
    componentId: 'PdfPageOrganizerTool',
  },
  {
    id: 'images-to-pdf',
    slug: 'images-to-pdf',
    name: 'Images to PDF Converter',
    category: 'documents',
    description: 'Convert JPG, PNG, and WebP images into a clean multi-page PDF document with custom margins and sizing.',
    iconName: 'Images',
    supportedInputTypes: ['JPG', 'PNG', 'JPEG', 'WebP'],
    supportedOutputTypes: ['PDF Document'],
    privacyNote: 'Image rendering and PDF compilation occur 100% inside your browser.',
    browserSupportNote: 'Requires Canvas2D and pdf-lib.',
    tags: ['pdf', 'images', 'jpg to pdf', 'png to pdf', 'convert', 'photos'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'ImagesToPdfTool',
  },
  {
    id: 'pdf-to-images',
    slug: 'pdf-to-images',
    name: 'PDF to Images Converter',
    category: 'documents',
    description: 'Rasterize and convert PDF pages into high-resolution JPG or PNG images with ZIP archive download.',
    iconName: 'Image',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['JPG Images', 'PNG Images', 'ZIP Archive'],
    privacyNote: 'PDF rendering executes entirely on local Canvas elements without server processing.',
    browserSupportNote: 'Requires PDF.js Canvas renderer support.',
    tags: ['pdf', 'convert', 'images', 'pdf to jpg', 'pdf to png', 'export'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfToImagesTool',
  },
  {
    id: 'crop-pdf',
    slug: 'crop-pdf',
    name: 'Crop PDF Margins',
    category: 'documents',
    description: 'Trim unwanted white borders, header/footer margins, or adjust printable boundaries directly in your browser.',
    iconName: 'Crop',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Cropped PDF'],
    privacyNote: 'Crop boxes are applied natively to PDF page geometry in client RAM.',
    browserSupportNote: 'Supported in all modern browsers.',
    tags: ['pdf', 'crop', 'margins', 'trim', 'cut', 'borders'],
    maxFileSizeMB: 50,
    componentId: 'PdfCropTool',
  },
  {
    id: 'add-watermark',
    slug: 'add-watermark',
    name: 'Add Watermark to PDF',
    category: 'documents',
    description: 'Stamp customizable text watermarks, confidential badges, or copyright labels with live opacity and angle preview.',
    iconName: 'Stamp',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Watermarked PDF'],
    privacyNote: 'Watermark vector text is embedded in client memory. No document upload.',
    browserSupportNote: 'Requires standard font embedding in pdf-lib.',
    tags: ['pdf', 'watermark', 'stamp', 'confidential', 'draft', 'copyright'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfWatermarkTool',
  },
  {
    id: 'add-page-numbers',
    slug: 'add-page-numbers',
    name: 'Add Page Numbers to PDF',
    category: 'documents',
    description: 'Number PDF pages automatically with customizable positions, font sizes, and format templates (e.g., Page X of Y).',
    iconName: 'Hash',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Numbered PDF'],
    privacyNote: 'Page number text is stamped directly into the vector stream on your device.',
    browserSupportNote: 'Supported on all modern browsers.',
    tags: ['pdf', 'page numbers', 'pagination', 'header', 'footer', 'numbering'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfPageNumbersTool',
  },
  {
    id: 'flatten-pdf',
    slug: 'flatten-pdf',
    name: 'Flatten PDF Form Fields',
    category: 'documents',
    description: 'Permanently flatten interactive PDF form inputs and annotations into read-only vector graphics.',
    iconName: 'FileCheck2',
    supportedInputTypes: ['PDF Form'],
    supportedOutputTypes: ['Flattened PDF'],
    privacyNote: 'Form fields are baked into the page vector stream in browser memory.',
    browserSupportNote: 'pdf-lib AcroForm flattening.',
    tags: ['pdf', 'flatten', 'form', 'lock', 'readonly', 'acroform'],
    maxFileSizeMB: 50,
    componentId: 'PdfFlattenTool',
  },
  {
    id: 'pdf-metadata',
    slug: 'pdf-metadata',
    name: 'PDF Metadata & Info Inspector',
    category: 'documents',
    description: 'Inspect PDF page counts, author, creator, creation date, and encryption status locally.',
    iconName: 'FileCheck',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Document Metadata Table', 'JSON'],
    privacyNote: 'Parsed with pdf-lib directly in your browser without transmitting document contents.',
    browserSupportNote: 'Requires ArrayBuffer and TypedArray support.',
    tags: ['pdf', 'metadata', 'inspector', 'page count', 'info'],
    maxFileSizeMB: 50,
    componentId: 'PdfMetadataTool',
  },
  {
    id: 'edit-pdf-document-info',
    slug: 'edit-pdf-document-info',
    name: 'Edit PDF Document Info',
    category: 'documents',
    description: 'Modify PDF title, author, subject, keywords, and producer tags with instant client-side rebuild.',
    iconName: 'FileSpreadsheet',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Updated PDF'],
    privacyNote: 'Metadata dictionary is updated in-memory without contacting external servers.',
    browserSupportNote: 'Supported across all modern browsers.',
    tags: ['pdf', 'metadata', 'edit', 'title', 'author', 'properties'],
    maxFileSizeMB: 50,
    componentId: 'PdfMetadataTool',
  },
  {
    id: 'remove-pdf-metadata',
    slug: 'remove-pdf-metadata',
    name: 'Remove PDF Metadata (Sanitize)',
    category: 'documents',
    description: 'Strip hidden author information, software signatures, creation timestamps, and privacy tags from PDF files.',
    iconName: 'ShieldAlert',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Sanitized PDF'],
    privacyNote: 'All metadata properties are scrubbed clean in client memory.',
    browserSupportNote: 'Supported across all modern browsers.',
    tags: ['pdf', 'metadata', 'remove', 'strip', 'sanitize', 'privacy', 'clean'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfMetadataTool',
  },
  {
    id: 'protect-pdf',
    slug: 'protect-pdf',
    name: 'Protect PDF (Password & Permissions)',
    category: 'documents',
    description: 'Encrypt PDF files with strong user/owner passwords and customizable printing/copying permission restrictions.',
    iconName: 'Lock',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Encrypted PDF'],
    privacyNote: '128-bit encryption cipher applied strictly in browser memory. Passwords never enter storage or telemetry.',
    browserSupportNote: 'Supported across all modern browsers via Web Crypto.',
    tags: ['pdf', 'protect', 'password', 'encrypt', 'lock', 'security', 'permissions'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfProtectTool',
  },
  {
    id: 'unlock-pdf',
    slug: 'unlock-pdf',
    name: 'Unlock PDF (Decrypt with Password)',
    category: 'documents',
    description: 'Remove password protection and permission restrictions from PDF documents when you provide the authorized password.',
    iconName: 'Unlock',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Decrypted PDF'],
    privacyNote: 'Decrypted strictly in local RAM. No password cracking or bypassing is supported.',
    browserSupportNote: 'Requires WebAssembly/Canvas and pdfjs-dist.',
    tags: ['pdf', 'unlock', 'decrypt', 'password', 'remove password', 'open'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfUnlockTool',
  },
  {
    id: 'pdf-merge-split',
    slug: 'pdf-merge-split',
    name: 'PDF Merge & Split Tool',
    category: 'documents',
    description: 'Merge multiple PDF files into one or extract specific page ranges (e.g., 1-3, 5) securely.',
    iconName: 'Files',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Merged PDF', 'Split PDF'],
    privacyNote: 'Documents are assembled in client RAM via pdf-lib and downloaded straight to your drive.',
    browserSupportNote: 'Requires modern browser memory support (recommended < 100MB per file).',
    tags: ['pdf', 'merge', 'split', 'combine', 'extract pages'],
    maxFileSizeMB: 100,
    componentId: 'PdfMergeSplitTool',
  },
  {
    id: 'annotate-pdf',
    slug: 'annotate-pdf',
    name: 'Annotate & Draw on PDF',
    category: 'documents',
    description: 'Add text notes, yellow highlighters, stamps, shapes, and freehand markup directly onto PDF pages.',
    iconName: 'PenTool',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Annotated PDF'],
    privacyNote: 'Annotations are drawn directly in browser memory and embedded into the PDF vector stream.',
    browserSupportNote: 'Supported in all modern browsers with HTML5 Canvas.',
    tags: ['pdf', 'annotate', 'draw', 'highlight', 'markup', 'stamp', 'notes', 'pen'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfAnnotateTool',
  },
  {
    id: 'fill-pdf-forms',
    slug: 'fill-pdf-forms',
    name: 'Fill PDF Form Fields',
    category: 'documents',
    description: 'Fill interactive AcroForm text fields, checkboxes, and dropdowns without third-party software.',
    iconName: 'CheckSquare',
    supportedInputTypes: ['PDF Form'],
    supportedOutputTypes: ['Filled PDF', 'Flattened PDF'],
    privacyNote: 'Form values are injected client-side into AcroForm dictionaries in RAM.',
    browserSupportNote: 'Supported across all browsers via pdf-lib.',
    tags: ['pdf', 'forms', 'fill', 'acroform', 'inputs', 'checkbox', 'text field'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfFormsTool',
  },
  {
    id: 'create-pdf-forms',
    slug: 'create-pdf-forms',
    name: 'Create Interactive PDF Forms',
    category: 'documents',
    description: 'Design interactive AcroForm text boxes, checkboxes, dropdowns, and buttons onto any PDF canvas.',
    iconName: 'FormInput',
    supportedInputTypes: ['PDF', 'Blank Form'],
    supportedOutputTypes: ['Interactive AcroForm PDF'],
    privacyNote: 'AcroForm field dictionaries are structured in browser memory.',
    browserSupportNote: 'Supported across all modern browsers.',
    tags: ['pdf', 'form builder', 'create form', 'acroform', 'interactive fields'],
    maxFileSizeMB: 50,
    componentId: 'PdfFormsTool',
  },
  {
    id: 'nup-pdf',
    slug: 'nup-pdf',
    name: 'N-Up Pages Per Sheet (2, 4, 9 on 1)',
    category: 'documents',
    description: 'Fit 2, 4, 6, 9, or 16 pages per printable sheet for handouts, booklets, and paper saving.',
    iconName: 'Grid',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['N-Up Composited PDF'],
    privacyNote: 'Pages are mathematically re-scaled and arranged in client memory.',
    browserSupportNote: 'Supported in all modern browsers.',
    tags: ['pdf', 'n-up', 'pages per sheet', 'multiple pages', '2-up', '4-up', 'grid', 'handouts'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfNUpTool',
  },
  {
    id: 'halve-pdf',
    slug: 'halve-pdf',
    name: 'Split 2-Page Spreads (Halve Pages)',
    category: 'documents',
    description: 'Cut scanned 2-page book spreads or side-by-side pages in half into single portrait pages.',
    iconName: 'Split',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Halved PDF'],
    privacyNote: 'Pages are clipped and doubled locally in browser memory.',
    browserSupportNote: 'Supported across all modern browsers.',
    tags: ['pdf', 'halve', 'split spreads', 'book scan', '2-page split', 'cut pages in half'],
    maxFileSizeMB: 50,
    componentId: 'PdfNUpTool',
  },
  {
    id: 'overlay-pdf',
    slug: 'overlay-pdf',
    name: 'PDF Overlay & Letterhead Compositor',
    category: 'documents',
    description: 'Superimpose stationary, letterheads, backgrounds, or templates onto another PDF document.',
    iconName: 'Layers',
    supportedInputTypes: ['PDF (Base)', 'PDF (Overlay)'],
    supportedOutputTypes: ['Composited PDF'],
    privacyNote: 'Overlay pages are composited as vector XObjects in client memory.',
    browserSupportNote: 'Supported across all modern browsers.',
    tags: ['pdf', 'overlay', 'letterhead', 'template', 'stationary', 'superimpose', 'stamp'],
    maxFileSizeMB: 50,
    componentId: 'PdfOverlayTool',
  },
  {
    id: 'compare-pdf',
    slug: 'compare-pdf',
    name: 'PDF Visual Diff & Comparator',
    category: 'documents',
    description: 'Compare two PDF documents side-by-side with pixel-level difference detection and split curtain slider.',
    iconName: 'GitCompare',
    supportedInputTypes: ['PDF (Doc A)', 'PDF (Doc B)'],
    supportedOutputTypes: ['Visual Diff', 'Comparison Report'],
    privacyNote: 'Pixel comparison is computed entirely on local HTML5 Canvas elements.',
    browserSupportNote: 'Requires Canvas2D with getImageData API.',
    tags: ['pdf', 'compare', 'diff', 'difference', 'side by side', 'visual diff', 'revisions'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfCompareTool',
  },
  {
    id: 'bookmarks-pdf',
    slug: 'bookmarks-pdf',
    name: 'PDF Bookmarks & Table of Contents',
    category: 'documents',
    description: 'Build document outlines, chapter markers, and automatically prepend a clean Table of Contents page.',
    iconName: 'Bookmark',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Updated PDF with TOC'],
    privacyNote: 'Bookmark index and Table of Contents page are generated in client memory.',
    browserSupportNote: 'Supported across all modern browsers.',
    tags: ['pdf', 'bookmarks', 'table of contents', 'toc', 'outline', 'chapters', 'index'],
    maxFileSizeMB: 50,
    componentId: 'PdfBookmarksTool',
  },
  {
    id: 'compress-pdf',
    slug: 'compress-pdf',
    name: 'Compress PDF & Reduce File Size',
    category: 'documents',
    description: 'Reduce PDF file sizes dramatically using lossy visual downsampling or lossless stream compaction.',
    iconName: 'Minimize2',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Compressed PDF'],
    privacyNote: 'Compression is executed entirely in browser memory with zero file transmission.',
    browserSupportNote: 'Supported in all modern browsers via Canvas2D & pdf-lib.',
    tags: ['pdf', 'compress', 'shrink', 'reduce size', 'optimize', 'dpi', 'downsample'],
    isPopular: true,
    maxFileSizeMB: 100,
    componentId: 'PdfCompressTool',
  },
  {
    id: 'extract-pdf-images',
    slug: 'extract-pdf-images',
    name: 'Extract Images from PDF',
    category: 'documents',
    description: 'Extract raw embedded raster images, illustrations, and photos from PDF files with ZIP archive export.',
    iconName: 'Image',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['PNG Images', 'JPG Images', 'ZIP Archive'],
    privacyNote: 'Images are extracted directly in browser RAM without server processing.',
    browserSupportNote: 'Requires Canvas2D & JSZip support.',
    tags: ['pdf', 'extract images', 'images', 'photos', 'illustrations', 'zip'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfExtractImagesTool',
  },
  {
    id: 'repair-pdf',
    slug: 'repair-pdf',
    name: 'Repair Corrupted PDF & Salvage Streams',
    category: 'documents',
    description: 'Diagnose and recover unreadable or corrupted PDF files by rebuilding cross-reference tables and fixing broken trailers.',
    iconName: 'Wrench',
    supportedInputTypes: ['PDF (Corrupted/Damaged)'],
    supportedOutputTypes: ['Repaired PDF', 'Diagnostic Report'],
    privacyNote: 'Byte analysis and cross-reference reconstruction occur 100% client-side in RAM.',
    browserSupportNote: 'Resilient byte parser and stream sanitizer.',
    tags: ['pdf', 'repair', 'corrupted', 'fix', 'salvage', 'broken', 'recover', 'xref'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'PdfRepairTool',
  },
  {
    id: 'pdf-a',
    slug: 'pdf-a',
    name: 'PDF/A Long-Term Archival Sanitizer',
    category: 'documents',
    description: 'Standardize documents for ISO 19005 archival preservation with sRGB OutputIntents and XMP schema metadata.',
    iconName: 'FileCheck2',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['PDF/A Compliant Document'],
    privacyNote: 'XMP metadata injection and script purging happen locally on your device.',
    browserSupportNote: 'Supported across all modern browsers.',
    tags: ['pdf', 'pdf/a', 'archival', 'iso', 'preservation', 'xmp', 'legal', 'compliance'],
    maxFileSizeMB: 50,
    componentId: 'PdfArchivalTool',
  },
  {
    id: 'web-optimize-pdf',
    slug: 'web-optimize-pdf',
    name: 'Web Stream & Object Optimizer',
    category: 'documents',
    description: 'Compacts internal object trees and stream dictionaries for efficient sequential reading.',
    iconName: 'Globe',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Optimized PDF'],
    privacyNote: 'Object streams are deflated and reorganized in local browser memory.',
    browserSupportNote: 'Standard pdf-lib object stream support.',
    tags: ['pdf', 'web optimize', 'fast web view', 'stream', 'compact', 'deflate'],
    maxFileSizeMB: 50,
    componentId: 'PdfWebOptimizeTool',
  },
  {
    id: 'ocr-pdf',
    slug: 'ocr-pdf',
    name: 'PDF OCR & Text Layer Extractor',
    category: 'documents',
    description: 'Inspect document text layers locally with zero-cloud upload guarantee and WASM architecture roadmap.',
    iconName: 'Search',
    supportedInputTypes: ['PDF'],
    supportedOutputTypes: ['Extracted Text Layer', 'Searchable PDF (WASM roadmap)'],
    privacyNote: 'Zero server uploads. Document text is extracted locally in client memory.',
    browserSupportNote: 'Requires client-side text layer parser.',
    tags: ['pdf', 'ocr', 'text', 'extract text', 'searchable', 'scan', 'read text'],
    maxFileSizeMB: 50,
    componentId: 'PdfOcrTool',
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    name: 'Word to PDF (.docx / .doc)',
    category: 'documents',
    description: 'Convert Microsoft Word documents into standard PDF format locally with zero-server-upload privacy guarantee.',
    iconName: 'FileText',
    supportedInputTypes: ['DOCX', 'DOC'],
    supportedOutputTypes: ['PDF'],
    privacyNote: 'Zero cloud uploads. Includes native offline export guides and WASM roadmap.',
    browserSupportNote: 'Native offline workflows supported.',
    tags: ['word to pdf', 'docx to pdf', 'convert docx', 'office', 'documents'],
    maxFileSizeMB: 50,
    componentId: 'OfficeConvertNoticeTool',
  },
  {
    id: 'excel-to-pdf',
    slug: 'excel-to-pdf',
    name: 'Excel to PDF (.xlsx / .xls)',
    category: 'documents',
    description: 'Convert spreadsheets and tables to PDF without server uploads.',
    iconName: 'FileSpreadsheet',
    supportedInputTypes: ['XLSX', 'XLS'],
    supportedOutputTypes: ['PDF'],
    privacyNote: 'Zero cloud uploads. Confidential spreadsheets remain in local RAM.',
    browserSupportNote: 'Native offline workflows supported.',
    tags: ['excel to pdf', 'xlsx to pdf', 'convert xlsx', 'spreadsheet', 'sheets'],
    maxFileSizeMB: 50,
    componentId: 'OfficeConvertNoticeTool',
  },
  {
    id: 'powerpoint-to-pdf',
    slug: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF (.pptx / .ppt)',
    category: 'documents',
    description: 'Convert presentation slide decks into PDF without server tracking.',
    iconName: 'Presentation',
    supportedInputTypes: ['PPTX', 'PPT'],
    supportedOutputTypes: ['PDF'],
    privacyNote: 'Zero cloud uploads. Slide contents stay strictly on your device.',
    browserSupportNote: 'Native offline workflows supported.',
    tags: ['powerpoint to pdf', 'pptx to pdf', 'convert pptx', 'slides', 'presentation'],
    maxFileSizeMB: 50,
    componentId: 'OfficeConvertNoticeTool',
  },

  // --- C. Developer & Text Utilities ---
  {
    id: 'uuid-generator',
    slug: 'uuid-generator',
    name: 'UUID / GUID Generator',
    category: 'developer',
    description: 'Generate single or bulk cryptographically secure RFC 4122 v4 UUIDs using the Web Crypto API.',
    iconName: 'Fingerprint',
    supportedInputTypes: ['None'],
    supportedOutputTypes: ['UUID v4 Strings'],
    privacyNote: 'Generated with window.crypto.randomUUID() / getRandomValues(). Never logged.',
    browserSupportNote: 'Web Crypto API standard.',
    tags: ['uuid', 'guid', 'v4', 'random', 'id'],
    isPopular: true,
    componentId: 'UuidGeneratorTool',
  },
  {
    id: 'password-generator',
    slug: 'password-generator',
    name: 'Strong Password & Passphrase Generator',
    category: 'developer',
    description: 'Create high-entropy passwords and diceware-style passphrases with entropy analysis.',
    iconName: 'KeyRound',
    supportedInputTypes: ['None'],
    supportedOutputTypes: ['Cryptographically Secure Passwords'],
    privacyNote: 'Built with window.crypto.getRandomValues(). Keys exist only in temporary UI state.',
    browserSupportNote: 'Web Crypto CSPRNG.',
    tags: ['password', 'passphrase', 'security', 'crypto', 'generator'],
    isPopular: true,
    componentId: 'PasswordGeneratorTool',
  },
  {
    id: 'hash-generator',
    slug: 'hash-generator',
    name: 'Cryptographic Hash Generator',
    category: 'developer',
    description: 'Compute SHA-256, SHA-384, and SHA-512 hashes for text and files using native SubtleCrypto.',
    iconName: 'ShieldCheck',
    supportedInputTypes: ['Text', 'File'],
    supportedOutputTypes: ['Hex Hashes (SHA-256, SHA-384, SHA-512)'],
    privacyNote: 'Processed via window.crypto.subtle.digest(). Zero network calls.',
    browserSupportNote: 'Web Crypto SubtleCrypto standard.',
    tags: ['hash', 'sha256', 'sha512', 'crypto', 'checksum'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'HashGeneratorTool',
  },
  {
    id: 'jwt-decoder',
    slug: 'jwt-decoder',
    name: 'JWT Token Decoder (Offline)',
    category: 'developer',
    description: 'Decode and inspect JSON Web Token headers, claims, and expiry dates locally without verification claims.',
    iconName: 'Key',
    supportedInputTypes: ['JWT String'],
    supportedOutputTypes: ['Parsed JSON Header & Payload'],
    privacyNote: 'Safe offline parsing. Never transmits your auth tokens across the internet.',
    browserSupportNote: 'Supported in all browsers.',
    tags: ['jwt', 'token', 'decode', 'json web token', 'auth', 'claims'],
    isPopular: true,
    componentId: 'JwtDecoderTool',
  },
  {
    id: 'timestamp-converter',
    slug: 'timestamp-converter',
    name: 'Unix Timestamp Converter',
    category: 'developer',
    description: 'Convert Unix epoch seconds/milliseconds to UTC, local formatted date, and relative time.',
    iconName: 'Clock',
    supportedInputTypes: ['Unix Timestamp', 'ISO Date', 'Date String'],
    supportedOutputTypes: ['Formatted Dates', 'Epoch Seconds/ms'],
    privacyNote: 'Local date arithmetic only.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['timestamp', 'unix', 'epoch', 'date', 'time'],
    componentId: 'TimestampConverterTool',
  },
  {
    id: 'color-converter',
    slug: 'color-converter',
    name: 'Color Format Converter',
    category: 'developer',
    description: 'Convert color values between HEX, RGB, HSL, and OKLCH with interactive visual picker.',
    iconName: 'Palette',
    supportedInputTypes: ['HEX', 'RGB', 'HSL'],
    supportedOutputTypes: ['HEX', 'RGB', 'HSL', 'CSS Code'],
    privacyNote: 'Runs in client memory.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['color', 'hex', 'rgb', 'hsl', 'css', 'palette'],
    componentId: 'ColorConverterTool',
  },
  {
    id: 'regex-tester',
    slug: 'regex-tester',
    name: 'Regular Expression Tester',
    category: 'developer',
    description: 'Test RegExp patterns against sample text with live match highlight, capture groups, and flags.',
    iconName: 'Terminal',
    supportedInputTypes: ['Regex Pattern', 'Test Text'],
    supportedOutputTypes: ['Match Highlights', 'Capture Group Inspector'],
    privacyNote: 'Evaluated locally in JavaScript sandbox.',
    browserSupportNote: 'Supported across all modern browsers.',
    tags: ['regex', 'regexp', 'match', 'pattern', 'test'],
    componentId: 'RegexTesterTool',
  },
  {
    id: 'text-utilities',
    slug: 'text-utilities',
    name: 'Text Utilities & Diff Viewer',
    category: 'developer',
    description: 'Word/character counters, case converters, line sorters, deduplication, and visual text diff.',
    iconName: 'AlignLeft',
    supportedInputTypes: ['Text'],
    supportedOutputTypes: ['Transformed Text', 'Side-by-Side Diff'],
    privacyNote: 'All string transformations are computed entirely in browser RAM.',
    browserSupportNote: 'Supported in all browsers.',
    tags: ['text', 'count', 'diff', 'case', 'sort', 'dedup', 'whitespace'],
    isPopular: true,
    maxFileSizeMB: 5,
    componentId: 'TextUtilitiesTool',
  },

  // --- D. Generator Tools ---
  {
    id: 'text-to-image',
    slug: 'text-to-image',
    name: 'Text to Image & Typography Studio',
    category: 'generators',
    description: 'Add watermarks, quotes, memes, and styled typography overlay onto photos, or generate high-res cards from scratch.',
    iconName: 'Type',
    supportedInputTypes: ['Text', 'PNG', 'JPG', 'WebP', 'SVG'],
    supportedOutputTypes: ['PNG Image', 'JPEG Image', 'WebP Image'],
    privacyNote: '100% client-side HTML5 Canvas typography rendering. No images or text ever leave your device.',
    browserSupportNote: 'Supported in all modern browsers with HTML5 Canvas and Blob APIs.',
    tags: ['text to image', 'add text to image', 'watermark', 'typography', 'meme', 'caption', 'quote', 'banner', 'overlay', 'poster'],
    isPopular: true,
    isNew: true,
    maxFileSizeMB: 40,
    componentId: 'TextToImageTool',
  },
  {
    id: 'qr-code-generator',
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    category: 'generators',
    description: 'Generate high-resolution customizable QR codes with custom colors, margin, and SVG/PNG download.',
    iconName: 'QrCode',
    supportedInputTypes: ['Text', 'URL', 'VCard', 'Wi-Fi'],
    supportedOutputTypes: ['PNG Image', 'SVG Vector', 'Data URL'],
    privacyNote: 'Generated offline via pure JavaScript QR generator canvas.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['qr', 'qrcode', 'barcode', 'generator', 'svg', 'png'],
    isPopular: true,
    componentId: 'QrCodeGeneratorTool',
  },
  {
    id: 'favicon-generator',
    slug: 'favicon-generator',
    name: 'Favicon & App Icon Generator',
    category: 'generators',
    description: 'Transform any square image into a complete favicon package (16px, 32px, 48px, Apple Touch, PWA) in a ZIP.',
    iconName: 'Layers',
    supportedInputTypes: ['PNG', 'JPG', 'SVG', 'WebP'],
    supportedOutputTypes: ['ZIP Archive with Icons & Manifest'],
    privacyNote: 'Resizing and ZIP packaging are processed entirely in browser memory.',
    browserSupportNote: 'Requires HTML5 Canvas and JSZip.',
    tags: ['favicon', 'icon', 'apple-touch-icon', 'pwa', 'manifest', 'zip'],
    isPopular: true,
    maxFileSizeMB: 20,
    componentId: 'FaviconGeneratorTool',
  },
  {
    id: 'random-generator',
    slug: 'random-generator',
    name: 'Random & Design Generator Suite',
    category: 'generators',
    description: 'Generate random numbers, list shufflers, slugs, lorem ipsum, CSS gradients, shadows, and buttons.',
    iconName: 'Sliders',
    supportedInputTypes: ['Parameters'],
    supportedOutputTypes: ['Generated Data', 'CSS Snippets'],
    privacyNote: 'Pure local mathematical generation.',
    browserSupportNote: 'Supported in all modern browsers.',
    tags: ['random', 'lorem', 'slug', 'css', 'gradient', 'shadow', 'button'],
    componentId: 'GeneratorSuiteTool',
  },
  {
    id: 'slug-generator',
    slug: 'slug-generator',
    name: 'URL Slug Generator',
    category: 'generators',
    description: 'Convert article titles, product names, and foreign phrases into clean, SEO-friendly URL slugs.',
    iconName: 'Link',
    supportedInputTypes: ['Text'],
    supportedOutputTypes: ['URL Slug'],
    privacyNote: '100% local text formatting with diacritic normalization.',
    browserSupportNote: 'Supported in all browsers.',
    tags: ['slug', 'url', 'seo', 'permalink', 'clean url', 'format'],
    isPopular: true,
    isNew: true,
    componentId: 'GeneratorSuiteTool',
  },
  {
    id: 'username-generator',
    slug: 'username-generator',
    name: 'Username & Handle Generator',
    category: 'generators',
    description: 'Generate developer, aesthetic, gamer, or minimalist usernames powered by Web Crypto CSPRNG.',
    iconName: 'UserCheck',
    supportedInputTypes: ['Parameters'],
    supportedOutputTypes: ['Usernames List'],
    privacyNote: 'Handles are generated client-side with zero external API calls.',
    browserSupportNote: 'Requires Web Crypto API.',
    tags: ['username', 'handle', 'alias', 'gamertag', 'random', 'crypto'],
    isPopular: true,
    isNew: true,
    componentId: 'GeneratorSuiteTool',
  },
  {
    id: 'palette-generator',
    slug: 'palette-generator',
    name: 'Color Palette & Harmony Generator',
    category: 'generators',
    description: 'Generate triadic, complementary, analogous, and monochromatic palettes with lockable swatches and WCAG contrast.',
    iconName: 'Palette',
    supportedInputTypes: ['Base Color', 'Harmony Rule'],
    supportedOutputTypes: ['CSS Variables', 'HEX / RGB / HSL'],
    privacyNote: 'Mathematical color wheel calculation in client memory.',
    browserSupportNote: 'Standard browser support.',
    tags: ['palette', 'color', 'harmony', 'triadic', 'complementary', 'css', 'design', 'wcag'],
    isPopular: true,
    isNew: true,
    componentId: 'GeneratorSuiteTool',
  },
  {
    id: 'gradient-generator',
    slug: 'gradient-generator',
    name: 'CSS Gradient Generator',
    category: 'generators',
    description: 'Create multi-stop linear and radial gradients with interactive canvas preview and CSS export.',
    iconName: 'Sparkles',
    supportedInputTypes: ['Color Stops', 'Angles'],
    supportedOutputTypes: ['CSS Code', 'Live Preview'],
    privacyNote: 'CSS generation with immediate preview.',
    browserSupportNote: 'All modern CSS3 browsers.',
    tags: ['gradient', 'css', 'linear', 'radial', 'design', 'background', 'style'],
    isPopular: true,
    isNew: true,
    componentId: 'GeneratorSuiteTool',
  },
  {
    id: 'shadow-generator',
    slug: 'shadow-generator',
    name: 'CSS Box & Text Shadow Generator',
    category: 'generators',
    description: 'Design smooth multi-layered box shadows and text elevations with real-time surface preview.',
    iconName: 'Box',
    supportedInputTypes: ['Offsets', 'Blur', 'Spread'],
    supportedOutputTypes: ['CSS box-shadow'],
    privacyNote: 'Calculated instantly in local DOM.',
    browserSupportNote: 'Standard CSS3 support.',
    tags: ['shadow', 'box-shadow', 'elevation', 'css', 'card', 'glow'],
    isPopular: true,
    isNew: true,
    componentId: 'GeneratorSuiteTool',
  },
  {
    id: 'robots-generator',
    slug: 'robots-generator',
    name: 'Robots.txt Generator',
    category: 'generators',
    description: 'Generate search crawler directives, AI bot blocks (GPTBot, ClaudeBot), and sitemap references.',
    iconName: 'Shield',
    supportedInputTypes: ['Form Inputs'],
    supportedOutputTypes: ['robots.txt file'],
    privacyNote: 'Formatted client-side.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['robots', 'seo', 'crawler', 'spider', 'ai bots', 'disallow'],
    isNew: true,
    componentId: 'WebBoilerplateTool',
  },
  {
    id: 'sitemap-generator',
    slug: 'sitemap-generator',
    name: 'Sitemap.xml Generator',
    category: 'generators',
    description: 'Generate XML sitemaps with custom page paths, change frequencies, priorities, and lastmod timestamps.',
    iconName: 'Globe',
    supportedInputTypes: ['Domain', 'Path List'],
    supportedOutputTypes: ['sitemap.xml file'],
    privacyNote: 'XML generation entirely in local memory.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['sitemap', 'xml', 'seo', 'google search', 'indexing'],
    isNew: true,
    componentId: 'WebBoilerplateTool',
  },
  {
    id: 'open-graph-generator',
    slug: 'open-graph-generator',
    name: 'Open Graph & Social Cards Generator',
    category: 'generators',
    description: 'Create social meta tags with live card previews for Facebook, Twitter/X, Discord, and Google.',
    iconName: 'Share2',
    supportedInputTypes: ['Title', 'Description', 'Image URL'],
    supportedOutputTypes: ['HTML Meta Tags'],
    privacyNote: 'Tags rendered locally.',
    browserSupportNote: 'Universal browser support.',
    tags: ['open graph', 'og', 'social card', 'meta tags', 'twitter card', 'seo'],
    isPopular: true,
    isNew: true,
    componentId: 'WebBoilerplateTool',
  },
  {
    id: 'passphrase-generator',
    slug: 'passphrase-generator',
    name: 'Passphrase & PIN Generator',
    category: 'developer',
    description: 'Create memorable Diceware-style passphrases and numeric PINs using Web Crypto CSPRNG.',
    iconName: 'Lock',
    supportedInputTypes: ['Word Count', 'Separator'],
    supportedOutputTypes: ['Secure Passphrase', 'PIN'],
    privacyNote: 'Web Crypto API entropy calculation. Zero network telemetry.',
    browserSupportNote: 'Supported across all modern browsers.',
    tags: ['passphrase', 'pin', 'diceware', 'password', 'security', 'crypto'],
    isPopular: true,
    isNew: true,
    componentId: 'PasswordGeneratorTool',
  },
  {
    id: 'web-boilerplate',
    slug: 'web-boilerplate',
    name: 'Web Config & Meta Tag Generator',
    category: 'generators',
    description: 'Create SEO-ready Open Graph meta tags, HTML5 boilerplate, robots.txt, and sitemap.xml.',
    iconName: 'Globe',
    supportedInputTypes: ['Form Inputs'],
    supportedOutputTypes: ['HTML', 'robots.txt', 'sitemap.xml'],
    privacyNote: 'Outputs are formatted strings generated on the fly.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['seo', 'opengraph', 'robots', 'sitemap', 'boilerplate', 'html5'],
    componentId: 'WebBoilerplateTool',
  },

  // --- E. Image & Utility Tools ---
  {
    id: 'convert-image',
    slug: 'convert-image',
    name: 'Universal Image Converter',
    category: 'utilities',
    description: 'Convert between PNG, JPG, WebP, AVIF, SVG, BMP, and ICO formats instantly in your browser.',
    iconName: 'RefreshCw',
    supportedInputTypes: ['PNG', 'JPG', 'JPEG', 'WebP', 'AVIF', 'SVG', 'BMP', 'GIF'],
    supportedOutputTypes: ['PNG', 'JPG', 'WebP', 'AVIF', 'BMP', 'ICO'],
    privacyNote: 'Converted entirely inside browser memory via Canvas / OffscreenCanvas. 0 bytes uploaded.',
    browserSupportNote: 'Supported in all modern HTML5 Canvas browsers.',
    tags: ['image', 'convert', 'png', 'jpg', 'webp', 'avif', 'bmp', 'ico', 'format'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'jpg-to-png',
    slug: 'jpg-to-png',
    name: 'JPG to PNG Converter',
    category: 'utilities',
    description: 'Convert JPEG and JPG photos into lossless PNG format with transparent canvas support.',
    iconName: 'ArrowRightLeft',
    supportedInputTypes: ['JPEG', 'JPG'],
    supportedOutputTypes: ['PNG'],
    privacyNote: 'Zero network transfer. Rendered client-side.',
    browserSupportNote: 'Standard HTML5 Canvas support.',
    tags: ['jpg', 'png', 'convert', 'lossless', 'image', 'photo'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'png-to-jpg',
    slug: 'png-to-jpg',
    name: 'PNG to JPG Converter',
    category: 'utilities',
    description: 'Convert PNG graphics and screenshots to lightweight JPG format with custom background color.',
    iconName: 'FileImage',
    supportedInputTypes: ['PNG'],
    supportedOutputTypes: ['JPEG', 'JPG'],
    privacyNote: 'Processed purely in local device RAM.',
    browserSupportNote: 'Standard HTML5 Canvas support.',
    tags: ['png', 'jpg', 'convert', 'jpeg', 'image'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'convert-to-webp',
    slug: 'convert-to-webp',
    name: 'Convert Image to WebP',
    category: 'utilities',
    description: 'Generate ultra-fast modern WebP images with 30-80% smaller file sizes than standard JPG.',
    iconName: 'Zap',
    supportedInputTypes: ['PNG', 'JPG', 'JPEG', 'BMP', 'SVG'],
    supportedOutputTypes: ['WebP'],
    privacyNote: 'WebP encoding is performed natively by your browser engine.',
    browserSupportNote: 'Supported in modern Chrome, Edge, Firefox, and Safari.',
    tags: ['webp', 'convert', 'web', 'fast', 'compress', 'image'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'convert-to-avif',
    slug: 'convert-to-avif',
    name: 'Convert Image to AVIF',
    category: 'utilities',
    description: 'Convert images to next-generation AVIF format for unmatched quality-to-size ratios.',
    iconName: 'Sparkles',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['AVIF'],
    privacyNote: 'Client-side encoding via browser canvas.',
    browserSupportNote: 'Supported on Chrome 94+, Firefox 113+, Safari 16.4+.',
    tags: ['avif', 'convert', 'nextgen', 'hdr', 'image'],
    isNew: true,
    maxFileSizeMB: 40,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'svg-to-raster',
    slug: 'svg-to-png',
    name: 'SVG to PNG Rasterizer',
    category: 'utilities',
    description: 'Render vector SVG illustrations into high-resolution pixel graphics safely without executing scripts.',
    iconName: 'Shapes',
    supportedInputTypes: ['SVG'],
    supportedOutputTypes: ['PNG', 'JPEG', 'WebP'],
    privacyNote: 'SVG is sanitized to strip malicious scripts before rendering.',
    browserSupportNote: 'Supported in all modern browsers.',
    tags: ['svg', 'rasterize', 'png', 'scale', 'vector', 'image'],
    maxFileSizeMB: 20,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'ico-maker',
    slug: 'ico-generator',
    name: 'Favicon ICO Maker',
    category: 'utilities',
    description: 'Create multi-resolution Windows .ICO files (16x16, 32x32, 48x48, 64x64, 128x128, 256x256).',
    iconName: 'Bookmark',
    supportedInputTypes: ['PNG', 'JPG', 'WebP', 'SVG'],
    supportedOutputTypes: ['ICO', 'PNG'],
    privacyNote: 'Binary ICO container built directly in memory via ArrayBuffer.',
    browserSupportNote: 'Universal browser support.',
    tags: ['ico', 'favicon', 'icon', 'windows', 'generator', 'image'],
    maxFileSizeMB: 20,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'heic-to-jpg',
    slug: 'heic-to-jpg',
    name: 'HEIC to JPG / PNG Converter',
    category: 'utilities',
    description: 'Convert iPhone & Apple HEIC/HEIF camera photos into universally compatible JPGs.',
    iconName: 'Smartphone',
    supportedInputTypes: ['HEIC', 'HEIF'],
    supportedOutputTypes: ['JPG', 'PNG'],
    privacyNote: 'Decoded locally using client-side WebAssembly parser. No cloud upload.',
    browserSupportNote: 'Standard modern browser.',
    tags: ['heic', 'heif', 'apple', 'iphone', 'photo', 'convert', 'image'],
    isNew: true,
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'compress-image',
    slug: 'compress-image',
    name: 'Image Compressor & Optimizer',
    category: 'utilities',
    description: 'Reduce image file size with real-time before/after preview, quality slider, and byte savings readout.',
    iconName: 'Minimize2',
    supportedInputTypes: ['PNG', 'JPG', 'JPEG', 'WebP', 'AVIF'],
    supportedOutputTypes: ['JPEG', 'WebP', 'PNG', 'AVIF'],
    privacyNote: 'Zero network requests. Compression runs on local GPU/CPU canvas.',
    browserSupportNote: 'Supported in all modern browsers.',
    tags: ['compress', 'optimize', 'shrink', 'quality', 'slider', 'image', 'photo'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'compress-to-target-size',
    slug: 'compress-to-target-size',
    name: 'Compress to Target File Size',
    category: 'utilities',
    description: 'Specify an exact target file size (e.g. Under 200 KB, Under 1 MB) and auto-optimize quality.',
    iconName: 'Gauge',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['JPEG', 'WebP'],
    privacyNote: 'Binary-search optimization passes occur entirely in client RAM.',
    browserSupportNote: 'Standard modern browser.',
    tags: ['target size', 'kb', 'mb', 'budget', 'limit', 'compress', 'image'],
    isPopular: true,
    maxFileSizeMB: 40,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'lossless-optimizer',
    slug: 'lossless-optimizer',
    name: 'Lossless Image Optimizer',
    category: 'utilities',
    description: 'Strip unnecessary metadata chunks, color profiles, and compress PNG/JPEG streams with 0% quality loss.',
    iconName: 'Shield',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['PNG', 'JPG', 'WebP'],
    privacyNote: 'Completely lossless local stream sanitization in browser memory.',
    browserSupportNote: 'Universal browser support.',
    tags: ['lossless', 'clean', 'perfect', 'metadata', 'shrink', 'optimize', 'image'],
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'compare-images',
    slug: 'compare-images',
    name: 'Visual Image Comparison Lab',
    category: 'utilities',
    description: 'Compare two images side-by-side or with an interactive split slider with zoom and pixel inspection.',
    iconName: 'Eye',
    supportedInputTypes: ['PNG', 'JPG', 'WebP', 'AVIF'],
    supportedOutputTypes: ['Visual Diff', 'Comparison View'],
    privacyNote: 'Images loaded only in local browser memory.',
    browserSupportNote: 'HTML5 Canvas standard.',
    tags: ['compare', 'slider', 'diff', 'inspection', 'zoom', 'image'],
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'resize-image',
    slug: 'resize-image',
    name: 'Image Resizer & Dimension Scaler',
    category: 'utilities',
    description: 'Resize images by exact pixels, percentage scale, or aspect ratio presets with bicubic interpolation.',
    iconName: 'Maximize2',
    supportedInputTypes: ['PNG', 'JPG', 'WebP', 'AVIF', 'BMP'],
    supportedOutputTypes: ['PNG', 'JPG', 'WebP'],
    privacyNote: 'Resampled locally using hardware-accelerated 2D canvas.',
    browserSupportNote: 'All modern browsers.',
    tags: ['resize', 'scale', 'dimensions', 'width', 'height', 'percent', 'image'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'crop-image',
    slug: 'crop-image',
    name: 'Image Cropper & Aspect Ratio Tool',
    category: 'utilities',
    description: 'Interactive visual cropping with freeform handles and standard aspect ratios (1:1, 16:9, 4:3, 9:16).',
    iconName: 'Crop',
    supportedInputTypes: ['PNG', 'JPG', 'WebP', 'AVIF', 'BMP'],
    supportedOutputTypes: ['PNG', 'JPG', 'WebP'],
    privacyNote: 'Cropped directly in memory. Original file never modified.',
    browserSupportNote: 'Supported in all modern browsers.',
    tags: ['crop', 'aspect ratio', 'square', '16:9', 'ratio', 'trim', 'image'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'rotate-flip-image',
    slug: 'rotate-flip-image',
    name: 'Rotate, Flip & Straighten Image',
    category: 'utilities',
    description: 'Rotate 90°, 180°, 270°, flip horizontally or vertically, and fine-tune straightening angles.',
    iconName: 'RotateCw',
    supportedInputTypes: ['PNG', 'JPG', 'WebP', 'AVIF', 'BMP'],
    supportedOutputTypes: ['PNG', 'JPG', 'WebP'],
    privacyNote: 'Local canvas coordinate transformation.',
    browserSupportNote: 'Universal browser support.',
    tags: ['rotate', 'flip', 'mirror', 'straighten', 'orientation', 'image'],
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'expand-canvas-pad',
    slug: 'expand-canvas-pad',
    name: 'Expand Canvas & Add Padding',
    category: 'utilities',
    description: 'Add borders, margins, or transparent padding around any image to fit specific square or banner dimensions.',
    iconName: 'Square',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['PNG', 'JPG', 'WebP'],
    privacyNote: 'Rendered in local canvas.',
    browserSupportNote: 'Standard HTML5 Canvas.',
    tags: ['padding', 'margin', 'expand', 'border', 'canvas', 'image'],
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'image-filters-adjustments',
    slug: 'image-filters-adjustments',
    name: 'Image Filters & Color Adjustments',
    category: 'utilities',
    description: 'Fine-tune brightness, contrast, saturation, temperature, tint, sepia, grayscale, invert, and duotone.',
    iconName: 'Sliders',
    supportedInputTypes: ['PNG', 'JPG', 'WebP', 'AVIF'],
    supportedOutputTypes: ['PNG', 'JPG', 'WebP'],
    privacyNote: 'Shader/Canvas pixel filter processing runs on local GPU/CPU.',
    browserSupportNote: 'Supported in all modern browsers.',
    tags: ['filter', 'brightness', 'contrast', 'saturation', 'grayscale', 'sepia', 'photo', 'image'],
    isPopular: true,
    maxFileSizeMB: 40,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'blur-pixelate-redact',
    slug: 'blur-pixelate-redact',
    name: 'Blur, Pixelate & Redact Tool',
    category: 'utilities',
    description: 'Anonymize sensitive text, faces, license plates, or credit cards with gaussian blur or pixelation boxes.',
    iconName: 'EyeOff',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['PNG', 'JPG', 'WebP'],
    privacyNote: 'Redactions are rasterized directly into the pixel buffer, making them non-reversible.',
    browserSupportNote: 'Standard HTML5 Canvas.',
    tags: ['redact', 'blur', 'pixelate', 'privacy', 'censor', 'anonymous', 'image'],
    isPopular: true,
    maxFileSizeMB: 40,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'watermark-image',
    slug: 'watermark-image',
    name: 'Image Watermark & Text Overlay',
    category: 'utilities',
    description: 'Stamp customized text or logo watermarks with opacity, rotation, tiled patterns, and positioning.',
    iconName: 'Stamp',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['PNG', 'JPG', 'WebP'],
    privacyNote: 'Watermark rasterized onto canvas client-side.',
    browserSupportNote: 'Supported in all browsers.',
    tags: ['watermark', 'text', 'logo', 'copyright', 'stamp', 'image'],
    isPopular: true,
    maxFileSizeMB: 40,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'rounded-corners-border',
    slug: 'rounded-corners-border',
    name: 'Rounded Corners & Shadows',
    category: 'utilities',
    description: 'Add smooth rounded corners, decorative borders, and soft drop shadows for modern mockups.',
    iconName: 'SquareCode',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['PNG', 'WebP'],
    privacyNote: 'Canvas clipping path rendered locally.',
    browserSupportNote: 'Standard modern browser.',
    tags: ['rounded', 'corners', 'border', 'shadow', 'radius', 'image'],
    maxFileSizeMB: 40,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'meme-generator',
    slug: 'meme-generator',
    name: 'Meme Generator & Text Styler',
    category: 'utilities',
    description: 'Create classic and modern memes with bold impact text, outline strokes, and customizable positioning.',
    iconName: 'Smile',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['PNG', 'JPEG'],
    privacyNote: 'Text composited client-side on canvas.',
    browserSupportNote: 'All browsers.',
    tags: ['meme', 'impact', 'text', 'funny', 'generator', 'caption', 'image'],
    maxFileSizeMB: 30,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'change-background-color',
    slug: 'change-background-color',
    name: 'Background Color & Gradients',
    category: 'utilities',
    description: 'Replace transparent image backgrounds with solid studio colors, smooth linear gradients, or soft water hues.',
    iconName: 'PaintBucket',
    supportedInputTypes: ['PNG', 'WebP', 'SVG'],
    supportedOutputTypes: ['PNG', 'JPEG', 'WebP'],
    privacyNote: 'Local canvas fill operation in browser memory.',
    browserSupportNote: 'Standard HTML5 Canvas.',
    tags: ['background', 'color', 'gradient', 'transparent', 'fill', 'image'],
    maxFileSizeMB: 40,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'transparent-channel-inspector',
    slug: 'transparent-channel-inspector',
    name: 'Alpha Channel & Transparency Inspector',
    category: 'utilities',
    description: 'Inspect alpha transparency channels, identify semi-transparent halos, and verify alpha masks.',
    iconName: 'Grid',
    supportedInputTypes: ['PNG', 'WebP', 'SVG'],
    supportedOutputTypes: ['PNG'],
    privacyNote: 'Visual inspection performed in local browser memory.',
    browserSupportNote: 'Canvas getImageData support.',
    tags: ['transparency', 'alpha', 'mask', 'checkerboard', 'inspect', 'image'],
    maxFileSizeMB: 40,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'background-remover',
    slug: 'background-remover',
    name: 'Background Remover (Local In-Browser)',
    category: 'utilities',
    description: 'Client-side background separation. Transparent status notice: never uploads your photos to cloud servers.',
    iconName: 'Scissors',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['PNG'],
    privacyNote: '100% In-Browser. No remote machine learning servers or cloud APIs are used.',
    browserSupportNote: 'Local neural models require WebGL/WebGPU support on your device.',
    tags: ['background', 'remover', 'cutout', 'transparent', 'wasm', 'image'],
    isNew: true,
    maxFileSizeMB: 25,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'view-exif-metadata',
    slug: 'view-exif-metadata',
    name: 'EXIF & GPS Metadata Viewer',
    category: 'utilities',
    description: 'Inspect camera model, GPS coordinates, date taken, exposure settings, software, and lens details.',
    iconName: 'FileSearch',
    supportedInputTypes: ['JPEG', 'JPG', 'TIFF', 'PNG'],
    supportedOutputTypes: ['Interactive Report', 'JSON'],
    privacyNote: 'EXIF bytes decoded locally. Zero telemetry or location queries sent.',
    browserSupportNote: 'Requires FileReader and ArrayBuffer.',
    tags: ['exif', 'metadata', 'gps', 'camera', 'iso', 'shutter', 'location', 'photo'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'remove-exif-metadata',
    slug: 'remove-exif-metadata',
    name: 'EXIF & Metadata Stripper (Sanitize)',
    category: 'utilities',
    description: 'Completely remove GPS location, camera serial numbers, author tags, and timestamps before sharing.',
    iconName: 'ShieldAlert',
    supportedInputTypes: ['JPEG', 'JPG', 'PNG', 'WebP'],
    supportedOutputTypes: ['JPEG', 'PNG', 'WebP'],
    privacyNote: 'Guaranteed 100% metadata scrub. Sanitized file contains purely raw image pixels.',
    browserSupportNote: 'Supported in all modern browsers.',
    tags: ['exif', 'strip', 'clean', 'privacy', 'gps', 'remove', 'scrub', 'sanitize'],
    isPopular: true,
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'privacy-risk-scanner',
    slug: 'privacy-risk-scanner',
    name: 'Photo Privacy Risk Scanner',
    category: 'utilities',
    description: 'Scan photos for hidden location tags, camera serial numbers, author names, and embedded thumbnails.',
    iconName: 'AlertTriangle',
    supportedInputTypes: ['JPEG', 'JPG', 'PNG', 'TIFF'],
    supportedOutputTypes: ['Privacy Audit Report'],
    privacyNote: 'Audit executed locally in your browser.',
    browserSupportNote: 'Standard browser support.',
    tags: ['privacy', 'audit', 'scanner', 'risk', 'gps', 'security', 'image'],
    isNew: true,
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'fix-photo-orientation',
    slug: 'fix-photo-orientation',
    name: 'EXIF Photo Orientation Fixer',
    category: 'utilities',
    description: 'Correct rotated or upside-down smartphone photos by baking the EXIF orientation tag into pixel geometry.',
    iconName: 'RotateCcw',
    supportedInputTypes: ['JPEG', 'JPG'],
    supportedOutputTypes: ['JPEG', 'PNG'],
    privacyNote: 'Local orientation correction in RAM.',
    browserSupportNote: 'All modern browsers.',
    tags: ['orientation', 'exif', 'rotate', 'fix', 'phone', 'camera', 'photo'],
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'extract-text-ocr',
    slug: 'extract-text-ocr',
    name: 'Client-Side OCR (Text Extractor)',
    category: 'utilities',
    description: 'Extract text, numbers, and receipt data from images locally in the browser with zero cloud transmission.',
    iconName: 'FileText',
    supportedInputTypes: ['PNG', 'JPG', 'WebP', 'BMP'],
    supportedOutputTypes: ['Editable Text', 'Clipboard'],
    privacyNote: 'OCR model runs client-side via WebAssembly. Zero document text leaves your computer.',
    browserSupportNote: 'Requires WebAssembly support.',
    tags: ['ocr', 'text', 'extract', 'scan', 'receipt', 'document', 'image'],
    isPopular: true,
    maxFileSizeMB: 30,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'enhance-document-scan',
    slug: 'enhance-document-scan',
    name: 'Scan Contrast & Binarizer',
    category: 'utilities',
    description: 'Enhance smartphone document photos into crisp black-and-white scans, remove shadows, and increase legibility.',
    iconName: 'FileCheck',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['PNG', 'JPEG'],
    privacyNote: 'Adaptive thresholding runs locally in canvas context.',
    browserSupportNote: 'Canvas2D standard.',
    tags: ['scan', 'binarize', 'document', 'contrast', 'black-and-white', 'clean', 'image'],
    maxFileSizeMB: 40,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'image-cropper',
    slug: 'image-cropper',
    name: 'Image Cropper & Ratio Preset',
    category: 'utilities',
    description: 'Crop images with aspect ratio presets (1:1, 16:9, 4:3, 3:2, freeform) and instant export.',
    iconName: 'Crop',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['Cropped PNG', 'JPG', 'WebP'],
    privacyNote: 'Cropping is performed in client canvas context.',
    browserSupportNote: 'HTML5 Canvas standard.',
    tags: ['crop', 'aspect ratio', 'image', 'photo', 'resize'],
    maxFileSizeMB: 30,
    componentId: 'ImageCropperTool',
  },
  {
    id: 'image-color-picker',
    slug: 'image-color-picker',
    name: 'Image Color Picker & Eyedropper',
    category: 'utilities',
    description: 'Inspect and sample exact pixel colors from any loaded image in HEX, RGB, and HSL.',
    iconName: 'Pipette',
    supportedInputTypes: ['PNG', 'JPG', 'WebP', 'SVG'],
    supportedOutputTypes: ['Sampled Color Codes'],
    privacyNote: 'Canvas pixel extraction happens exclusively on your device.',
    browserSupportNote: 'HTML5 Canvas getImageData standard.',
    tags: ['color', 'eyedropper', 'picker', 'pixel', 'image', 'hex'],
    maxFileSizeMB: 30,
    componentId: 'ImageColorPickerTool',
  },
  {
    id: 'extract-color-palette',
    slug: 'extract-color-palette',
    name: 'Color Palette Extractor',
    category: 'utilities',
    description: 'Extract dominant color palettes, harmonic swatches, and CSS color variables from any photo.',
    iconName: 'Palette',
    supportedInputTypes: ['PNG', 'JPG', 'WebP', 'AVIF'],
    supportedOutputTypes: ['Color Swatches', 'CSS Variables', 'JSON'],
    privacyNote: 'Color quantization executed on local worker/canvas.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['palette', 'dominant', 'swatch', 'css', 'colors', 'quantize', 'image'],
    isPopular: true,
    maxFileSizeMB: 40,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'color-blind-preview',
    slug: 'color-blind-preview',
    name: 'Color Blindness Simulator',
    category: 'utilities',
    description: 'Test image accessibility under Protanopia, Deuteranopia, Tritanopia, and Achromatopsia color filters.',
    iconName: 'Eye',
    supportedInputTypes: ['PNG', 'JPG', 'WebP', 'SVG'],
    supportedOutputTypes: ['PNG', 'Simulation Preview'],
    privacyNote: 'Matrix transformation computed locally.',
    browserSupportNote: 'Standard browser canvas.',
    tags: ['colorblind', 'accessibility', 'a11y', 'wcag', 'protanopia', 'deuteranopia', 'image'],
    maxFileSizeMB: 40,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'image-contrast-checker',
    slug: 'image-contrast-checker',
    name: 'Color Contrast Analyzer (WCAG)',
    category: 'utilities',
    description: 'Calculate WCAG AA/AAA contrast ratios between sampled image colors and background text.',
    iconName: 'CheckCircle2',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['WCAG Pass/Fail Report'],
    privacyNote: 'Mathematical contrast formula evaluated locally.',
    browserSupportNote: 'Supported in all modern browsers.',
    tags: ['contrast', 'wcag', 'aa', 'aaa', 'accessibility', 'ratio', 'color'],
    maxFileSizeMB: 30,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'batch-convert-images',
    slug: 'batch-convert-images',
    name: 'Batch Image Converter & ZIP',
    category: 'utilities',
    description: 'Convert dozens of images simultaneously to WebP, PNG, JPG, or AVIF and download as a single ZIP archive.',
    iconName: 'Boxes',
    supportedInputTypes: ['PNG', 'JPG', 'JPEG', 'WebP', 'BMP', 'AVIF', 'SVG'],
    supportedOutputTypes: ['ZIP Archive', 'WebP', 'PNG', 'JPEG'],
    privacyNote: 'Batch queue and ZIP creation run entirely in browser memory.',
    browserSupportNote: 'Supported in all modern browsers with JSZip.',
    tags: ['batch', 'multi', 'convert', 'zip', 'bulk', 'archive', 'image'],
    isPopular: true,
    maxFileSizeMB: 100,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'batch-resize-images',
    slug: 'batch-resize-images',
    name: 'Batch Image Resizer',
    category: 'utilities',
    description: 'Resize an entire folder of photos to uniform dimensions, percentage scales, or bounding boxes with ZIP export.',
    iconName: 'Maximize',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['ZIP Archive', 'PNG', 'JPEG'],
    privacyNote: 'Processed locally in browser memory.',
    browserSupportNote: 'Standard browser canvas & JSZip.',
    tags: ['batch', 'resize', 'scale', 'bulk', 'zip', 'image'],
    maxFileSizeMB: 100,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'batch-watermark-images',
    slug: 'batch-watermark-images',
    name: 'Batch Watermark Stamper',
    category: 'utilities',
    description: 'Apply copyright text, signatures, or logo watermarks to multiple photos at once in a single batch.',
    iconName: 'Stamp',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['ZIP Archive', 'JPEG', 'PNG'],
    privacyNote: 'Watermarking runs entirely on client device.',
    browserSupportNote: 'Canvas2D and JSZip.',
    tags: ['batch', 'watermark', 'copyright', 'stamp', 'multi', 'image'],
    maxFileSizeMB: 100,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'image-to-base64',
    slug: 'image-to-base64',
    name: 'Image to Base64 & Data URI',
    category: 'utilities',
    description: 'Convert images into Base64 strings, HTML <img> tags, CSS background-image code, and Data URIs.',
    iconName: 'Code',
    supportedInputTypes: ['PNG', 'JPG', 'WebP', 'SVG', 'GIF', 'ICO'],
    supportedOutputTypes: ['Data URI', 'Base64 String', 'CSS Code', 'HTML'],
    privacyNote: 'Base64 string generated in local memory.',
    browserSupportNote: 'Supported in all modern browsers.',
    tags: ['base64', 'data-uri', 'css', 'html', 'developer', 'inline', 'image'],
    isPopular: true,
    maxFileSizeMB: 20,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'favicon-pwa-icon-pack',
    slug: 'favicon-pwa-icon-pack',
    name: 'Favicon & PWA Icon Pack Generator',
    category: 'utilities',
    description: 'Generate all standard favicon and PWA icon sizes (16x16, 32x32, 180x180, 192x192, 512x512) + manifest.json.',
    iconName: 'Package',
    supportedInputTypes: ['PNG', 'SVG', 'JPEG'],
    supportedOutputTypes: ['ZIP Archive with Icons & Manifest'],
    privacyNote: 'Icon resizing and ZIP packing occur locally.',
    browserSupportNote: 'Requires HTML5 Canvas and JSZip.',
    tags: ['favicon', 'pwa', 'manifest', 'icons', 'web', 'apple-touch-icon', 'image'],
    isPopular: true,
    maxFileSizeMB: 25,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'opengraph-image-maker',
    slug: 'opengraph-image-maker',
    name: 'Open Graph (OG) Image Maker',
    category: 'utilities',
    description: 'Generate standard 1200x630 social share preview cards for Twitter, Facebook, LinkedIn, and Discord.',
    iconName: 'Share2',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['PNG', 'JPEG'],
    privacyNote: 'Rendered locally on 1200×630 canvas.',
    browserSupportNote: 'Supported across all browsers.',
    tags: ['opengraph', 'og', 'twitter', 'social', 'banner', '1200x630', 'image'],
    isNew: true,
    maxFileSizeMB: 30,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'responsive-srcset-generator',
    slug: 'responsive-srcset-generator',
    name: 'Responsive Srcset & Picture Generator',
    category: 'utilities',
    description: 'Export multiple responsive image widths (320w, 640w, 1024w, 1920w) and copy the <picture> HTML code.',
    iconName: 'Layout',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['ZIP Archive', 'HTML Code'],
    privacyNote: 'Responsive images and HTML snippets created client-side.',
    browserSupportNote: 'Standard browser canvas.',
    tags: ['srcset', 'responsive', 'picture', 'html', 'breakpoints', 'developer', 'image'],
    maxFileSizeMB: 40,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'quality-vs-size-lab',
    slug: 'quality-vs-size-lab',
    name: 'Quality-vs-Size Optimization Lab',
    category: 'utilities',
    description: 'Test WebP vs JPG vs AVIF across multiple quality levels simultaneously to find the sweet spot.',
    iconName: 'BarChart2',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['Interactive Matrix', 'Optimized Image'],
    privacyNote: 'All format variations encoded in local browser RAM.',
    browserSupportNote: 'All modern browsers.',
    tags: ['quality', 'size', 'matrix', 'comparison', 'lab', 'optimization', 'image'],
    isPopular: true,
    maxFileSizeMB: 30,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'social-media-pack',
    slug: 'social-media-pack',
    name: 'Social Media Image Pack',
    category: 'utilities',
    description: 'Crop and resize one photo into Instagram, YouTube, X/Twitter, LinkedIn, and TikTok sizes in one click.',
    iconName: 'Share',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['ZIP Archive'],
    privacyNote: 'Batch social resizing processed locally.',
    browserSupportNote: 'Standard browser canvas & JSZip.',
    tags: ['social', 'instagram', 'youtube', 'tiktok', 'twitter', 'linkedin', 'presets', 'image'],
    isPopular: true,
    maxFileSizeMB: 40,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'screenshot-beautifier',
    slug: 'screenshot-beautifier',
    name: 'Screenshot Beautifier & Frame',
    category: 'utilities',
    description: 'Frame raw screenshots on a gorgeous water-glass or twilight backdrop with soft drop shadows and padding.',
    iconName: 'Monitor',
    supportedInputTypes: ['PNG', 'JPG', 'WebP'],
    supportedOutputTypes: ['PNG Image'],
    privacyNote: 'Composited on 2D canvas client-side.',
    browserSupportNote: 'All modern browsers.',
    tags: ['screenshot', 'beautify', 'mockup', 'frame', 'gradient', 'shadow', 'image'],
    isPopular: true,
    isNew: true,
    maxFileSizeMB: 40,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'file-size-budget-tool',
    slug: 'file-size-budget-tool',
    name: 'Image File-Size Budget Tester',
    category: 'utilities',
    description: 'Simulate mobile network load times (3G, 4G, 5G) and test against performance budgets (e.g., < 150 KB).',
    iconName: 'Activity',
    supportedInputTypes: ['PNG', 'JPG', 'WebP', 'AVIF', 'SVG'],
    supportedOutputTypes: ['Performance Report'],
    privacyNote: 'Performance calculations run locally without network pings.',
    browserSupportNote: 'Standard browser support.',
    tags: ['budget', 'cwv', 'performance', 'latency', '3g', '4g', 'speed', 'image'],
    maxFileSizeMB: 50,
    componentId: 'ImageToolRunner',
  },
  {
    id: 'file-info',
    slug: 'file-info',
    name: 'File Inspector & Magic Byte Validator',
    category: 'utilities',
    description: 'Inspect exact file sizes, MIME types, last-modified dates, magic byte signatures, and dimensions.',
    iconName: 'FileSearch',
    supportedInputTypes: ['Any File'],
    supportedOutputTypes: ['File Signature Report'],
    privacyNote: 'Only the first few bytes are read into memory to verify headers. Zero file transmission.',
    browserSupportNote: 'Requires FileReader and ArrayBuffer.',
    tags: ['file', 'mime', 'magic bytes', 'signature', 'inspect', 'size'],
    maxFileSizeMB: 100,
    componentId: 'FileInfoTool',
  },
];

export const ALL_TOOLS = TOOLS;

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOLS.find(
    (t) => t.slug === slug || t.id === slug || (slug === 'add-text-to-image' && t.slug === 'text-to-image')
  );
}

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getPopularTools(): ToolDefinition[] {
  return TOOLS.filter((t) => t.isPopular);
}

export function searchTools(query: string): ToolDefinition[] {
  const q = query.toLowerCase().trim();
  if (!q) return TOOLS;
  return TOOLS.filter((t) => {
    return (
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q) ||
      t.tags.some((tag) => tag.toLowerCase().includes(q))
    );
  });
}

export function getRelatedTools(currentSlug: string, count = 3): ToolDefinition[] {
  const current = getToolBySlug(currentSlug);
  if (!current) return TOOLS.slice(0, count);
  return TOOLS.filter((t) => t.slug !== currentSlug && (t.category === current.category || t.isPopular)).slice(
    0,
    count
  );
}
